
var createFFmepgModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmepgModule) {
  createFFmepgModule = createFFmepgModule || {};


var c;c||(c=typeof createFFmepgModule !== 'undefined' ? createFFmepgModule : {});var aa,ba;c.ready=new Promise(function(a,b){aa=a;ba=b});Object.getOwnPropertyDescriptor(c.ready,"_main")||(Object.defineProperty(c.ready,"_main",{configurable:!0,get:function(){f("You are getting _main on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_main",{configurable:!0,set:function(){f("You are setting _main on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_decode")||(Object.defineProperty(c.ready,"_decode",{configurable:!0,get:function(){f("You are getting _decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_decode",{configurable:!0,set:function(){f("You are setting _decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_encode")||(Object.defineProperty(c.ready,"_encode",{configurable:!0,get:function(){f("You are getting _encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_encode",{configurable:!0,set:function(){f("You are setting _encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_open_audio_decode")||(Object.defineProperty(c.ready,"_open_audio_decode",{configurable:!0,get:function(){f("You are getting _open_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_open_audio_decode",{configurable:!0,set:function(){f("You are setting _open_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_audio_decode")||(Object.defineProperty(c.ready,"_audio_decode",{configurable:!0,get:function(){f("You are getting _audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_audio_decode",{configurable:!0,set:function(){f("You are setting _audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_close_audio_decode")||(Object.defineProperty(c.ready,"_close_audio_decode",{configurable:!0,get:function(){f("You are getting _close_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_close_audio_decode",{configurable:!0,set:function(){f("You are setting _close_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_open_audio_encode")||(Object.defineProperty(c.ready,"_open_audio_encode",{configurable:!0,get:function(){f("You are getting _open_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_open_audio_encode",{configurable:!0,set:function(){f("You are setting _open_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_audio_encode")||(Object.defineProperty(c.ready,"_audio_encode",{configurable:!0,get:function(){f("You are getting _audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_audio_encode",{configurable:!0,set:function(){f("You are setting _audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"_close_audio_encode")||(Object.defineProperty(c.ready,"_close_audio_encode",{configurable:!0,get:function(){f("You are getting _close_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"_close_audio_encode",{configurable:!0,set:function(){f("You are setting _close_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"___stdio_exit")||(Object.defineProperty(c.ready,"___stdio_exit",{configurable:!0,get:function(){f("You are getting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"___stdio_exit",{configurable:!0,set:function(){f("You are setting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(c.ready,"onRuntimeInitialized")||(Object.defineProperty(c.ready,"onRuntimeInitialized",{configurable:!0,get:function(){f("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(c.ready,"onRuntimeInitialized",{configurable:!0,set:function(){f("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var ca=Object.assign({},c),da="./this.program",ea=(a,b)=>{throw b;},fa="object"==typeof window,h="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ia=!fa&&!ha&&!h;if(c.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var m="",t,u,v;
function ja(a){if(!(a instanceof ka)){var b=a;a&&"object"==typeof a&&a.stack&&(b=[a,a.stack]);x("exiting due to exception: "+b)}}var fs,ma,na;
if(ha){if("object"!=typeof process||"function"!=typeof require)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");m=h?require("path").dirname(m)+"/":__dirname+"/";na=()=>{ma||(fs=require("fs"),ma=require("path"))};t=function(a,b){na();a=ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=t(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);
return a};u=(a,b,d)=>{na();a=ma.normalize(a);fs.readFile(a,function(e,g){e?d(e):b(g.buffer)})};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;});process.on("unhandledRejection",function(a){throw a;});ea=(a,b)=>{if(noExitRuntime||0<oa)throw process.exitCode=a,b;ja(b);process.exit(a)};c.inspect=function(){return"[Emscripten Module object]"}}else if(ia){if("object"==typeof process&&"function"===
typeof require||"object"==typeof window||"function"==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");"undefined"!=typeof read&&(t=function(a){return read(a)});v=function(a){if("function"==typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"==typeof a);return a};u=function(a,b){setTimeout(()=>
b(v(a)),0)};"function"==typeof quit&&(ea=(a,b)=>{if(oa)throw b;ja(b);quit(a)});"undefined"!=typeof print&&("undefined"==typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!=typeof printErr?printErr:print)}else if(fa||h){h?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src);_scriptDir&&(m=_scriptDir);0!==m.indexOf("blob:")?m=m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):m="";if("object"!=typeof window&&
"function"!=typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};h&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});u=(a,b,d)=>{var e=new XMLHttpRequest;e.open("GET",a,
!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)}}else throw Error("environment detection error");var y=c.print||console.log.bind(console),x=c.printErr||console.warn.bind(console);Object.assign(c,ca);ca=null;Object.getOwnPropertyDescriptor(c,"fetchSettings")&&f("`Module.fetchSettings` was supplied but `fetchSettings` not included in INCOMING_MODULE_JS_API");C("arguments","arguments_");c.thisProgram&&(da=c.thisProgram);
C("thisProgram","thisProgram");c.quit&&(ea=c.quit);C("quit","quit_");assert("undefined"==typeof c.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof c.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof c.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"==typeof c.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof c.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"==typeof c.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");assert("undefined"==typeof c.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"==typeof c.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");
assert("undefined"==typeof c.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");C("read","read_");C("readAsync","readAsync");C("readBinary","readBinary");C("setWindowTitle","setWindowTitle");assert(!ia,"shell environment detected but not enabled at build time.  Add 'shell' to `-s ENVIRONMENT` to enable.");function pa(a){qa||(qa={});qa[a]||(qa[a]=1,x(a))}var qa;
function C(a,b){Object.getOwnPropertyDescriptor(c,a)||Object.defineProperty(c,a,{configurable:!0,get:function(){f("Module."+a+" has been replaced with plain "+b+" (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}})}function ra(a){return"'"+a+"' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)"}
function sa(a){Object.getOwnPropertyDescriptor(c,a)||Object.defineProperty(c,a,{configurable:!0,get:function(){f(ra(a))}})}function D(a){Object.getOwnPropertyDescriptor(c,a)||(c[a]=()=>f(ra(a)))}var ta;c.wasmBinary&&(ta=c.wasmBinary);C("wasmBinary","wasmBinary");var noExitRuntime=c.noExitRuntime||!0;C("noExitRuntime","noExitRuntime");"object"!=typeof WebAssembly&&f("no native wasm support detected");var ua,va=!1;function assert(a,b){a||f("Assertion failed"+(b?": "+b:""))}
function wa(a){var b=c["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function xa(a,b,d,e){var g={string:function(n){var r=0;if(null!==n&&void 0!==n&&0!==n){var w=(n.length<<2)+1;r=ya(w);za(n,r,w)}return r},array:function(n){var r=ya(n.length);assert(0<=n.length,"writeArrayToMemory array must have a length (should be an array or typed array)");F.set(n,r);return r}};a=wa(a);var k=[],l=0;assert("array"!==b,'Return type should not be "array".');if(e)for(var p=0;p<e.length;p++){var q=g[d[p]];q?(0===l&&(l=Aa()),k[p]=q(e[p])):k[p]=e[p]}d=a.apply(null,k);return d=function(n){0!==
l&&Ba(l);return"string"===b?G(n):"boolean"===b?!!n:n}(d)}var Ca="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,d){var e=b+d;for(d=b;a[d]&&!(d>=e);)++d;if(16<d-b&&a.subarray&&Ca)return Ca.decode(a.subarray(b,d));for(e="";b<d;){var g=a[b++];if(g&128){var k=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|k);else{var l=a[b++]&63;224==(g&240)?g=(g&15)<<12|k<<6|l:(240!=(g&248)&&pa("Invalid UTF-8 leading byte 0x"+g.toString(16)+" encountered when deserializing a UTF-8 string in wasm memory to a JS string!"),g=(g&7)<<18|k<<12|l<<6|a[b++]&63);65536>g?e+=String.fromCharCode(g):(g-=65536,e+=
String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}function G(a){return a?H(I,a,void 0):""}
function Da(a,b,d,e){if(!(0<e))return 0;var g=d;e=d+e-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var p=a.charCodeAt(++k);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(d>=e)break;b[d++]=l}else{if(2047>=l){if(d+1>=e)break;b[d++]=192|l>>6}else{if(65535>=l){if(d+2>=e)break;b[d++]=224|l>>12}else{if(d+3>=e)break;1114111<l&&pa("Invalid Unicode code point 0x"+l.toString(16)+" encountered when serializing a JS string to a UTF-8 string in wasm memory! (Valid unicode code points should be in range 0-0x10FFFF).");
b[d++]=240|l>>18;b[d++]=128|l>>12&63}b[d++]=128|l>>6&63}b[d++]=128|l&63}}b[d]=0;return d-g}function za(a,b,d){assert("number"==typeof d,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");Da(a,I,b,d)}function Ea(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!=typeof TextDecoder&&new TextDecoder("utf-16le");
function Fa(a){var b=Ea(a)+1,d=Ga(b);d&&Da(a,F,d,b);return d}var Ha,F,I,Ia,J,Ja;function Ka(){var a=ua.buffer;Ha=a;c.HEAP8=F=new Int8Array(a);c.HEAP16=Ia=new Int16Array(a);c.HEAP32=J=new Int32Array(a);c.HEAPU8=I=new Uint8Array(a);c.HEAPU16=new Uint16Array(a);c.HEAPU32=Ja=new Uint32Array(a);c.HEAPF32=new Float32Array(a);c.HEAPF64=new Float64Array(a)}c.TOTAL_STACK&&assert(5242880===c.TOTAL_STACK,"the stack size can no longer be determined at runtime");var La=c.INITIAL_MEMORY||16777216;
C("INITIAL_MEMORY","INITIAL_MEMORY");assert(5242880<=La,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+La+"! (TOTAL_STACK=5242880)");assert("undefined"!=typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!=Int32Array.prototype.subarray&&void 0!=Int32Array.prototype.set,"JS engine does not provide full typed array support");assert(!c.wasmMemory,"Use of `wasmMemory` detected.  Use -s IMPORTED_MEMORY to define wasmMemory externally");assert(16777216==La,"Detected runtime INITIAL_MEMORY setting.  Use -s IMPORTED_MEMORY to define wasmMemory dynamically");
var Ma;function Na(){var a=Oa();assert(0==(a&3));J[a+4>>2]=34821223;J[a+8>>2]=2310721022;J[0]=1668509029}function K(){if(!va){var a=Oa(),b=Ja[a+4>>2];a=Ja[a+8>>2];34821223==b&&2310721022==a||f("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+a.toString(16)+" 0x"+b.toString(16));1668509029!==J[0]&&f("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var Pa=new Int16Array(1),Qa=new Int8Array(Pa.buffer);
Pa[0]=25459;if(115!==Qa[0]||99!==Qa[1])throw"Runtime error: expected the system to be little-endian! (Run with -s SUPPORT_BIG_ENDIAN=1 to bypass)";var Ra=[],Sa=[],Ta=[],Ua=[],Va=!1,Wa=!1,oa=0;function Xa(){var a=c.preRun.shift();Ra.unshift(a)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var L=0,M=null,Ya=null,O={};function Za(a){for(var b=a;;){if(!O[a])return a;a=b+Math.random()}}
function $a(a){L++;c.monitorRunDependencies&&c.monitorRunDependencies(L);a?(assert(!O[a]),O[a]=1,null===M&&"undefined"!=typeof setInterval&&(M=setInterval(function(){if(va)clearInterval(M),M=null;else{var b=!1,d;for(d in O)b||(b=!0,x("still waiting on run dependencies:")),x("dependency: "+d);b&&x("(end of list)")}},1E4))):x("warning: run dependency added without ID")}
function ab(a){L--;c.monitorRunDependencies&&c.monitorRunDependencies(L);a?(assert(O[a]),delete O[a]):x("warning: run dependency removed without ID");0==L&&(null!==M&&(clearInterval(M),M=null),Ya&&(a=Ya,Ya=null,a()))}c.preloadedImages={};c.preloadedAudios={};function f(a){if(c.onAbort)c.onAbort(a);a="Aborted("+a+")";x(a);va=!0;a=new WebAssembly.RuntimeError(a);ba(a);throw a;}function bb(){return P.startsWith("data:application/octet-stream;base64,")}
function Q(a){return function(){var b=c.asm;assert(Va,"native function `"+a+"` called before runtime initialization");assert(!Wa,"native function `"+a+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");b[a]||assert(b[a],"exported native function `"+a+"` not found");return b[a].apply(null,arguments)}}var P;P="audio.wasm";if(!bb()){var cb=P;P=c.locateFile?c.locateFile(cb,m):m+cb}
function db(){var a=P;try{if(a==P&&ta)return new Uint8Array(ta);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){f(b)}}
function eb(){if(!ta&&(fa||h)){if("function"==typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return db()});if(u)return new Promise(function(a,b){u(P,function(d){a(new Uint8Array(d))},b)})}return Promise.resolve().then(function(){return db()})}var R,S;
function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(c);else{var d=b.Jb;"number"==typeof d?void 0===b.la?gb(d)():gb(d)(b.la):d(void 0===b.la?null:b.la)}}}function hb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){pa("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return b===b?b:b+" ["+b+"]"})}var ib=[];
function gb(a){var b=ib[a];b||(a>=ib.length&&(ib.length=a+1),ib[a]=b=Ma.get(a));assert(Ma.get(a)==b,"JavaScript-side Wasm function table mirror is out of date!");return b}function jb(a,b){for(var d=0,e=a.length-1;0<=e;e--){var g=a[e];"."===g?a.splice(e,1):".."===g?(a.splice(e,1),d++):d&&(a.splice(e,1),d--)}if(b)for(;d;d--)a.unshift("..");return a}
function kb(a){var b="/"===a.charAt(0),d="/"===a.substr(-1);(a=jb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&d&&(a+="/");return(b?"/":"")+a}function lb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function T(a){if("/"===a)return"/";a=kb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function U(a,b){return kb(a+"/"+b)}
function mb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(d){}return function(){f("no cryptographic support found for randomDevice. consider polyfilling it if you want to use something insecure like Math.random(), e.g. put this in a --pre-js: var crypto = { getRandomValues: function(array) { for (var i = 0; i < array.length; i++) array[i] = (Math.random()*256)|0 } };")}}
function V(){for(var a="",b=!1,d=arguments.length-1;-1<=d&&!b;d--){b=0<=d?arguments[d]:W.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=jb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function nb(a,b){function d(l){for(var p=0;p<l.length&&""===l[p];p++);for(var q=l.length-1;0<=q&&""===l[q];q--);return p>q?[]:l.slice(p,q-p+1)}a=V(a).substr(1);b=V(b).substr(1);a=d(a.split("/"));b=d(b.split("/"));for(var e=Math.min(a.length,b.length),g=e,k=0;k<e;k++)if(a[k]!==b[k]){g=k;break}e=[];for(k=g;k<a.length;k++)e.push("..");e=e.concat(b.slice(g));return e.join("/")}var ob=[];function pb(a,b){ob[a]={input:[],output:[],S:b};W.za(a,qb)}
var qb={open:function(a){var b=ob[a.node.rdev];if(!b)throw new W.g(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.S.flush(a.tty)},flush:function(a){a.tty.S.flush(a.tty)},read:function(a,b,d,e){if(!a.tty||!a.tty.S.Oa)throw new W.g(60);for(var g=0,k=0;k<e;k++){try{var l=a.tty.S.Oa(a.tty)}catch(p){throw new W.g(29);}if(void 0===l&&0===g)throw new W.g(6);if(null===l||void 0===l)break;g++;b[d+k]=l}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,d,e){if(!a.tty||!a.tty.S.wa)throw new W.g(60);
try{for(var g=0;g<e;g++)a.tty.S.wa(a.tty,b[d+g])}catch(k){throw new W.g(29);}e&&(a.node.timestamp=Date.now());return g}},sb={Oa:function(a){if(!a.input.length){var b=null;if(ha){var d=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,d,0,256,-1)}catch(g){if(g.toString().includes("EOF"))e=0;else throw g;}0<e?b=d.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=rb(b)}return a.input.shift()},wa:function(a,b){null===b||10===b?(y(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(y(H(a.output,0)),a.output=[])}},tb={wa:function(a,b){null===b||10===b?(x(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(x(H(a.output,0)),a.output=[])}},X={H:null,s:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,
b,d,e){if(W.pb(d)||W.isFIFO(d))throw new W.g(63);X.H||(X.H={dir:{node:{D:X.h.D,v:X.h.v,lookup:X.h.lookup,I:X.h.I,rename:X.h.rename,unlink:X.h.unlink,rmdir:X.h.rmdir,readdir:X.h.readdir,symlink:X.h.symlink},stream:{A:X.j.A}},file:{node:{D:X.h.D,v:X.h.v},stream:{A:X.j.A,read:X.j.read,write:X.j.write,U:X.j.U,Y:X.j.Y,aa:X.j.aa}},link:{node:{D:X.h.D,v:X.h.v,readlink:X.h.readlink},stream:{}},Da:{node:{D:X.h.D,v:X.h.v},stream:W.bb}});d=W.createNode(a,b,d,e);W.u(d.mode)?(d.h=X.H.dir.node,d.j=X.H.dir.stream,
d.i={}):W.isFile(d.mode)?(d.h=X.H.file.node,d.j=X.H.file.stream,d.m=0,d.i=null):W.M(d.mode)?(d.h=X.H.link.node,d.j=X.H.link.stream):W.W(d.mode)&&(d.h=X.H.Da.node,d.j=X.H.Da.stream);d.timestamp=Date.now();a&&(a.i[b]=d,a.timestamp=d.timestamp);return d},Kb:function(a){return a.i?a.i.subarray?a.i.subarray(0,a.m):new Uint8Array(a.i):new Uint8Array(0)},Ka:function(a,b){var d=a.i?a.i.length:0;d>=b||(b=Math.max(b,d*(1048576>d?2:1.125)>>>0),0!=d&&(b=Math.max(b,256)),d=a.i,a.i=new Uint8Array(b),0<a.m&&a.i.set(d.subarray(0,
a.m),0))},zb:function(a,b){if(a.m!=b)if(0==b)a.i=null,a.m=0;else{var d=a.i;a.i=new Uint8Array(b);d&&a.i.set(d.subarray(0,Math.min(b,a.m)));a.m=b}},h:{D:function(a){var b={};b.dev=W.W(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;W.u(a.mode)?b.size=4096:W.isFile(a.mode)?b.size=a.m:W.M(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Za=4096;b.blocks=Math.ceil(b.size/b.Za);return b},v:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.zb(a,b.size)},lookup:function(){throw W.oa[44];},I:function(a,b,d,e){return X.createNode(a,b,d,e)},rename:function(a,b,d){if(W.u(a.mode)){try{var e=W.F(b,d)}catch(k){}if(e)for(var g in e.i)throw new W.g(55);}delete a.parent.i[a.name];a.parent.timestamp=Date.now();a.name=d;b.i[d]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.i[b];a.timestamp=Date.now()},rmdir:function(a,
b){var d=W.F(a,b),e;for(e in d.i)throw new W.g(55);delete a.i[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],d;for(d in a.i)a.i.hasOwnProperty(d)&&b.push(d);return b},symlink:function(a,b,d){a=X.createNode(a,b,41471,0);a.link=d;return a},readlink:function(a){if(!W.M(a.mode))throw new W.g(28);return a.link}},j:{read:function(a,b,d,e,g){var k=a.node.i;if(g>=a.node.m)return 0;a=Math.min(a.node.m-g,e);assert(0<=a);if(8<a&&k.subarray)b.set(k.subarray(g,g+a),d);else for(e=0;e<a;e++)b[d+
e]=k[g+e];return a},write:function(a,b,d,e,g,k){assert(!(b instanceof ArrayBuffer));b.buffer===F.buffer&&(k=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.i||a.i.subarray)){if(k)return assert(0===g,"canOwn must imply no weird position inside the file"),a.i=b.subarray(d,d+e),a.m=e;if(0===a.m&&0===g)return a.i=b.slice(d,d+e),a.m=e;if(g+e<=a.m)return a.i.set(b.subarray(d,d+e),g),e}X.Ka(a,g+e);if(a.i.subarray&&b.subarray)a.i.set(b.subarray(d,d+e),g);else for(k=0;k<e;k++)a.i[g+k]=
b[d+k];a.m=Math.max(a.m,g+e);return e},A:function(a,b,d){1===d?b+=a.position:2===d&&W.isFile(a.node.mode)&&(b+=a.node.m);if(0>b)throw new W.g(28);return b},U:function(a,b,d){X.Ka(a.node,b+d);a.node.m=Math.max(a.node.m,b+d)},Y:function(a,b,d,e,g,k){if(0!==b)throw new W.g(28);if(!W.isFile(a.node.mode))throw new W.g(43);a=a.node.i;if(k&2||a.buffer!==Ha){if(0<e||e+d<a.length)a.subarray?a=a.subarray(e,e+d):a=Array.prototype.slice.call(a,e,e+d);e=!0;assert(65536,"alignment argument is required");d=65536*
Math.ceil(d/65536);(k=ub(65536,d))?(I.fill(0,k,k+d),d=k):d=0;if(!d)throw new W.g(48);F.set(a,d)}else e=!1,d=a.byteOffset;return{Tb:d,Eb:e}},aa:function(a,b,d,e,g){if(!W.isFile(a.node.mode))throw new W.g(43);if(g&2)return 0;X.j.write(a,b,0,e,d,!1);return 0}}};function vb(a,b,d){var e=Za("al "+a);u(a,function(g){assert(g,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(g));e&&ab(e)},function(){if(d)d();else throw'Loading data file "'+a+'" failed.';});e&&$a(e)}
var wb={0:"Success",1:"Arg list too long",2:"Permission denied",3:"Address already in use",4:"Address not available",5:"Address family not supported by protocol family",6:"No more processes",7:"Socket already connected",8:"Bad file number",9:"Trying to read unreadable message",10:"Mount device busy",11:"Operation canceled",12:"No children",13:"Connection aborted",14:"Connection refused",15:"Connection reset by peer",16:"File locking deadlock error",17:"Destination address required",18:"Math arg out of domain of func",
19:"Quota exceeded",20:"File exists",21:"Bad address",22:"File too large",23:"Host is unreachable",24:"Identifier removed",25:"Illegal byte sequence",26:"Connection already in progress",27:"Interrupted system call",28:"Invalid argument",29:"I/O error",30:"Socket is already connected",31:"Is a directory",32:"Too many symbolic links",33:"Too many open files",34:"Too many links",35:"Message too long",36:"Multihop attempted",37:"File or path name too long",38:"Network interface is not configured",39:"Connection reset by network",
40:"Network is unreachable",41:"Too many open files in system",42:"No buffer space available",43:"No such device",44:"No such file or directory",45:"Exec format error",46:"No record locks available",47:"The link has been severed",48:"Not enough core",49:"No message of desired type",50:"Protocol not available",51:"No space left on device",52:"Function not implemented",53:"Socket is not connected",54:"Not a directory",55:"Directory not empty",56:"State not recoverable",57:"Socket operation on non-socket",
59:"Not a typewriter",60:"No such device or address",61:"Value too large for defined data type",62:"Previous owner died",63:"Not super-user",64:"Broken pipe",65:"Protocol error",66:"Unknown protocol",67:"Protocol wrong type for socket",68:"Math result not representable",69:"Read only file system",70:"Illegal seek",71:"No such process",72:"Stale file handle",73:"Connection timed out",74:"Text file busy",75:"Cross-device link",100:"Device not a stream",101:"Bad font file fmt",102:"Invalid slot",103:"Invalid request code",
104:"No anode",105:"Block device required",106:"Channel number out of range",107:"Level 3 halted",108:"Level 3 reset",109:"Link number out of range",110:"Protocol driver not attached",111:"No CSI structure available",112:"Level 2 halted",113:"Invalid exchange",114:"Invalid request descriptor",115:"Exchange full",116:"No data (for no delay io)",117:"Timer expired",118:"Out of streams resources",119:"Machine is not on the network",120:"Package not installed",121:"The object is remote",122:"Advertise error",
123:"Srmount error",124:"Communication error on send",125:"Cross mount point (not really error)",126:"Given log. name not unique",127:"f.d. invalid for this operation",128:"Remote address changed",129:"Can   access a needed shared lib",130:"Accessing a corrupted shared lib",131:".lib section in a.out corrupted",132:"Attempting to link in too many libs",133:"Attempting to exec a shared library",135:"Streams pipe error",136:"Too many users",137:"Socket type not supported",138:"Not supported",139:"Protocol family not supported",
140:"Can't send after socket shutdown",141:"Too many references",142:"Host is down",148:"No medium (in tape drive)",156:"Level 2 not synchronized"},xb={},W={root:null,$:[],Ia:{},streams:[],ub:1,G:null,Ha:"/",ga:!1,Sa:!0,g:null,oa:{},lb:null,ba:0,l:(a,b={})=>{a=V(W.cwd(),a);if(!a)return{path:"",node:null};var d={na:!0,ya:0},e;for(e in d)void 0===b[e]&&(b[e]=d[e]);if(8<b.ya)throw new W.g(32);a=jb(a.split("/").filter(l=>!!l),!1);var g=W.root;d="/";for(e=0;e<a.length;e++){var k=e===a.length-1;if(k&&b.parent)break;
g=W.F(g,a[e]);d=U(d,a[e]);W.N(g)&&(!k||k&&b.na)&&(g=g.Z.root);if(!k||b.B)for(k=0;W.M(g.mode);)if(g=W.readlink(d),d=V(lb(d),g),g=W.l(d,{ya:b.ya}).node,40<k++)throw new W.g(32);}return{path:d,node:g}},J:a=>{for(var b;;){if(W.ha(a))return a=a.s.Ta,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},qa:(a,b)=>{for(var d=0,e=0;e<b.length;e++)d=(d<<5)-d+b.charCodeAt(e)|0;return(a+d>>>0)%W.G.length},Qa:a=>{var b=W.qa(a.parent.id,a.name);a.P=W.G[b];W.G[b]=a},Ra:a=>{var b=W.qa(a.parent.id,
a.name);if(W.G[b]===a)W.G[b]=a.P;else for(b=W.G[b];b;){if(b.P===a){b.P=a.P;break}b=b.P}},F:(a,b)=>{var d=W.rb(a);if(d)throw new W.g(d,a);for(d=W.G[W.qa(a.id,b)];d;d=d.P){var e=d.name;if(d.parent.id===a.id&&e===b)return d}return W.lookup(a,b)},createNode:(a,b,d,e)=>{assert("object"==typeof a);a=new W.Va(a,b,d,e);W.Qa(a);return a},ma:a=>{W.Ra(a)},ha:a=>a===a.parent,N:a=>!!a.Z,isFile:a=>32768===(a&61440),u:a=>16384===(a&61440),M:a=>40960===(a&61440),W:a=>8192===(a&61440),pb:a=>24576===(a&61440),isFIFO:a=>
4096===(a&61440),isSocket:a=>49152===(a&49152),mb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},tb:a=>{var b=W.mb[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},La:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},K:(a,b)=>{if(W.Sa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},rb:a=>{var b=W.K(a,"x");return b?b:a.h.lookup?0:2},va:(a,b)=>{try{return W.F(a,b),20}catch(d){}return W.K(a,
"wx")},ia:(a,b,d)=>{try{var e=W.F(a,b)}catch(g){return g.o}if(a=W.K(a,"wx"))return a;if(d){if(!W.u(e.mode))return 54;if(W.ha(e)||W.J(e)===W.cwd())return 10}else if(W.u(e.mode))return 31;return 0},sb:(a,b)=>a?W.M(a.mode)?32:W.u(a.mode)&&("r"!==W.La(b)||b&512)?31:W.K(a,W.La(b)):44,Wa:4096,vb:(a=0,b=W.Wa)=>{for(;a<=b;a++)if(!W.streams[a])return a;throw new W.g(33);},R:a=>W.streams[a],jb:(a,b,d)=>{W.ka||(W.ka=function(){},W.ka.prototype={object:{get:function(){return this.node},set:function(e){this.node=
e}}});a=Object.assign(new W.ka,a);b=W.vb(b,d);a.fd=b;return W.streams[b]=a},cb:a=>{W.streams[a]=null},bb:{open:a=>{a.j=W.nb(a.node.rdev).j;a.j.open&&a.j.open(a)},A:()=>{throw new W.g(70);}},ua:a=>a>>8,Ob:a=>a&255,O:(a,b)=>a<<8|b,za:(a,b)=>{W.Ia[a]={j:b}},nb:a=>W.Ia[a],Na:a=>{var b=[];for(a=[a];a.length;){var d=a.pop();b.push(d);a.push.apply(a,d.$)}return b},Ua:(a,b)=>{function d(l){assert(0<W.ba);W.ba--;return b(l)}function e(l){if(l){if(!e.kb)return e.kb=!0,d(l)}else++k>=g.length&&d(null)}"function"==
typeof a&&(b=a,a=!1);W.ba++;1<W.ba&&x("warning: "+W.ba+" FS.syncfs operations in flight at once, probably just doing extra work");var g=W.Na(W.root.s),k=0;g.forEach(l=>{if(!l.type.Ua)return e(null);l.type.Ua(l,a,e)})},s:(a,b,d)=>{if("string"==typeof a)throw a;var e="/"===d,g=!d;if(e&&W.root)throw new W.g(10);if(!e&&!g){var k=W.l(d,{na:!1});d=k.path;k=k.node;if(W.N(k))throw new W.g(10);if(!W.u(k.mode))throw new W.g(54);}b={type:a,Sb:b,Ta:d,$:[]};a=a.s(b);a.s=b;b.root=a;e?W.root=a:k&&(k.Z=b,k.s&&k.s.$.push(b));
return a},Xb:a=>{a=W.l(a,{na:!1});if(!W.N(a.node))throw new W.g(28);a=a.node;var b=a.Z,d=W.Na(b);Object.keys(W.G).forEach(e=>{for(e=W.G[e];e;){var g=e.P;d.includes(e.s)&&W.ma(e);e=g}});a.Z=null;b=a.s.$.indexOf(b);assert(-1!==b);a.s.$.splice(b,1)},lookup:(a,b)=>a.h.lookup(a,b),I:(a,b,d)=>{var e=W.l(a,{parent:!0}).node;a=T(a);if(!a||"."===a||".."===a)throw new W.g(28);var g=W.va(e,a);if(g)throw new W.g(g);if(!e.h.I)throw new W.g(63);return e.h.I(e,a,b,d)},create:(a,b)=>W.I(a,(void 0!==b?b:438)&4095|
32768,0),mkdir:(a,b)=>W.I(a,(void 0!==b?b:511)&1023|16384,0),Pb:(a,b)=>{a=a.split("/");for(var d="",e=0;e<a.length;++e)if(a[e]){d+="/"+a[e];try{W.mkdir(d,b)}catch(g){if(20!=g.o)throw g;}}},ja:(a,b,d)=>{"undefined"==typeof d&&(d=b,b=438);return W.I(a,b|8192,d)},symlink:(a,b)=>{if(!V(a))throw new W.g(44);var d=W.l(b,{parent:!0}).node;if(!d)throw new W.g(44);b=T(b);var e=W.va(d,b);if(e)throw new W.g(e);if(!d.h.symlink)throw new W.g(63);return d.h.symlink(d,b,a)},rename:(a,b)=>{var d=lb(a),e=lb(b),g=
T(a),k=T(b);var l=W.l(a,{parent:!0});var p=l.node;l=W.l(b,{parent:!0});l=l.node;if(!p||!l)throw new W.g(44);if(p.s!==l.s)throw new W.g(75);var q=W.F(p,g);a=nb(a,e);if("."!==a.charAt(0))throw new W.g(28);a=nb(b,d);if("."!==a.charAt(0))throw new W.g(55);try{var n=W.F(l,k)}catch(r){}if(q!==n){b=W.u(q.mode);if(g=W.ia(p,g,b))throw new W.g(g);if(g=n?W.ia(l,k,b):W.va(l,k))throw new W.g(g);if(!p.h.rename)throw new W.g(63);if(W.N(q)||n&&W.N(n))throw new W.g(10);if(l!==p&&(g=W.K(p,"w")))throw new W.g(g);W.Ra(q);
try{p.h.rename(q,l,k)}catch(r){throw r;}finally{W.Qa(q)}}},rmdir:a=>{var b=W.l(a,{parent:!0}).node;a=T(a);var d=W.F(b,a),e=W.ia(b,a,!0);if(e)throw new W.g(e);if(!b.h.rmdir)throw new W.g(63);if(W.N(d))throw new W.g(10);b.h.rmdir(b,a);W.ma(d)},readdir:a=>{a=W.l(a,{B:!0}).node;if(!a.h.readdir)throw new W.g(54);return a.h.readdir(a)},unlink:a=>{var b=W.l(a,{parent:!0}).node;if(!b)throw new W.g(44);a=T(a);var d=W.F(b,a),e=W.ia(b,a,!1);if(e)throw new W.g(e);if(!b.h.unlink)throw new W.g(63);if(W.N(d))throw new W.g(10);
b.h.unlink(b,a);W.ma(d)},readlink:a=>{a=W.l(a).node;if(!a)throw new W.g(44);if(!a.h.readlink)throw new W.g(28);return V(W.J(a.parent),a.h.readlink(a))},stat:(a,b)=>{a=W.l(a,{B:!b}).node;if(!a)throw new W.g(44);if(!a.h.D)throw new W.g(63);return a.h.D(a)},lstat:a=>W.stat(a,!0),chmod:(a,b,d)=>{a="string"==typeof a?W.l(a,{B:!d}).node:a;if(!a.h.v)throw new W.g(63);a.h.v(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{W.chmod(a,b,!0)},fchmod:(a,b)=>{a=W.R(a);if(!a)throw new W.g(8);W.chmod(a.node,
b)},chown:(a,b,d,e)=>{a="string"==typeof a?W.l(a,{B:!e}).node:a;if(!a.h.v)throw new W.g(63);a.h.v(a,{timestamp:Date.now()})},lchown:(a,b,d)=>{W.chown(a,b,d,!0)},fchown:(a,b,d)=>{a=W.R(a);if(!a)throw new W.g(8);W.chown(a.node,b,d)},truncate:(a,b)=>{if(0>b)throw new W.g(28);a="string"==typeof a?W.l(a,{B:!0}).node:a;if(!a.h.v)throw new W.g(63);if(W.u(a.mode))throw new W.g(31);if(!W.isFile(a.mode))throw new W.g(28);var d=W.K(a,"w");if(d)throw new W.g(d);a.h.v(a,{size:b,timestamp:Date.now()})},Ib:(a,b)=>
{a=W.R(a);if(!a)throw new W.g(8);if(0===(a.flags&2097155))throw new W.g(28);W.truncate(a.node,b)},Yb:(a,b,d)=>{a=W.l(a,{B:!0}).node;a.h.v(a,{timestamp:Math.max(b,d)})},open:(a,b,d,e,g)=>{if(""===a)throw new W.g(44);b="string"==typeof b?W.tb(b):b;d=b&64?("undefined"==typeof d?438:d)&4095|32768:0;if("object"==typeof a)var k=a;else{a=kb(a);try{k=W.l(a,{B:!(b&131072)}).node}catch(p){}}var l=!1;if(b&64)if(k){if(b&128)throw new W.g(20);}else k=W.I(a,d,0),l=!0;if(!k)throw new W.g(44);W.W(k.mode)&&(b&=-513);
if(b&65536&&!W.u(k.mode))throw new W.g(54);if(!l&&(d=W.sb(k,b)))throw new W.g(d);b&512&&W.truncate(k,0);b&=-131713;e=W.jb({node:k,path:W.J(k),flags:b,seekable:!0,position:0,j:k.j,Cb:[],error:!1},e,g);e.j.open&&e.j.open(e);!c.logReadFiles||b&1||(W.xa||(W.xa={}),a in W.xa||(W.xa[a]=1));return e},close:a=>{if(W.X(a))throw new W.g(8);a.L&&(a.L=null);try{a.j.close&&a.j.close(a)}catch(b){throw b;}finally{W.cb(a.fd)}a.fd=null},X:a=>null===a.fd,A:(a,b,d)=>{if(W.X(a))throw new W.g(8);if(!a.seekable||!a.j.A)throw new W.g(70);
if(0!=d&&1!=d&&2!=d)throw new W.g(28);a.position=a.j.A(a,b,d);a.Cb=[];return a.position},read:(a,b,d,e,g)=>{if(0>e||0>g)throw new W.g(28);if(W.X(a))throw new W.g(8);if(1===(a.flags&2097155))throw new W.g(8);if(W.u(a.node.mode))throw new W.g(31);if(!a.j.read)throw new W.g(28);var k="undefined"!=typeof g;if(!k)g=a.position;else if(!a.seekable)throw new W.g(70);b=a.j.read(a,b,d,e,g);k||(a.position+=b);return b},write:(a,b,d,e,g,k)=>{if(0>e||0>g)throw new W.g(28);if(W.X(a))throw new W.g(8);if(0===(a.flags&
2097155))throw new W.g(8);if(W.u(a.node.mode))throw new W.g(31);if(!a.j.write)throw new W.g(28);a.seekable&&a.flags&1024&&W.A(a,0,2);var l="undefined"!=typeof g;if(!l)g=a.position;else if(!a.seekable)throw new W.g(70);b=a.j.write(a,b,d,e,g,k);l||(a.position+=b);return b},U:(a,b,d)=>{if(W.X(a))throw new W.g(8);if(0>b||0>=d)throw new W.g(28);if(0===(a.flags&2097155))throw new W.g(8);if(!W.isFile(a.node.mode)&&!W.u(a.node.mode))throw new W.g(43);if(!a.j.U)throw new W.g(138);a.j.U(a,b,d)},Y:(a,b,d,e,
g,k)=>{if(0!==(g&2)&&0===(k&2)&&2!==(a.flags&2097155))throw new W.g(2);if(1===(a.flags&2097155))throw new W.g(2);if(!a.j.Y)throw new W.g(43);return a.j.Y(a,b,d,e,g,k)},aa:(a,b,d,e,g)=>a&&a.j.aa?a.j.aa(a,b,d,e,g):0,Rb:()=>0,ra:(a,b,d)=>{if(!a.j.ra)throw new W.g(59);return a.j.ra(a,b,d)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var d,e=W.open(a,b.flags);a=W.stat(a).size;
var g=new Uint8Array(a);W.read(e,g,0,a,0);"utf8"===b.encoding?d=H(g,0):"binary"===b.encoding&&(d=g);W.close(e);return d},writeFile:(a,b,d={})=>{d.flags=d.flags||577;a=W.open(a,d.flags,d.mode);if("string"==typeof b){var e=new Uint8Array(Ea(b)+1);b=Da(b,e,0,e.length);W.write(a,e,0,b,void 0,d.ab)}else if(ArrayBuffer.isView(b))W.write(a,b,0,b.byteLength,void 0,d.ab);else throw Error("Unsupported data type");W.close(a)},cwd:()=>W.Ha,chdir:a=>{a=W.l(a,{B:!0});if(null===a.node)throw new W.g(44);if(!W.u(a.node.mode))throw new W.g(54);
var b=W.K(a.node,"x");if(b)throw new W.g(b);W.Ha=a.path},fb:()=>{W.mkdir("/tmp");W.mkdir("/home");W.mkdir("/home/web_user")},eb:()=>{W.mkdir("/dev");W.za(W.O(1,3),{read:()=>0,write:(b,d,e,g)=>g});W.ja("/dev/null",W.O(1,3));pb(W.O(5,0),sb);pb(W.O(6,0),tb);W.ja("/dev/tty",W.O(5,0));W.ja("/dev/tty1",W.O(6,0));var a=mb();W.C("/dev","random",a);W.C("/dev","urandom",a);W.mkdir("/dev/shm");W.mkdir("/dev/shm/tmp")},hb:()=>{W.mkdir("/proc");var a=W.mkdir("/proc/self");W.mkdir("/proc/self/fd");W.s({s:()=>{var b=
W.createNode(a,"fd",16895,73);b.h={lookup:(d,e)=>{var g=W.R(+e);if(!g)throw new W.g(8);d={parent:null,s:{Ta:"fake"},h:{readlink:()=>g.path}};return d.parent=d}};return b}},{},"/proc/self/fd")},ib:()=>{c.stdin?W.C("/dev","stdin",c.stdin):W.symlink("/dev/tty","/dev/stdin");c.stdout?W.C("/dev","stdout",null,c.stdout):W.symlink("/dev/tty","/dev/stdout");c.stderr?W.C("/dev","stderr",null,c.stderr):W.symlink("/dev/tty1","/dev/stderr");var a=W.open("/dev/stdin",0),b=W.open("/dev/stdout",1),d=W.open("/dev/stderr",
1);assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");assert(1===b.fd,"invalid handle for stdout ("+b.fd+")");assert(2===d.fd,"invalid handle for stderr ("+d.fd+")")},Ja:()=>{W.g||(W.g=function(a,b){this.node=b;this.Ab=function(d){this.o=d;for(var e in xb)if(xb[e]===d){this.code=e;break}};this.Ab(a);this.message=wb[a];this.stack&&(Object.defineProperty(this,"stack",{value:Error().stack,writable:!0}),this.stack=hb(this.stack))},W.g.prototype=Error(),W.g.prototype.constructor=W.g,[44].forEach(a=>
{W.oa[a]=new W.g(a);W.oa[a].stack="<generic error, no stack>"}))},Bb:()=>{W.Ja();W.G=Array(4096);W.s(X,{},"/");W.fb();W.eb();W.hb();W.lb={MEMFS:X}},V:(a,b,d)=>{assert(!W.V.ga,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");W.V.ga=!0;W.Ja();c.stdin=a||c.stdin;c.stdout=b||c.stdout;c.stderr=d||c.stderr;W.ib()},Ub:()=>{W.V.ga=!1;yb();for(var a=0;a<W.streams.length;a++){var b=
W.streams[a];b&&W.close(b)}},pa:(a,b)=>{var d=0;a&&(d|=365);b&&(d|=146);return d},Hb:(a,b)=>{a=W.da(a,b);return a.exists?a.object:null},da:(a,b)=>{try{var d=W.l(a,{B:!b});a=d.path}catch(g){}var e={ha:!1,exists:!1,error:0,name:null,path:null,object:null,wb:!1,yb:null,xb:null};try{d=W.l(a,{parent:!0}),e.wb=!0,e.yb=d.path,e.xb=d.node,e.name=T(a),d=W.l(a,{B:!b}),e.exists=!0,e.path=d.path,e.object=d.node,e.name=d.node.name,e.ha="/"===d.path}catch(g){e.error=g.o}return e},Fa:(a,b)=>{a="string"==typeof a?
a:W.J(a);for(b=b.split("/").reverse();b.length;){var d=b.pop();if(d){var e=U(a,d);try{W.mkdir(e)}catch(g){}a=e}}return e},gb:(a,b,d,e,g)=>{a=U("string"==typeof a?a:W.J(a),b);return W.create(a,W.pa(e,g))},ea:(a,b,d,e,g,k)=>{var l=b;a&&(a="string"==typeof a?a:W.J(a),l=b?U(a,b):a);a=W.pa(e,g);l=W.create(l,a);if(d){if("string"==typeof d){b=Array(d.length);e=0;for(g=d.length;e<g;++e)b[e]=d.charCodeAt(e);d=b}W.chmod(l,a|146);b=W.open(l,577);W.write(b,d,0,d.length,0,k);W.close(b);W.chmod(l,a)}return l},
C:(a,b,d,e)=>{a=U("string"==typeof a?a:W.J(a),b);b=W.pa(!!d,!!e);W.C.ua||(W.C.ua=64);var g=W.O(W.C.ua++,0);W.za(g,{open:k=>{k.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(k,l,p,q)=>{for(var n=0,r=0;r<q;r++){try{var w=d()}catch(A){throw new W.g(29);}if(void 0===w&&0===n)throw new W.g(6);if(null===w||void 0===w)break;n++;l[p+r]=w}n&&(k.node.timestamp=Date.now());return n},write:(k,l,p,q)=>{for(var n=0;n<q;n++)try{e(l[p+n])}catch(r){throw new W.g(29);}q&&(k.node.timestamp=Date.now());
return n}});return W.ja(a,b,g)},Ma:a=>{if(a.sa||a.qb||a.link||a.i)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(t)try{a.i=rb(t(a.url)),a.m=a.i.length}catch(b){throw new W.g(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Ea:(a,b,d,e,g)=>{function k(){this.ta=!1;this.fa=
[]}k.prototype.get=function(n){if(!(n>this.length-1||0>n)){var r=n%this.chunkSize;return this.Pa(n/this.chunkSize|0)[r]}};k.prototype.ob=function(n){this.Pa=n};k.prototype.Ca=function(){var n=new XMLHttpRequest;n.open("HEAD",d,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+d+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),w,A=(w=n.getResponseHeader("Accept-Ranges"))&&"bytes"===w;n=(w=n.getResponseHeader("Content-Encoding"))&&
"gzip"===w;var B=1048576;A||(B=r);var z=this;z.ob(N=>{var la=N*B,Z=(N+1)*B-1;Z=Math.min(Z,r-1);if("undefined"==typeof z.fa[N]){var Qb=z.fa;if(la>Z)throw Error("invalid range ("+la+", "+Z+") or no bytes requested!");if(Z>r-1)throw Error("only "+r+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",d,!1);r!==B&&E.setRequestHeader("Range","bytes="+la+"-"+Z);E.responseType="arraybuffer";E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);
if(!(200<=E.status&&300>E.status||304===E.status))throw Error("Couldn't load "+d+". Status: "+E.status);la=void 0!==E.response?new Uint8Array(E.response||[]):rb(E.responseText||"");Qb[N]=la}if("undefined"==typeof z.fa[N])throw Error("doXHR failed!");return z.fa[N]});if(n||!r)B=r=1,B=r=this.Pa(0).length,y("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ya=r;this.Xa=B;this.ta=!0};if("undefined"!=typeof XMLHttpRequest){if(!h)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new k;Object.defineProperties(l,{length:{get:function(){this.ta||this.Ca();return this.Ya}},chunkSize:{get:function(){this.ta||this.Ca();return this.Xa}}});l={sa:!1,i:l}}else l={sa:!1,url:d};var p=W.gb(a,b,l,e,g);l.i?p.i=l.i:l.url&&(p.i=null,p.url=l.url);Object.defineProperties(p,{m:{get:function(){return this.i.length}}});var q={};Object.keys(p.j).forEach(n=>{var r=p.j[n];q[n]=function(){W.Ma(p);return r.apply(null,arguments)}});q.read=(n,r,w,A,B)=>{W.Ma(p);n=n.node.i;if(B>=n.length)return 0;
A=Math.min(n.length-B,A);assert(0<=A);if(n.slice)for(var z=0;z<A;z++)r[w+z]=n[B+z];else for(z=0;z<A;z++)r[w+z]=n.get(B+z);return A};p.j=q;return p},Ga:(a,b,d,e,g,k,l,p,q,n)=>{function r(B){function z(N){n&&n();p||W.ea(a,b,N,e,g,q);k&&k();ab(A)}zb.Lb(B,w,z,()=>{l&&l();ab(A)})||z(B)}var w=b?V(U(a,b)):a,A=Za("cp "+w);$a(A);"string"==typeof d?vb(d,B=>r(B),l):r(d)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Aa:()=>"EM_FS_"+window.location.pathname,Ba:20,
T:"FILE_DATA",Vb:(a,b,d)=>{b=b||(()=>{});d=d||(()=>{});var e=W.indexedDB();try{var g=e.open(W.Aa(),W.Ba)}catch(k){return d(k)}g.onupgradeneeded=()=>{y("creating db");g.result.createObjectStore(W.T)};g.onsuccess=()=>{var k=g.result.transaction([W.T],"readwrite"),l=k.objectStore(W.T),p=0,q=0,n=a.length;a.forEach(r=>{r=l.put(W.da(r).object.i,r);r.onsuccess=()=>{p++;p+q==n&&(0==q?b():d())};r.onerror=()=>{q++;p+q==n&&(0==q?b():d())}});k.onerror=d};g.onerror=d},Nb:(a,b,d)=>{b=b||(()=>{});d=d||(()=>{});
var e=W.indexedDB();try{var g=e.open(W.Aa(),W.Ba)}catch(k){return d(k)}g.onupgradeneeded=d;g.onsuccess=()=>{var k=g.result;try{var l=k.transaction([W.T],"readonly")}catch(w){d(w);return}var p=l.objectStore(W.T),q=0,n=0,r=a.length;a.forEach(w=>{var A=p.get(w);A.onsuccess=()=>{W.da(w).exists&&W.unlink(w);W.ea(lb(w),T(w),A.result,!0,!0,!0);q++;q+n==r&&(0==n?b():d())};A.onerror=()=>{n++;q+n==r&&(0==n?b():d())}});l.onerror=d};g.onerror=d},Db:()=>{f("FS.absolutePath has been removed; use PATH_FS.resolve instead")},
Fb:()=>{f("FS.createFolder has been removed; use FS.mkdir instead")},Gb:()=>{f("FS.createLink has been removed; use FS.symlink instead")},Mb:()=>{f("FS.joinPath has been removed; use PATH.join instead")},Qb:()=>{f("FS.mmapAlloc has been replaced by the top level function mmapAlloc")},Wb:()=>{f("FS.standardizePath has been removed; use PATH.normalize instead")}};
function Ab(a,b,d){if("/"===b[0])return b;if(-100===a)a=W.cwd();else{a=W.R(a);if(!a)throw new W.g(8);a=a.path}if(0==b.length){if(!d)throw new W.g(44);return a}return U(a,b)}
function Bb(a,b,d){try{var e=a(b)}catch(g){if(g&&g.node&&kb(b)!==kb(W.J(g.node)))return-54;throw g;}J[d>>2]=e.dev;J[d+4>>2]=0;J[d+8>>2]=e.ino;J[d+12>>2]=e.mode;J[d+16>>2]=e.nlink;J[d+20>>2]=e.uid;J[d+24>>2]=e.gid;J[d+28>>2]=e.rdev;J[d+32>>2]=0;S=[e.size>>>0,(R=e.size,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];J[d+40>>2]=S[0];J[d+44>>2]=S[1];J[d+48>>2]=4096;J[d+52>>2]=e.blocks;J[d+56>>2]=e.atime.getTime()/1E3|0;J[d+60>>
2]=0;J[d+64>>2]=e.mtime.getTime()/1E3|0;J[d+68>>2]=0;J[d+72>>2]=e.ctime.getTime()/1E3|0;J[d+76>>2]=0;S=[e.ino>>>0,(R=e.ino,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];J[d+80>>2]=S[0];J[d+84>>2]=S[1];return 0}var Cb=void 0;function Db(){assert(void 0!=Cb);Cb+=4;return J[Cb-4>>2]}function Y(a){a=W.R(a);if(!a)throw new W.g(8);return a}
function Eb(a,b,d){function e(q){return(q=q.toTimeString().match(/\(([A-Za-z ]+)\)$/))?q[1]:"GMT"}var g=(new Date).getFullYear(),k=new Date(g,0,1),l=new Date(g,6,1);g=k.getTimezoneOffset();var p=l.getTimezoneOffset();J[a>>2]=60*Math.max(g,p);J[b>>2]=Number(g!=p);a=e(k);b=e(l);a=Fa(a);b=Fa(b);p<g?(J[d>>2]=a,J[d+4>>2]=b):(J[d>>2]=b,J[d+4>>2]=a)}function Fb(a,b,d){Fb.$a||(Fb.$a=!0,Eb(a,b,d))}function Gb(){void 0===Gb.start&&(Gb.start=Date.now());return 1E3*(Date.now()-Gb.start)|0}var Hb;
Hb=ha?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Ib={};function Jb(){if(!Kb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ib)void 0===Ib[b]?delete a[b]:a[b]=Ib[b];var d=[];for(b in a)d.push(b+"="+a[b]);Kb=d}return Kb}var Kb;
function Lb(a,b,d,e){a||(a=this);this.parent=a;this.s=a.s;this.Z=null;this.id=W.ub++;this.name=b;this.mode=d;this.h={};this.j={};this.rdev=e}Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},qb:{get:function(){return W.u(this.mode)}},sa:{get:function(){return W.W(this.mode)}}});W.Va=Lb;W.Bb();var zb;
c.FS_createPath=W.Fa;c.FS_createDataFile=W.ea;c.FS_createPreloadedFile=W.Ga;c.FS_createLazyFile=W.Ea;c.FS_createDevice=W.C;c.FS_unlink=W.unlink;
xb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,
ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,
EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function rb(a){var b=Array(Ea(a)+1);a=Da(a,b,0,b.length);b.length=a;return b}
var Nb={__syscall_faccessat:function(a,b,d,e){try{b=G(b);assert(0===e);b=Ab(a,b);if(d&-8)var g=-28;else{var k=W.l(b,{B:!0}).node;k?(a="",d&4&&(a+="r"),d&2&&(a+="w"),d&1&&(a+="x"),g=a&&W.K(k,a)?-2:0):g=-44}return g}catch(l){if("undefined"==typeof W||!(l instanceof W.g))throw l;return-l.o}},__syscall_fcntl64:function(a,b,d){Cb=d;try{var e=Y(a);switch(b){case 0:var g=Db();return 0>g?-28:W.open(e.path,e.flags,0,g).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return g=Db(),e.flags|=g,0;case 5:return g=
Db(),Ia[g+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return J[Mb()>>2]=28,-1;default:return-28}}catch(k){if("undefined"==typeof W||!(k instanceof W.g))throw k;return-k.o}},__syscall_fstat64:function(a,b){try{var d=Y(a);return Bb(W.stat,d.path,b)}catch(e){if("undefined"==typeof W||!(e instanceof W.g))throw e;return-e.o}},__syscall_fstatat64:function(a,b,d,e){try{b=G(b);var g=e&256,k=e&4096;e&=-4353;assert(!e,e);b=Ab(a,b,k);return Bb(g?W.lstat:W.stat,b,d)}catch(l){if("undefined"==
typeof W||!(l instanceof W.g))throw l;return-l.o}},__syscall_getdents64:function(a,b,d){try{var e=Y(a);e.L||(e.L=W.readdir(e.path));a=0;for(var g=W.A(e,0,1),k=Math.floor(g/280);k<e.L.length&&a+280<=d;){var l=e.L[k];if("."===l){var p=e.node.id;var q=4}else if(".."===l)p=W.l(e.path,{parent:!0}).node.id,q=4;else{var n=W.F(e.node,l);p=n.id;q=W.W(n.mode)?2:W.u(n.mode)?4:W.M(n.mode)?10:8}assert(p);S=[p>>>0,(R=p,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>
0))/4294967296)>>>0:0)];J[b+a>>2]=S[0];J[b+a+4>>2]=S[1];S=[280*(k+1)>>>0,(R=280*(k+1),1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];J[b+a+8>>2]=S[0];J[b+a+12>>2]=S[1];Ia[b+a+16>>1]=280;F[b+a+18>>0]=q;za(l,b+a+19,256);a+=280;k+=1}W.A(e,280*k,0);return a}catch(r){if("undefined"==typeof W||!(r instanceof W.g))throw r;return-r.o}},__syscall_ioctl:function(a,b,d){Cb=d;try{var e=Y(a);switch(b){case 21509:case 21505:return e.tty?
0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var g=Db();return J[g>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return g=Db(),W.ra(e,b,g);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:f("bad ioctl syscall "+b)}}catch(k){if("undefined"==typeof W||!(k instanceof W.g))throw k;return-k.o}},__syscall_lstat64:function(a,b){try{return a=G(a),Bb(W.lstat,a,b)}catch(d){if("undefined"==typeof W||!(d instanceof
W.g))throw d;return-d.o}},__syscall_open:function(a,b,d){Cb=d;try{var e=G(a),g=d?Db():0;return W.open(e,b,g).fd}catch(k){if("undefined"==typeof W||!(k instanceof W.g))throw k;return-k.o}},__syscall_rename:function(a,b){try{return a=G(a),b=G(b),W.rename(a,b),0}catch(d){if("undefined"==typeof W||!(d instanceof W.g))throw d;return-d.o}},__syscall_rmdir:function(a){try{return a=G(a),W.rmdir(a),0}catch(b){if("undefined"==typeof W||!(b instanceof W.g))throw b;return-b.o}},__syscall_stat64:function(a,b){try{return a=
G(a),Bb(W.stat,a,b)}catch(d){if("undefined"==typeof W||!(d instanceof W.g))throw d;return-d.o}},__syscall_unlink:function(a){try{return a=G(a),W.unlink(a),0}catch(b){if("undefined"==typeof W||!(b instanceof W.g))throw b;return-b.o}},_gmtime_js:function(a,b){a=new Date(1E3*J[a>>2]);J[b>>2]=a.getUTCSeconds();J[b+4>>2]=a.getUTCMinutes();J[b+8>>2]=a.getUTCHours();J[b+12>>2]=a.getUTCDate();J[b+16>>2]=a.getUTCMonth();J[b+20>>2]=a.getUTCFullYear()-1900;J[b+24>>2]=a.getUTCDay();J[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),
0,1,0,0,0,0))/864E5|0},_localtime_js:function(a,b){a=new Date(1E3*J[a>>2]);J[b>>2]=a.getSeconds();J[b+4>>2]=a.getMinutes();J[b+8>>2]=a.getHours();J[b+12>>2]=a.getDate();J[b+16>>2]=a.getMonth();J[b+20>>2]=a.getFullYear()-1900;J[b+24>>2]=a.getDay();var d=new Date(a.getFullYear(),0,1);J[b+28>>2]=(a.getTime()-d.getTime())/864E5|0;J[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();d=d.getTimezoneOffset();J[b+32>>2]=(e!=d&&a.getTimezoneOffset()==Math.min(d,
e))|0},_mktime_js:function(a){var b=new Date(J[a+20>>2]+1900,J[a+16>>2],J[a+12>>2],J[a+8>>2],J[a+4>>2],J[a>>2],0),d=J[a+32>>2],e=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),k=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),l=g.getTimezoneOffset(),p=Math.min(l,k);0>d?J[a+32>>2]=Number(k!=l&&p==e):0<d!=(p==e)&&(k=Math.max(l,k),b.setTime(b.getTime()+6E4*((0<d?p:k)-e)));J[a+24>>2]=b.getDay();J[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;J[a>>2]=b.getSeconds();J[a+4>>2]=b.getMinutes();J[a+
8>>2]=b.getHours();J[a+12>>2]=b.getDate();J[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},_tzset_js:Fb,abort:function(){f("native code called abort()")},clock:Gb,clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Hb();else return J[Mb()>>2]=28,-1;J[b>>2]=a/1E3|0;J[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_get_now:Hb,emscripten_memcpy_big:function(a,b,d){I.copyWithin(a,b,b+d)},emscripten_resize_heap:function(a){var b=I.length;a>>>=0;assert(a>b);if(2147483648<a)return x("Cannot enlarge memory, asked to go up to "+
a+" bytes, but the limit is 2147483648 bytes!"),!1;for(var d=1;4>=d;d*=2){var e=b*(1+.2/d);e=Math.min(e,a+100663296);var g=Math;e=Math.max(a,e);g=g.min.call(g,2147483648,e+(65536-e%65536)%65536);e=Hb();a:{var k=g;try{ua.grow(k-Ha.byteLength+65535>>>16);Ka();var l=1;break a}catch(p){x("emscripten_realloc_buffer: Attempted to grow heap from "+Ha.byteLength+" bytes to "+k+" bytes, but got error: "+p)}l=void 0}k=Hb();y("Heap resize call from "+b+" to "+g+" took "+(k-e)+" msecs. Success: "+!!l);if(l)return!0}x("Failed to grow the heap from "+
b+" bytes to "+g+" bytes, not enough memory!");return!1},environ_get:function(a,b){var d=0;Jb().forEach(function(e,g){var k=b+d;g=J[a+4*g>>2]=k;for(k=0;k<e.length;++k)assert(e.charCodeAt(k)===(e.charCodeAt(k)&255)),F[g++>>0]=e.charCodeAt(k);F[g>>0]=0;d+=e.length+1});return 0},environ_sizes_get:function(a,b){var d=Jb();J[a>>2]=d.length;var e=0;d.forEach(function(g){e+=g.length+1});J[b>>2]=e;return 0},fd_close:function(a){try{var b=Y(a);W.close(b);return 0}catch(d){if("undefined"==typeof W||!(d instanceof
W.g))throw d;return d.o}},fd_fdstat_get:function(a,b){try{var d=Y(a);F[b>>0]=d.tty?2:W.u(d.mode)?3:W.M(d.mode)?7:4;return 0}catch(e){if("undefined"==typeof W||!(e instanceof W.g))throw e;return e.o}},fd_read:function(a,b,d,e){try{a:{for(var g=Y(a),k=a=0;k<d;k++){var l=J[b+(8*k+4)>>2],p=W.read(g,F,J[b+8*k>>2],l,void 0);if(0>p){var q=-1;break a}a+=p;if(p<l)break}q=a}J[e>>2]=q;return 0}catch(n){if("undefined"==typeof W||!(n instanceof W.g))throw n;return n.o}},fd_seek:function(a,b,d,e,g){try{var k=Y(a);
a=4294967296*d+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;W.A(k,a,e);S=[k.position>>>0,(R=k.position,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];J[g>>2]=S[0];J[g+4>>2]=S[1];k.L&&0===a&&0===e&&(k.L=null);return 0}catch(l){if("undefined"==typeof W||!(l instanceof W.g))throw l;return l.o}},fd_write:function(a,b,d,e){try{a:{for(var g=Y(a),k=a=0;k<d;k++){var l=W.write(g,F,J[b+8*k>>2],J[b+(8*k+4)>>2],void 0);
if(0>l){var p=-1;break a}a+=l}p=a}J[e>>2]=p;return 0}catch(q){if("undefined"==typeof W||!(q instanceof W.g))throw q;return q.o}},gettimeofday:function(a){var b=Date.now();J[a>>2]=b/1E3|0;J[a+4>>2]=b%1E3*1E3|0;return 0},setTempRet0:function(){}};
(function(){function a(k){c.asm=k.exports;ua=c.asm.memory;assert(ua,"memory not found in wasm exports");Ka();Ma=c.asm.__indirect_function_table;assert(Ma,"table not found in wasm exports");Sa.unshift(c.asm.__wasm_call_ctors);ab("wasm-instantiate")}function b(k){assert(c===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;a(k.instance)}function d(k){return eb().then(function(l){return WebAssembly.instantiate(l,e)}).then(function(l){return l}).then(k,
function(l){x("failed to asynchronously prepare wasm: "+l);P.startsWith("file://")&&x("warning: Loading from a file URI ("+P+") is not supported in most browsers. See https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing");f(l)})}var e={env:Nb,wasi_snapshot_preview1:Nb};$a("wasm-instantiate");var g=c;if(c.instantiateWasm)try{return c.instantiateWasm(e,a)}catch(k){return x("Module.instantiateWasm callback failed with error: "+
k),!1}(function(){return ta||"function"!=typeof WebAssembly.instantiateStreaming||bb()||P.startsWith("file://")||"function"!=typeof fetch?d(b):fetch(P,{credentials:"same-origin"}).then(function(k){return WebAssembly.instantiateStreaming(k,e).then(b,function(l){x("wasm streaming compile failed: "+l);x("falling back to ArrayBuffer instantiation");return d(b)})})})().catch(ba);return{}})();c.___wasm_call_ctors=Q("__wasm_call_ctors");var Ga=c._malloc=Q("malloc");c._decode=Q("decode");
c._open_audio_decode=Q("open_audio_decode");c._audio_decode=Q("audio_decode");c._close_audio_decode=Q("close_audio_decode");c._encode=Q("encode");c._open_audio_encode=Q("open_audio_encode");c._audio_encode=Q("audio_encode");c._close_audio_encode=Q("close_audio_encode");c._main=Q("main");var Mb=c.___errno_location=Q("__errno_location");c._free=Q("free");
var yb=c.___stdio_exit=Q("__stdio_exit"),ub=c._emscripten_builtin_memalign=Q("emscripten_builtin_memalign"),Ob=c._emscripten_stack_init=function(){return(Ob=c._emscripten_stack_init=c.asm.emscripten_stack_init).apply(null,arguments)};c._emscripten_stack_get_free=function(){return(c._emscripten_stack_get_free=c.asm.emscripten_stack_get_free).apply(null,arguments)};c._emscripten_stack_get_base=function(){return(c._emscripten_stack_get_base=c.asm.emscripten_stack_get_base).apply(null,arguments)};
var Oa=c._emscripten_stack_get_end=function(){return(Oa=c._emscripten_stack_get_end=c.asm.emscripten_stack_get_end).apply(null,arguments)},Aa=c.stackSave=Q("stackSave"),Ba=c.stackRestore=Q("stackRestore"),ya=c.stackAlloc=Q("stackAlloc");c.dynCall_jiji=Q("dynCall_jiji");c.dynCall_iiiji=Q("dynCall_iiiji");c.dynCall_jiiij=Q("dynCall_jiiij");c.dynCall_jiiji=Q("dynCall_jiiji");c.dynCall_viiijj=Q("dynCall_viiijj");c.dynCall_jij=Q("dynCall_jij");c.dynCall_jii=Q("dynCall_jii");D("intArrayFromString");D("intArrayToString");
D("ccall");c.cwrap=function(a,b,d){return function(){return xa(a,b,d,arguments)}};D("setValue");D("getValue");D("allocate");D("UTF8ArrayToString");D("UTF8ToString");D("stringToUTF8Array");D("stringToUTF8");D("lengthBytesUTF8");D("stackTrace");D("addOnPreRun");D("addOnInit");D("addOnPreMain");D("addOnExit");D("addOnPostRun");D("writeStringToMemory");D("writeArrayToMemory");D("writeAsciiToMemory");c.addRunDependency=$a;c.removeRunDependency=ab;D("FS_createFolder");c.FS_createPath=W.Fa;
c.FS_createDataFile=W.ea;c.FS_createPreloadedFile=W.Ga;c.FS_createLazyFile=W.Ea;D("FS_createLink");c.FS_createDevice=W.C;c.FS_unlink=W.unlink;D("getLEB");D("getFunctionTables");D("alignFunctionTables");D("registerFunctions");D("addFunction");D("removeFunction");D("getFuncWrapper");D("prettyPrint");D("dynCall");D("getCompilerSetting");D("print");D("printErr");D("getTempRet0");D("setTempRet0");D("callMain");D("abort");D("keepRuntimeAlive");D("zeroMemory");D("stringToNewUTF8");D("emscripten_realloc_buffer");
D("ENV");D("withStackSave");D("ERRNO_CODES");D("ERRNO_MESSAGES");D("setErrNo");D("inetPton4");D("inetNtop4");D("inetPton6");D("inetNtop6");D("readSockaddr");D("writeSockaddr");D("DNS");D("getHostByName");D("Protocols");D("Sockets");D("getRandomDevice");D("traverseStack");D("convertFrameToPC");D("UNWIND_CACHE");D("saveInUnwindCache");D("convertPCtoSourceLocation");D("readAsmConstArgsArray");D("readAsmConstArgs");D("mainThreadEM_ASM");D("jstoi_q");D("jstoi_s");D("getExecutableName");D("listenOnce");
D("autoResumeAudioContext");D("dynCallLegacy");D("getDynCaller");D("dynCall");D("callRuntimeCallbacks");D("wasmTableMirror");D("setWasmTableEntry");D("getWasmTableEntry");D("handleException");D("runtimeKeepalivePush");D("runtimeKeepalivePop");D("callUserCallback");D("maybeExit");D("safeSetTimeout");D("asmjsMangle");D("asyncLoad");D("alignMemory");D("mmapAlloc");D("reallyNegative");D("unSign");D("reSign");D("formatString");D("PATH");D("PATH_FS");D("SYSCALLS");D("getSocketFromFD");D("getSocketAddress");
D("JSEvents");D("registerKeyEventCallback");D("specialHTMLTargets");D("maybeCStringToJsString");D("findEventTarget");D("findCanvasEventTarget");D("getBoundingClientRect");D("fillMouseEventData");D("registerMouseEventCallback");D("registerWheelEventCallback");D("registerUiEventCallback");D("registerFocusEventCallback");D("fillDeviceOrientationEventData");D("registerDeviceOrientationEventCallback");D("fillDeviceMotionEventData");D("registerDeviceMotionEventCallback");D("screenOrientation");D("fillOrientationChangeEventData");
D("registerOrientationChangeEventCallback");D("fillFullscreenChangeEventData");D("registerFullscreenChangeEventCallback");D("registerRestoreOldStyle");D("hideEverythingExceptGivenElement");D("restoreHiddenElements");D("setLetterbox");D("currentFullscreenStrategy");D("restoreOldWindowedStyle");D("softFullscreenResizeWebGLRenderTarget");D("doRequestFullscreen");D("fillPointerlockChangeEventData");D("registerPointerlockChangeEventCallback");D("registerPointerlockErrorEventCallback");D("requestPointerLock");
D("fillVisibilityChangeEventData");D("registerVisibilityChangeEventCallback");D("registerTouchEventCallback");D("fillGamepadEventData");D("registerGamepadEventCallback");D("registerBeforeUnloadEventCallback");D("fillBatteryEventData");D("battery");D("registerBatteryEventCallback");D("setCanvasElementSize");D("getCanvasElementSize");D("demangle");D("demangleAll");D("jsStackTrace");D("stackTrace");D("getEnvStrings");D("checkWasiClock");D("writeI53ToI64");D("writeI53ToI64Clamped");D("writeI53ToI64Signaling");
D("writeI53ToU64Clamped");D("writeI53ToU64Signaling");D("readI53FromI64");D("readI53FromU64");D("convertI32PairToI53");D("convertU32PairToI53");D("setImmediateWrapped");D("clearImmediateWrapped");D("polyfillSetImmediate");D("uncaughtExceptionCount");D("exceptionLast");D("exceptionCaught");D("ExceptionInfo");D("CatchInfo");D("exception_addRef");D("exception_decRef");D("Browser");D("funcWrappers");D("getFuncWrapper");D("setMainLoop");D("wget");D("FS");D("MEMFS");D("TTY");D("PIPEFS");D("SOCKFS");D("_setNetworkCallback");
D("tempFixedLengthArray");D("miniTempWebGLFloatBuffers");D("heapObjectForWebGLType");D("heapAccessShiftForWebGLHeap");D("GL");D("emscriptenWebGLGet");D("computeUnpackAlignedImageSize");D("emscriptenWebGLGetTexPixelData");D("emscriptenWebGLGetUniform");D("webglGetUniformLocation");D("webglPrepareUniformLocationsBeforeFirstUse");D("webglGetLeftBracePos");D("emscriptenWebGLGetVertexAttrib");D("writeGLArray");D("AL");D("SDL_unicode");D("SDL_ttfContext");D("SDL_audio");D("SDL");D("SDL_gfx");D("GLUT");
D("EGL");D("GLFW_Window");D("GLFW");D("GLEW");D("IDBStore");D("runAndAbortIfError");D("warnOnce");D("stackSave");D("stackRestore");D("stackAlloc");D("AsciiToString");D("stringToAscii");D("UTF16ToString");D("stringToUTF16");D("lengthBytesUTF16");D("UTF32ToString");D("stringToUTF32");D("lengthBytesUTF32");D("allocateUTF8");D("allocateUTF8OnStack");c.writeStackCookie=Na;c.checkStackCookie=K;sa("ALLOC_NORMAL");sa("ALLOC_STACK");var Pb;
function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ya=function Rb(){Pb||Sb();Pb||(Ya=Rb)};
function Sb(){function a(){if(!Pb&&(Pb=!0,c.calledRun=!0,!va)){K();assert(!Va);Va=!0;c.noFSInit||W.V.ga||W.V();W.Sa=!1;fb(Sa);K();fb(Ta);aa(c);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(Tb){assert(0==L,'cannot call main when async dependencies remain! (listen on Module["onRuntimeInitialized"])');assert(0==Ra.length,"cannot call main when preRun functions remain to be called");var b=c._main;try{var d=b(0,0);oa||Ub();noExitRuntime||0<oa||(K(),Wa=!0);if(!(noExitRuntime||0<oa)){if(c.onExit)c.onExit(d);
va=!0}ea(d,new ka(d))}catch(e){e instanceof ka||"unwind"==e||ea(1,e)}finally{}}K();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;)b=c.postRun.shift(),Ua.unshift(b);fb(Ua)}}if(!(0<L)){Ob();Na();if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Xa();fb(Ra);0<L||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);a()},1)):a(),K())}}c.run=Sb;
function Ub(){var a=y,b=x,d=!1;y=x=()=>{d=!0};try{yb(),["stdout","stderr"].forEach(function(e){(e=W.da("/dev/"+e))&&(e=ob[e.object.rdev])&&e.output&&e.output.length&&(d=!0)})}catch(e){}y=a;x=b;d&&pa("stdio streams had content in them that was not flushed. you should set EXIT_RUNTIME to 1 (see the FAQ), or make sure to emit a newline when you printf etc.")}if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();var Tb=!0;c.noInitialRun&&(Tb=!1);
Sb();self.FS=W;


  return createFFmepgModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmepgModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmepgModule; });
else if (typeof exports === 'object')
  exports["createFFmepgModule"] = createFFmepgModule;
