
var createFFmepgModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmepgModule) {
  createFFmepgModule = createFFmepgModule || {};


var d;d||(d=typeof createFFmepgModule !== 'undefined' ? createFFmepgModule : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});Object.getOwnPropertyDescriptor(d.ready,"_decode")||(Object.defineProperty(d.ready,"_decode",{configurable:!0,get:function(){f("You are getting _decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_decode",{configurable:!0,set:function(){f("You are setting _decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_open_audio_decode")||(Object.defineProperty(d.ready,"_open_audio_decode",{configurable:!0,get:function(){f("You are getting _open_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_open_audio_decode",{configurable:!0,set:function(){f("You are setting _open_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_audio_decode")||(Object.defineProperty(d.ready,"_audio_decode",{configurable:!0,get:function(){f("You are getting _audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_audio_decode",{configurable:!0,set:function(){f("You are setting _audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_close_audio_decode")||(Object.defineProperty(d.ready,"_close_audio_decode",{configurable:!0,get:function(){f("You are getting _close_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_close_audio_decode",{configurable:!0,set:function(){f("You are setting _close_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"___stdio_exit")||(Object.defineProperty(d.ready,"___stdio_exit",{configurable:!0,get:function(){f("You are getting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"___stdio_exit",{configurable:!0,set:function(){f("You are setting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"onRuntimeInitialized")||(Object.defineProperty(d.ready,"onRuntimeInitialized",{configurable:!0,get:function(){f("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"onRuntimeInitialized",{configurable:!0,set:function(){f("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var ca=Object.assign({},d),da="./this.program",ea="object"==typeof window,k="function"==typeof importScripts,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ha=!ea&&!fa&&!k;if(d.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var n="",v,w,x,fs,ia,ja;
if(fa){if("object"!=typeof process||"function"!=typeof require)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");n=k?require("path").dirname(n)+"/":__dirname+"/";ja=()=>{ia||(fs=require("fs"),ia=require("path"))};v=function(a,b){ja();a=ia.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};x=a=>{a=v(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);
return a};w=(a,b,c)=>{ja();a=ia.normalize(a);fs.readFile(a,function(e,g){e?c(e):b(g.buffer)})};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",function(a){throw a;});d.inspect=function(){return"[Emscripten Module object]"}}else if(ha){if("object"==typeof process&&"function"===typeof require||"object"==typeof window||"function"==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");
"undefined"!=typeof read&&(v=function(a){return read(a)});x=function(a){if("function"==typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"==typeof a);return a};w=function(a,b){setTimeout(()=>b(x(a)),0)};"undefined"!=typeof print&&("undefined"==typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!=typeof printErr?printErr:print)}else if(ea||k){k?n=self.location.href:"undefined"!=typeof document&&document.currentScript&&(n=document.currentScript.src);
_scriptDir&&(n=_scriptDir);0!==n.indexOf("blob:")?n=n.substr(0,n.replace(/[?#].*/,"").lastIndexOf("/")+1):n="";if("object"!=typeof window&&"function"!=typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};k&&(x=a=>{var b=new XMLHttpRequest;b.open("GET",
a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});w=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)}}else throw Error("environment detection error");var ka=d.print||console.log.bind(console),B=d.printErr||console.warn.bind(console);Object.assign(d,ca);ca=null;Object.getOwnPropertyDescriptor(d,"fetchSettings")&&f("`Module.fetchSettings` was supplied but `fetchSettings` not included in INCOMING_MODULE_JS_API");
C("arguments","arguments_");d.thisProgram&&(da=d.thisProgram);C("thisProgram","thisProgram");C("quit","quit_");assert("undefined"==typeof d.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof d.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof d.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"==typeof d.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof d.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"==typeof d.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");assert("undefined"==typeof d.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"==typeof d.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");
assert("undefined"==typeof d.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");C("read","read_");C("readAsync","readAsync");C("readBinary","readBinary");C("setWindowTitle","setWindowTitle");assert(!ha,"shell environment detected but not enabled at build time.  Add 'shell' to `-s ENVIRONMENT` to enable.");function la(a){ma||(ma={});ma[a]||(ma[a]=1,B(a))}var ma;
function C(a,b){Object.getOwnPropertyDescriptor(d,a)||Object.defineProperty(d,a,{configurable:!0,get:function(){f("Module."+a+" has been replaced with plain "+b+" (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}})}
function na(a,b){a="'"+a+"' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)";b&&(a+=". Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you");return a}function oa(a){Object.getOwnPropertyDescriptor(d,a)||Object.defineProperty(d,a,{configurable:!0,get:function(){f(na(a,!1))}})}function D(a,b){Object.getOwnPropertyDescriptor(d,a)||(d[a]=()=>f(na(a,b)))}var pa;d.wasmBinary&&(pa=d.wasmBinary);C("wasmBinary","wasmBinary");
var noExitRuntime=d.noExitRuntime||!0;C("noExitRuntime","noExitRuntime");"object"!=typeof WebAssembly&&f("no native wasm support detected");var qa,ra=!1;function assert(a,b){a||f("Assertion failed"+(b?": "+b:""))}function sa(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ta(a,b,c,e){var g={string:function(p){var r=0;if(null!==p&&void 0!==p&&0!==p){var y=(p.length<<2)+1;r=ua(y);va(p,r,y)}return r},array:function(p){var r=ua(p.length);wa(p,r);return r}};a=sa(a);var h=[],l=0;assert("array"!==b,'Return type should not be "array".');if(e)for(var q=0;q<e.length;q++){var t=g[c[q]];t?(0===l&&(l=xa()),h[q]=t(e[q])):h[q]=e[q]}c=a.apply(null,h);return c=function(p){0!==l&&ya(l);return"string"===b?E(p):"boolean"===b?!!p:p}(c)}
var za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function H(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&za)return za.decode(a.subarray(b,c));for(e="";b<c;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;224==(g&240)?g=(g&15)<<12|h<<6|l:(240!=(g&248)&&la("Invalid UTF-8 leading byte 0x"+g.toString(16)+" encountered when deserializing a UTF-8 string in wasm memory to a JS string!"),g=(g&7)<<18|h<<12|l<<6|a[b++]&63);65536>g?e+=String.fromCharCode(g):(g-=65536,e+=
String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}function E(a){return a?H(I,a,void 0):""}
function Aa(a,b,c,e){if(!(0<e))return 0;var g=c;e=c+e-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var q=a.charCodeAt(++h);l=65536+((l&1023)<<10)|q&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;1114111<l&&la("Invalid Unicode code point 0x"+l.toString(16)+" encountered when serializing a JS string to a UTF-8 string in wasm memory! (Valid unicode code points should be in range 0-0x10FFFF).");
b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-g}function va(a,b,c){assert("number"==typeof c,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");Aa(a,I,b,c)}function Ba(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!=typeof TextDecoder&&new TextDecoder("utf-16le");
function Ca(a){var b=Ba(a)+1,c=Da(b);c&&Aa(a,J,c,b);return c}function wa(a,b){assert(0<=a.length,"writeArrayToMemory array must have a length (should be an array or typed array)");J.set(a,b)}var Ea,J,I,Fa,K,Ga;function Ha(){var a=qa.buffer;Ea=a;d.HEAP8=J=new Int8Array(a);d.HEAP16=Fa=new Int16Array(a);d.HEAP32=K=new Int32Array(a);d.HEAPU8=I=new Uint8Array(a);d.HEAPU16=new Uint16Array(a);d.HEAPU32=Ga=new Uint32Array(a);d.HEAPF32=new Float32Array(a);d.HEAPF64=new Float64Array(a)}
d.TOTAL_STACK&&assert(5242880===d.TOTAL_STACK,"the stack size can no longer be determined at runtime");var Ia=d.INITIAL_MEMORY||16777216;C("INITIAL_MEMORY","INITIAL_MEMORY");assert(5242880<=Ia,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+Ia+"! (TOTAL_STACK=5242880)");assert("undefined"!=typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!=Int32Array.prototype.subarray&&void 0!=Int32Array.prototype.set,"JS engine does not provide full typed array support");
assert(!d.wasmMemory,"Use of `wasmMemory` detected.  Use -s IMPORTED_MEMORY to define wasmMemory externally");assert(16777216==Ia,"Detected runtime INITIAL_MEMORY setting.  Use -s IMPORTED_MEMORY to define wasmMemory dynamically");var Ja;function Ka(){var a=La();assert(0==(a&3));K[a+4>>2]=34821223;K[a+8>>2]=2310721022;K[0]=1668509029}
function Ma(){if(!ra){var a=La(),b=Ga[a+4>>2];a=Ga[a+8>>2];34821223==b&&2310721022==a||f("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+a.toString(16)+" 0x"+b.toString(16));1668509029!==K[0]&&f("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var Na=new Int16Array(1),Oa=new Int8Array(Na.buffer);Na[0]=25459;
if(115!==Oa[0]||99!==Oa[1])throw"Runtime error: expected the system to be little-endian! (Run with -s SUPPORT_BIG_ENDIAN=1 to bypass)";var Pa=[],Qa=[],Ra=[],Sa=!1;function Ta(){var a=d.preRun.shift();Pa.unshift(a)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var M=0,N=null,Ua=null,O={};function Va(a){for(var b=a;;){if(!O[a])return a;a=b+Math.random()}}
function Wa(a){M++;d.monitorRunDependencies&&d.monitorRunDependencies(M);a?(assert(!O[a]),O[a]=1,null===N&&"undefined"!=typeof setInterval&&(N=setInterval(function(){if(ra)clearInterval(N),N=null;else{var b=!1,c;for(c in O)b||(b=!0,B("still waiting on run dependencies:")),B("dependency: "+c);b&&B("(end of list)")}},1E4))):B("warning: run dependency added without ID")}
function Xa(a){M--;d.monitorRunDependencies&&d.monitorRunDependencies(M);a?(assert(O[a]),delete O[a]):B("warning: run dependency removed without ID");0==M&&(null!==N&&(clearInterval(N),N=null),Ua&&(a=Ua,Ua=null,a()))}d.preloadedImages={};d.preloadedAudios={};function f(a){if(d.onAbort)d.onAbort(a);a="Aborted("+a+")";B(a);ra=!0;a=new WebAssembly.RuntimeError(a);ba(a);throw a;}function Ya(){return P.startsWith("data:application/octet-stream;base64,")}
function Q(a){return function(){var b=d.asm;assert(Sa,"native function `"+a+"` called before runtime initialization");assert(!0,"native function `"+a+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");b[a]||assert(b[a],"exported native function `"+a+"` not found");return b[a].apply(null,arguments)}}var P;P="daudio.wasm";if(!Ya()){var Za=P;P=d.locateFile?d.locateFile(Za,n):n+Za}
function $a(){var a=P;try{if(a==P&&pa)return new Uint8Array(pa);if(x)return x(a);throw"both async and sync fetching of the wasm failed";}catch(b){f(b)}}
function ab(){if(!pa&&(ea||k)){if("function"==typeof fetch&&!P.startsWith("file://"))return fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return $a()});if(w)return new Promise(function(a,b){w(P,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return $a()})}var R,S;
function bb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.Tb;"number"==typeof c?void 0===b.qa?cb(c)():cb(c)(b.qa):c(void 0===b.qa?null:b.qa)}}}function db(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){la("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return b===b?b:b+" ["+b+"]"})}var eb=[];
function cb(a){var b=eb[a];b||(a>=eb.length&&(eb.length=a+1),eb[a]=b=Ja.get(a));assert(Ja.get(a)==b,"JavaScript-side Wasm function table mirror is out of date!");return b}function fb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var g=a[e];"."===g?a.splice(e,1):".."===g?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function gb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function T(a){if("/"===a)return"/";a=gb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function U(a,b){return gb(a+"/"+b)}
function ib(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(fa)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){f("no cryptographic support found for randomDevice. consider polyfilling it if you want to use something insecure like Math.random(), e.g. put this in a --pre-js: var crypto = { getRandomValues: function(array) { for (var i = 0; i < array.length; i++) array[i] = (Math.random()*256)|0 } };")}}
function V(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:W.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function jb(a,b){function c(l){for(var q=0;q<l.length&&""===l[q];q++);for(var t=l.length-1;0<=t&&""===l[t];t--);return q>t?[]:l.slice(q,t-q+1)}a=V(a).substr(1);b=V(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),g=e,h=0;h<e;h++)if(a[h]!==b[h]){g=h;break}e=[];for(h=g;h<a.length;h++)e.push("..");e=e.concat(b.slice(g));return e.join("/")}var kb=[];function lb(a,b){kb[a]={input:[],output:[],T:b};W.Ea(a,mb)}
var mb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new W.g(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.T.flush(a.tty)},flush:function(a){a.tty.T.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.T.Ra)throw new W.g(60);for(var g=0,h=0;h<e;h++){try{var l=a.tty.T.Ra(a.tty)}catch(q){throw new W.g(29);}if(void 0===l&&0===g)throw new W.g(6);if(null===l||void 0===l)break;g++;b[c+h]=l}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,e){if(!a.tty||!a.tty.T.Ba)throw new W.g(60);
try{for(var g=0;g<e;g++)a.tty.T.Ba(a.tty,b[c+g])}catch(h){throw new W.g(29);}e&&(a.node.timestamp=Date.now());return g}},ob={Ra:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(g){if(g.toString().includes("EOF"))e=0;else throw g;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},Ba:function(a,b){null===b||10===b?(ka(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ka(H(a.output,0)),a.output=[])}},pb={Ba:function(a,b){null===b||10===b?(B(H(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(B(H(a.output,0)),a.output=[])}},X={H:null,s:function(){return X.createNode(null,"/",16895,0)},createNode:function(a,
b,c,e){if(W.sb(c)||W.isFIFO(c))throw new W.g(63);X.H||(X.H={dir:{node:{D:X.h.D,v:X.h.v,lookup:X.h.lookup,I:X.h.I,rename:X.h.rename,unlink:X.h.unlink,rmdir:X.h.rmdir,readdir:X.h.readdir,symlink:X.h.symlink},stream:{B:X.j.B}},file:{node:{D:X.h.D,v:X.h.v},stream:{B:X.j.B,read:X.j.read,write:X.j.write,W:X.j.W,$:X.j.$,da:X.j.da}},link:{node:{D:X.h.D,v:X.h.v,readlink:X.h.readlink},stream:{}},Ia:{node:{D:X.h.D,v:X.h.v},stream:W.fb}});c=W.createNode(a,b,c,e);W.u(c.mode)?(c.h=X.H.dir.node,c.j=X.H.dir.stream,
c.i={}):W.isFile(c.mode)?(c.h=X.H.file.node,c.j=X.H.file.stream,c.m=0,c.i=null):W.N(c.mode)?(c.h=X.H.link.node,c.j=X.H.link.stream):W.Y(c.mode)&&(c.h=X.H.Ia.node,c.j=X.H.Ia.stream);c.timestamp=Date.now();a&&(a.i[b]=c,a.timestamp=c.timestamp);return c},Ub:function(a){return a.i?a.i.subarray?a.i.subarray(0,a.m):new Uint8Array(a.i):new Uint8Array(0)},Na:function(a,b){var c=a.i?a.i.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.i,a.i=new Uint8Array(b),0<a.m&&a.i.set(c.subarray(0,
a.m),0))},Cb:function(a,b){if(a.m!=b)if(0==b)a.i=null,a.m=0;else{var c=a.i;a.i=new Uint8Array(b);c&&a.i.set(c.subarray(0,Math.min(b,a.m)));a.m=b}},h:{D:function(a){var b={};b.dev=W.Y(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;W.u(a.mode)?b.size=4096:W.isFile(a.mode)?b.size=a.m:W.N(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.bb=4096;b.blocks=Math.ceil(b.size/b.bb);return b},v:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&X.Cb(a,b.size)},lookup:function(){throw W.ta[44];},I:function(a,b,c,e){return X.createNode(a,b,c,e)},rename:function(a,b,c){if(W.u(a.mode)){try{var e=W.F(b,c)}catch(h){}if(e)for(var g in e.i)throw new W.g(55);}delete a.parent.i[a.name];a.parent.timestamp=Date.now();a.name=c;b.i[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.i[b];a.timestamp=Date.now()},rmdir:function(a,
b){var c=W.F(a,b),e;for(e in c.i)throw new W.g(55);delete a.i[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.i)a.i.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=X.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!W.N(a.mode))throw new W.g(28);return a.link}},j:{read:function(a,b,c,e,g){var h=a.node.i;if(g>=a.node.m)return 0;a=Math.min(a.node.m-g,e);assert(0<=a);if(8<a&&h.subarray)b.set(h.subarray(g,g+a),c);else for(e=0;e<a;e++)b[c+
e]=h[g+e];return a},write:function(a,b,c,e,g,h){assert(!(b instanceof ArrayBuffer));b.buffer===J.buffer&&(h=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.i||a.i.subarray)){if(h)return assert(0===g,"canOwn must imply no weird position inside the file"),a.i=b.subarray(c,c+e),a.m=e;if(0===a.m&&0===g)return a.i=b.slice(c,c+e),a.m=e;if(g+e<=a.m)return a.i.set(b.subarray(c,c+e),g),e}X.Na(a,g+e);if(a.i.subarray&&b.subarray)a.i.set(b.subarray(c,c+e),g);else for(h=0;h<e;h++)a.i[g+h]=
b[c+h];a.m=Math.max(a.m,g+e);return e},B:function(a,b,c){1===c?b+=a.position:2===c&&W.isFile(a.node.mode)&&(b+=a.node.m);if(0>b)throw new W.g(28);return b},W:function(a,b,c){X.Na(a.node,b+c);a.node.m=Math.max(a.node.m,b+c)},$:function(a,b,c,e,g,h){if(0!==b)throw new W.g(28);if(!W.isFile(a.node.mode))throw new W.g(43);a=a.node.i;if(h&2||a.buffer!==Ea){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;assert(65536,"alignment argument is required");c=65536*
Math.ceil(c/65536);(h=qb(65536,c))?(I.fill(0,h,h+c),c=h):c=0;if(!c)throw new W.g(48);J.set(a,c)}else e=!1,c=a.byteOffset;return{cc:c,Lb:e}},da:function(a,b,c,e,g){if(!W.isFile(a.node.mode))throw new W.g(43);if(g&2)return 0;X.j.write(a,b,0,e,c,!1);return 0}}};function rb(a,b,c){var e=Va("al "+a);w(a,function(g){assert(g,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(g));e&&Xa(e)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Wa(e)}
var sb={0:"Success",1:"Arg list too long",2:"Permission denied",3:"Address already in use",4:"Address not available",5:"Address family not supported by protocol family",6:"No more processes",7:"Socket already connected",8:"Bad file number",9:"Trying to read unreadable message",10:"Mount device busy",11:"Operation canceled",12:"No children",13:"Connection aborted",14:"Connection refused",15:"Connection reset by peer",16:"File locking deadlock error",17:"Destination address required",18:"Math arg out of domain of func",
19:"Quota exceeded",20:"File exists",21:"Bad address",22:"File too large",23:"Host is unreachable",24:"Identifier removed",25:"Illegal byte sequence",26:"Connection already in progress",27:"Interrupted system call",28:"Invalid argument",29:"I/O error",30:"Socket is already connected",31:"Is a directory",32:"Too many symbolic links",33:"Too many open files",34:"Too many links",35:"Message too long",36:"Multihop attempted",37:"File or path name too long",38:"Network interface is not configured",39:"Connection reset by network",
40:"Network is unreachable",41:"Too many open files in system",42:"No buffer space available",43:"No such device",44:"No such file or directory",45:"Exec format error",46:"No record locks available",47:"The link has been severed",48:"Not enough core",49:"No message of desired type",50:"Protocol not available",51:"No space left on device",52:"Function not implemented",53:"Socket is not connected",54:"Not a directory",55:"Directory not empty",56:"State not recoverable",57:"Socket operation on non-socket",
59:"Not a typewriter",60:"No such device or address",61:"Value too large for defined data type",62:"Previous owner died",63:"Not super-user",64:"Broken pipe",65:"Protocol error",66:"Unknown protocol",67:"Protocol wrong type for socket",68:"Math result not representable",69:"Read only file system",70:"Illegal seek",71:"No such process",72:"Stale file handle",73:"Connection timed out",74:"Text file busy",75:"Cross-device link",100:"Device not a stream",101:"Bad font file fmt",102:"Invalid slot",103:"Invalid request code",
104:"No anode",105:"Block device required",106:"Channel number out of range",107:"Level 3 halted",108:"Level 3 reset",109:"Link number out of range",110:"Protocol driver not attached",111:"No CSI structure available",112:"Level 2 halted",113:"Invalid exchange",114:"Invalid request descriptor",115:"Exchange full",116:"No data (for no delay io)",117:"Timer expired",118:"Out of streams resources",119:"Machine is not on the network",120:"Package not installed",121:"The object is remote",122:"Advertise error",
123:"Srmount error",124:"Communication error on send",125:"Cross mount point (not really error)",126:"Given log. name not unique",127:"f.d. invalid for this operation",128:"Remote address changed",129:"Can   access a needed shared lib",130:"Accessing a corrupted shared lib",131:".lib section in a.out corrupted",132:"Attempting to link in too many libs",133:"Attempting to exec a shared library",135:"Streams pipe error",136:"Too many users",137:"Socket type not supported",138:"Not supported",139:"Protocol family not supported",
140:"Can't send after socket shutdown",141:"Too many references",142:"Host is down",148:"No medium (in tape drive)",156:"Level 2 not synchronized"},tb={},W={root:null,ba:[],La:{},streams:[],xb:1,G:null,Ka:"/",ha:!1,Va:!0,g:null,ta:{},ob:null,ea:0,l:(a,b={})=>{a=V(W.cwd(),a);if(!a)return{path:"",node:null};var c={sa:!0,Da:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.Da)throw new W.g(32);a=fb(a.split("/").filter(l=>!!l),!1);var g=W.root;c="/";for(e=0;e<a.length;e++){var h=e===a.length-1;if(h&&
b.parent)break;g=W.F(g,a[e]);c=U(c,a[e]);W.O(g)&&(!h||h&&b.sa)&&(g=g.aa.root);if(!h||b.C)for(h=0;W.N(g.mode);)if(g=W.readlink(c),c=V(hb(c),g),g=W.l(c,{Da:b.Da}).node,40<h++)throw new W.g(32);}return{path:c,node:g}},K:a=>{for(var b;;){if(W.ia(a))return a=a.s.Wa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},va:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%W.G.length},Ta:a=>{var b=W.va(a.parent.id,a.name);a.R=W.G[b];W.G[b]=a},Ua:a=>{var b=
W.va(a.parent.id,a.name);if(W.G[b]===a)W.G[b]=a.R;else for(b=W.G[b];b;){if(b.R===a){b.R=a.R;break}b=b.R}},F:(a,b)=>{var c=W.ub(a);if(c)throw new W.g(c,a);for(c=W.G[W.va(a.id,b)];c;c=c.R){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return W.lookup(a,b)},createNode:(a,b,c,e)=>{assert("object"==typeof a);a=new W.Ya(a,b,c,e);W.Ta(a);return a},ra:a=>{W.Ua(a)},ia:a=>a===a.parent,O:a=>!!a.aa,isFile:a=>32768===(a&61440),u:a=>16384===(a&61440),N:a=>40960===(a&61440),Y:a=>8192===(a&61440),sb:a=>24576===
(a&61440),isFIFO:a=>4096===(a&61440),isSocket:a=>49152===(a&49152),pb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},wb:a=>{var b=W.pb[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},Oa:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},L:(a,b)=>{if(W.Va)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},ub:a=>{var b=W.L(a,"x");return b?b:a.h.lookup?0:2},Aa:(a,b)=>{try{return W.F(a,
b),20}catch(c){}return W.L(a,"wx")},ja:(a,b,c)=>{try{var e=W.F(a,b)}catch(g){return g.o}if(a=W.L(a,"wx"))return a;if(c){if(!W.u(e.mode))return 54;if(W.ia(e)||W.K(e)===W.cwd())return 10}else if(W.u(e.mode))return 31;return 0},vb:(a,b)=>a?W.N(a.mode)?32:W.u(a.mode)&&("r"!==W.Oa(b)||b&512)?31:W.L(a,W.Oa(b)):44,Za:4096,yb:(a=0,b=W.Za)=>{for(;a<=b;a++)if(!W.streams[a])return a;throw new W.g(33);},S:a=>W.streams[a],mb:(a,b,c)=>{W.oa||(W.oa=function(){},W.oa.prototype={object:{get:function(){return this.node},
set:function(e){this.node=e}}});a=Object.assign(new W.oa,a);b=W.yb(b,c);a.fd=b;return W.streams[b]=a},gb:a=>{W.streams[a]=null},fb:{open:a=>{a.j=W.qb(a.node.rdev).j;a.j.open&&a.j.open(a)},B:()=>{throw new W.g(70);}},za:a=>a>>8,Yb:a=>a&255,P:(a,b)=>a<<8|b,Ea:(a,b)=>{W.La[a]={j:b}},qb:a=>W.La[a],Qa:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.ba)}return b},Xa:(a,b)=>{function c(l){assert(0<W.ea);W.ea--;return b(l)}function e(l){if(l){if(!e.nb)return e.nb=!0,c(l)}else++h>=
g.length&&c(null)}"function"==typeof a&&(b=a,a=!1);W.ea++;1<W.ea&&B("warning: "+W.ea+" FS.syncfs operations in flight at once, probably just doing extra work");var g=W.Qa(W.root.s),h=0;g.forEach(l=>{if(!l.type.Xa)return e(null);l.type.Xa(l,a,e)})},s:(a,b,c)=>{if("string"==typeof a)throw a;var e="/"===c,g=!c;if(e&&W.root)throw new W.g(10);if(!e&&!g){var h=W.l(c,{sa:!1});c=h.path;h=h.node;if(W.O(h))throw new W.g(10);if(!W.u(h.mode))throw new W.g(54);}b={type:a,bc:b,Wa:c,ba:[]};a=a.s(b);a.s=b;b.root=
a;e?W.root=a:h&&(h.aa=b,h.s&&h.s.ba.push(b));return a},ic:a=>{a=W.l(a,{sa:!1});if(!W.O(a.node))throw new W.g(28);a=a.node;var b=a.aa,c=W.Qa(b);Object.keys(W.G).forEach(e=>{for(e=W.G[e];e;){var g=e.R;c.includes(e.s)&&W.ra(e);e=g}});a.aa=null;b=a.s.ba.indexOf(b);assert(-1!==b);a.s.ba.splice(b,1)},lookup:(a,b)=>a.h.lookup(a,b),I:(a,b,c)=>{var e=W.l(a,{parent:!0}).node;a=T(a);if(!a||"."===a||".."===a)throw new W.g(28);var g=W.Aa(e,a);if(g)throw new W.g(g);if(!e.h.I)throw new W.g(63);return e.h.I(e,a,
b,c)},create:(a,b)=>W.I(a,(void 0!==b?b:438)&4095|32768,0),mkdir:(a,b)=>W.I(a,(void 0!==b?b:511)&1023|16384,0),Zb:(a,b)=>{a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{W.mkdir(c,b)}catch(g){if(20!=g.o)throw g;}}},ka:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return W.I(a,b|8192,c)},symlink:(a,b)=>{if(!V(a))throw new W.g(44);var c=W.l(b,{parent:!0}).node;if(!c)throw new W.g(44);b=T(b);var e=W.Aa(c,b);if(e)throw new W.g(e);if(!c.h.symlink)throw new W.g(63);return c.h.symlink(c,
b,a)},rename:(a,b)=>{var c=hb(a),e=hb(b),g=T(a),h=T(b);var l=W.l(a,{parent:!0});var q=l.node;l=W.l(b,{parent:!0});l=l.node;if(!q||!l)throw new W.g(44);if(q.s!==l.s)throw new W.g(75);var t=W.F(q,g);a=jb(a,e);if("."!==a.charAt(0))throw new W.g(28);a=jb(b,c);if("."!==a.charAt(0))throw new W.g(55);try{var p=W.F(l,h)}catch(r){}if(t!==p){b=W.u(t.mode);if(g=W.ja(q,g,b))throw new W.g(g);if(g=p?W.ja(l,h,b):W.Aa(l,h))throw new W.g(g);if(!q.h.rename)throw new W.g(63);if(W.O(t)||p&&W.O(p))throw new W.g(10);if(l!==
q&&(g=W.L(q,"w")))throw new W.g(g);W.Ua(t);try{q.h.rename(t,l,h)}catch(r){throw r;}finally{W.Ta(t)}}},rmdir:a=>{var b=W.l(a,{parent:!0}).node;a=T(a);var c=W.F(b,a),e=W.ja(b,a,!0);if(e)throw new W.g(e);if(!b.h.rmdir)throw new W.g(63);if(W.O(c))throw new W.g(10);b.h.rmdir(b,a);W.ra(c)},readdir:a=>{a=W.l(a,{C:!0}).node;if(!a.h.readdir)throw new W.g(54);return a.h.readdir(a)},unlink:a=>{var b=W.l(a,{parent:!0}).node;if(!b)throw new W.g(44);a=T(a);var c=W.F(b,a),e=W.ja(b,a,!1);if(e)throw new W.g(e);if(!b.h.unlink)throw new W.g(63);
if(W.O(c))throw new W.g(10);b.h.unlink(b,a);W.ra(c)},readlink:a=>{a=W.l(a).node;if(!a)throw new W.g(44);if(!a.h.readlink)throw new W.g(28);return V(W.K(a.parent),a.h.readlink(a))},stat:(a,b)=>{a=W.l(a,{C:!b}).node;if(!a)throw new W.g(44);if(!a.h.D)throw new W.g(63);return a.h.D(a)},lstat:a=>W.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?W.l(a,{C:!c}).node:a;if(!a.h.v)throw new W.g(63);a.h.v(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{W.chmod(a,b,!0)},fchmod:(a,b)=>{a=W.S(a);
if(!a)throw new W.g(8);W.chmod(a.node,b)},chown:(a,b,c,e)=>{a="string"==typeof a?W.l(a,{C:!e}).node:a;if(!a.h.v)throw new W.g(63);a.h.v(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{W.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=W.S(a);if(!a)throw new W.g(8);W.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new W.g(28);a="string"==typeof a?W.l(a,{C:!0}).node:a;if(!a.h.v)throw new W.g(63);if(W.u(a.mode))throw new W.g(31);if(!W.isFile(a.mode))throw new W.g(28);var c=W.L(a,"w");if(c)throw new W.g(c);a.h.v(a,{size:b,
timestamp:Date.now()})},Sb:(a,b)=>{a=W.S(a);if(!a)throw new W.g(8);if(0===(a.flags&2097155))throw new W.g(28);W.truncate(a.node,b)},jc:(a,b,c)=>{a=W.l(a,{C:!0}).node;a.h.v(a,{timestamp:Math.max(b,c)})},open:(a,b,c,e,g)=>{if(""===a)throw new W.g(44);b="string"==typeof b?W.wb(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var h=a;else{a=gb(a);try{h=W.l(a,{C:!(b&131072)}).node}catch(q){}}var l=!1;if(b&64)if(h){if(b&128)throw new W.g(20);}else h=W.I(a,c,0),l=!0;if(!h)throw new W.g(44);
W.Y(h.mode)&&(b&=-513);if(b&65536&&!W.u(h.mode))throw new W.g(54);if(!l&&(c=W.vb(h,b)))throw new W.g(c);b&512&&W.truncate(h,0);b&=-131713;e=W.mb({node:h,path:W.K(h),flags:b,seekable:!0,position:0,j:h.j,Jb:[],error:!1},e,g);e.j.open&&e.j.open(e);!d.logReadFiles||b&1||(W.Ca||(W.Ca={}),a in W.Ca||(W.Ca[a]=1));return e},close:a=>{if(W.Z(a))throw new W.g(8);a.M&&(a.M=null);try{a.j.close&&a.j.close(a)}catch(b){throw b;}finally{W.gb(a.fd)}a.fd=null},Z:a=>null===a.fd,B:(a,b,c)=>{if(W.Z(a))throw new W.g(8);
if(!a.seekable||!a.j.B)throw new W.g(70);if(0!=c&&1!=c&&2!=c)throw new W.g(28);a.position=a.j.B(a,b,c);a.Jb=[];return a.position},read:(a,b,c,e,g)=>{if(0>e||0>g)throw new W.g(28);if(W.Z(a))throw new W.g(8);if(1===(a.flags&2097155))throw new W.g(8);if(W.u(a.node.mode))throw new W.g(31);if(!a.j.read)throw new W.g(28);var h="undefined"!=typeof g;if(!h)g=a.position;else if(!a.seekable)throw new W.g(70);b=a.j.read(a,b,c,e,g);h||(a.position+=b);return b},write:(a,b,c,e,g,h)=>{if(0>e||0>g)throw new W.g(28);
if(W.Z(a))throw new W.g(8);if(0===(a.flags&2097155))throw new W.g(8);if(W.u(a.node.mode))throw new W.g(31);if(!a.j.write)throw new W.g(28);a.seekable&&a.flags&1024&&W.B(a,0,2);var l="undefined"!=typeof g;if(!l)g=a.position;else if(!a.seekable)throw new W.g(70);b=a.j.write(a,b,c,e,g,h);l||(a.position+=b);return b},W:(a,b,c)=>{if(W.Z(a))throw new W.g(8);if(0>b||0>=c)throw new W.g(28);if(0===(a.flags&2097155))throw new W.g(8);if(!W.isFile(a.node.mode)&&!W.u(a.node.mode))throw new W.g(43);if(!a.j.W)throw new W.g(138);
a.j.W(a,b,c)},$:(a,b,c,e,g,h)=>{if(0!==(g&2)&&0===(h&2)&&2!==(a.flags&2097155))throw new W.g(2);if(1===(a.flags&2097155))throw new W.g(2);if(!a.j.$)throw new W.g(43);return a.j.$(a,b,c,e,g,h)},da:(a,b,c,e,g)=>a&&a.j.da?a.j.da(a,b,c,e,g):0,ac:()=>0,wa:(a,b,c)=>{if(!a.j.wa)throw new W.g(59);return a.j.wa(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=W.open(a,b.flags);
a=W.stat(a).size;var g=new Uint8Array(a);W.read(e,g,0,a,0);"utf8"===b.encoding?c=H(g,0):"binary"===b.encoding&&(c=g);W.close(e);return c},writeFile:(a,b,c={})=>{c.flags=c.flags||577;a=W.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(Ba(b)+1);b=Aa(b,e,0,e.length);W.write(a,e,0,b,void 0,c.eb)}else if(ArrayBuffer.isView(b))W.write(a,b,0,b.byteLength,void 0,c.eb);else throw Error("Unsupported data type");W.close(a)},cwd:()=>W.Ka,chdir:a=>{a=W.l(a,{C:!0});if(null===a.node)throw new W.g(44);
if(!W.u(a.node.mode))throw new W.g(54);var b=W.L(a.node,"x");if(b)throw new W.g(b);W.Ka=a.path},ib:()=>{W.mkdir("/tmp");W.mkdir("/home");W.mkdir("/home/web_user")},hb:()=>{W.mkdir("/dev");W.Ea(W.P(1,3),{read:()=>0,write:(b,c,e,g)=>g});W.ka("/dev/null",W.P(1,3));lb(W.P(5,0),ob);lb(W.P(6,0),pb);W.ka("/dev/tty",W.P(5,0));W.ka("/dev/tty1",W.P(6,0));var a=ib();W.J("/dev","random",a);W.J("/dev","urandom",a);W.mkdir("/dev/shm");W.mkdir("/dev/shm/tmp")},kb:()=>{W.mkdir("/proc");var a=W.mkdir("/proc/self");
W.mkdir("/proc/self/fd");W.s({s:()=>{var b=W.createNode(a,"fd",16895,73);b.h={lookup:(c,e)=>{var g=W.S(+e);if(!g)throw new W.g(8);c={parent:null,s:{Wa:"fake"},h:{readlink:()=>g.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},lb:()=>{d.stdin?W.J("/dev","stdin",d.stdin):W.symlink("/dev/tty","/dev/stdin");d.stdout?W.J("/dev","stdout",null,d.stdout):W.symlink("/dev/tty","/dev/stdout");d.stderr?W.J("/dev","stderr",null,d.stderr):W.symlink("/dev/tty1","/dev/stderr");var a=W.open("/dev/stdin",
0),b=W.open("/dev/stdout",1),c=W.open("/dev/stderr",1);assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");assert(1===b.fd,"invalid handle for stdout ("+b.fd+")");assert(2===c.fd,"invalid handle for stderr ("+c.fd+")")},Ma:()=>{W.g||(W.g=function(a,b){this.node=b;this.Db=function(c){this.o=c;for(var e in tb)if(tb[e]===c){this.code=e;break}};this.Db(a);this.message=sb[a];this.stack&&(Object.defineProperty(this,"stack",{value:Error().stack,writable:!0}),this.stack=db(this.stack))},W.g.prototype=
Error(),W.g.prototype.constructor=W.g,[44].forEach(a=>{W.ta[a]=new W.g(a);W.ta[a].stack="<generic error, no stack>"}))},Eb:()=>{W.Ma();W.G=Array(4096);W.s(X,{},"/");W.ib();W.hb();W.kb();W.ob={MEMFS:X}},X:(a,b,c)=>{assert(!W.X.ha,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");W.X.ha=!0;W.Ma();d.stdin=a||d.stdin;d.stdout=b||d.stdout;d.stderr=c||d.stderr;W.lb()},dc:()=>{W.X.ha=
!1;ub();for(var a=0;a<W.streams.length;a++){var b=W.streams[a];b&&W.close(b)}},ua:(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Rb:(a,b)=>{a=W.pa(a,b);return a.exists?a.object:null},pa:(a,b)=>{try{var c=W.l(a,{C:!b});a=c.path}catch(g){}var e={ia:!1,exists:!1,error:0,name:null,path:null,object:null,zb:!1,Bb:null,Ab:null};try{c=W.l(a,{parent:!0}),e.zb=!0,e.Bb=c.path,e.Ab=c.node,e.name=T(a),c=W.l(a,{C:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.ia="/"===c.path}catch(g){e.error=
g.o}return e},Pb:(a,b)=>{a="string"==typeof a?a:W.K(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=U(a,c);try{W.mkdir(e)}catch(g){}a=e}}return e},jb:(a,b,c,e,g)=>{a=U("string"==typeof a?a:W.K(a),b);return W.create(a,W.ua(e,g))},Ja:(a,b,c,e,g,h)=>{var l=b;a&&(a="string"==typeof a?a:W.K(a),l=b?U(a,b):a);a=W.ua(e,g);l=W.create(l,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(g=c.length;e<g;++e)b[e]=c.charCodeAt(e);c=b}W.chmod(l,a|146);b=W.open(l,577);W.write(b,c,0,c.length,
0,h);W.close(b);W.chmod(l,a)}return l},J:(a,b,c,e)=>{a=U("string"==typeof a?a:W.K(a),b);b=W.ua(!!c,!!e);W.J.za||(W.J.za=64);var g=W.P(W.J.za++,0);W.Ea(g,{open:h=>{h.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(h,l,q,t)=>{for(var p=0,r=0;r<t;r++){try{var y=c()}catch(A){throw new W.g(29);}if(void 0===y&&0===p)throw new W.g(6);if(null===y||void 0===y)break;p++;l[q+r]=y}p&&(h.node.timestamp=Date.now());return p},write:(h,l,q,t)=>{for(var p=0;p<t;p++)try{e(l[q+p])}catch(r){throw new W.g(29);
}t&&(h.node.timestamp=Date.now());return p}});return W.ka(a,b,g)},Pa:a=>{if(a.xa||a.tb||a.link||a.i)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(v)try{a.i=nb(v(a.url),!0),a.m=a.i.length}catch(b){throw new W.g(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Nb:(a,
b,c,e,g)=>{function h(){this.ya=!1;this.ga=[]}h.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.chunkSize;return this.Sa(p/this.chunkSize|0)[r]}};h.prototype.rb=function(p){this.Sa=p};h.prototype.Ha=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),y,A=(y=p.getResponseHeader("Accept-Ranges"))&&"bytes"===y;
p=(y=p.getResponseHeader("Content-Encoding"))&&"gzip"===y;var m=1048576;A||(m=r);var u=this;u.rb(z=>{var F=z*m,L=(z+1)*m-1;L=Math.min(L,r-1);if("undefined"==typeof u.ga[z]){var Pb=u.ga;if(F>L)throw Error("invalid range ("+F+", "+L+") or no bytes requested!");if(L>r-1)throw Error("only "+r+" bytes available! programmer error!");var G=new XMLHttpRequest;G.open("GET",c,!1);r!==m&&G.setRequestHeader("Range","bytes="+F+"-"+L);G.responseType="arraybuffer";G.overrideMimeType&&G.overrideMimeType("text/plain; charset=x-user-defined");
G.send(null);if(!(200<=G.status&&300>G.status||304===G.status))throw Error("Couldn't load "+c+". Status: "+G.status);F=void 0!==G.response?new Uint8Array(G.response||[]):nb(G.responseText||"",!0);Pb[z]=F}if("undefined"==typeof u.ga[z])throw Error("doXHR failed!");return u.ga[z]});if(p||!r)m=r=1,m=r=this.Sa(0).length,ka("LazyFiles on gzip forces download of the whole file when length is accessed");this.ab=r;this.$a=m;this.ya=!0};if("undefined"!=typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new h;Object.defineProperties(l,{length:{get:function(){this.ya||this.Ha();return this.ab}},chunkSize:{get:function(){this.ya||this.Ha();return this.$a}}});l={xa:!1,i:l}}else l={xa:!1,url:c};var q=W.jb(a,b,l,e,g);l.i?q.i=l.i:l.url&&(q.i=null,q.url=l.url);Object.defineProperties(q,{m:{get:function(){return this.i.length}}});var t={};Object.keys(q.j).forEach(p=>{var r=q.j[p];t[p]=function(){W.Pa(q);return r.apply(null,arguments)}});t.read=(p,r,y,A,m)=>{W.Pa(q);p=p.node.i;if(m>=p.length)return 0;
A=Math.min(p.length-m,A);assert(0<=A);if(p.slice)for(var u=0;u<A;u++)r[y+u]=p[m+u];else for(u=0;u<A;u++)r[y+u]=p.get(m+u);return A};q.j=t;return q},Qb:(a,b,c,e,g,h,l,q,t,p)=>{function r(m){function u(z){p&&p();q||W.Ja(a,b,z,e,g,t);h&&h();Xa(A)}vb.Vb(m,y,u,()=>{l&&l();Xa(A)})||u(m)}var y=b?V(U(a,b)):a,A=Va("cp "+y);Wa(A);"string"==typeof c?rb(c,m=>r(m),l):r(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,Fa:()=>"EM_FS_"+window.location.pathname,Ga:20,
V:"FILE_DATA",ec:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=W.indexedDB();try{var g=e.open(W.Fa(),W.Ga)}catch(h){return c(h)}g.onupgradeneeded=()=>{ka("creating db");g.result.createObjectStore(W.V)};g.onsuccess=()=>{var h=g.result.transaction([W.V],"readwrite"),l=h.objectStore(W.V),q=0,t=0,p=a.length;a.forEach(r=>{r=l.put(W.pa(r).object.i,r);r.onsuccess=()=>{q++;q+t==p&&(0==t?b():c())};r.onerror=()=>{t++;q+t==p&&(0==t?b():c())}});h.onerror=c};g.onerror=c},Xb:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});
var e=W.indexedDB();try{var g=e.open(W.Fa(),W.Ga)}catch(h){return c(h)}g.onupgradeneeded=c;g.onsuccess=()=>{var h=g.result;try{var l=h.transaction([W.V],"readonly")}catch(y){c(y);return}var q=l.objectStore(W.V),t=0,p=0,r=a.length;a.forEach(y=>{var A=q.get(y);A.onsuccess=()=>{W.pa(y).exists&&W.unlink(y);W.Ja(hb(y),T(y),A.result,!0,!0,!0);t++;t+p==r&&(0==p?b():c())};A.onerror=()=>{p++;t+p==r&&(0==p?b():c())}});l.onerror=c};g.onerror=c},Kb:()=>{f("FS.absolutePath has been removed; use PATH_FS.resolve instead")},
Mb:()=>{f("FS.createFolder has been removed; use FS.mkdir instead")},Ob:()=>{f("FS.createLink has been removed; use FS.symlink instead")},Wb:()=>{f("FS.joinPath has been removed; use PATH.join instead")},$b:()=>{f("FS.mmapAlloc has been replaced by the top level function mmapAlloc")},fc:()=>{f("FS.standardizePath has been removed; use PATH.normalize instead")}};
function wb(a,b,c){if("/"===b[0])return b;if(-100===a)a=W.cwd();else{a=W.S(a);if(!a)throw new W.g(8);a=a.path}if(0==b.length){if(!c)throw new W.g(44);return a}return U(a,b)}
function xb(a,b,c){try{var e=a(b)}catch(g){if(g&&g.node&&gb(b)!==gb(W.K(g.node)))return-54;throw g;}K[c>>2]=e.dev;K[c+4>>2]=0;K[c+8>>2]=e.ino;K[c+12>>2]=e.mode;K[c+16>>2]=e.nlink;K[c+20>>2]=e.uid;K[c+24>>2]=e.gid;K[c+28>>2]=e.rdev;K[c+32>>2]=0;S=[e.size>>>0,(R=e.size,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];K[c+40>>2]=S[0];K[c+44>>2]=S[1];K[c+48>>2]=4096;K[c+52>>2]=e.blocks;K[c+56>>2]=e.atime.getTime()/1E3|0;K[c+60>>
2]=0;K[c+64>>2]=e.mtime.getTime()/1E3|0;K[c+68>>2]=0;K[c+72>>2]=e.ctime.getTime()/1E3|0;K[c+76>>2]=0;S=[e.ino>>>0,(R=e.ino,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];K[c+80>>2]=S[0];K[c+84>>2]=S[1];return 0}var Y=void 0;function yb(){assert(void 0!=Y);Y+=4;return K[Y-4>>2]}function Z(a){a=W.S(a);if(!a)throw new W.g(8);return a}
function zb(a,b,c){function e(t){return(t=t.toTimeString().match(/\(([A-Za-z ]+)\)$/))?t[1]:"GMT"}var g=(new Date).getFullYear(),h=new Date(g,0,1),l=new Date(g,6,1);g=h.getTimezoneOffset();var q=l.getTimezoneOffset();K[a>>2]=60*Math.max(g,q);K[b>>2]=Number(g!=q);a=e(h);b=e(l);a=Ca(a);b=Ca(b);q<g?(K[c>>2]=a,K[c+4>>2]=b):(K[c>>2]=b,K[c+4>>2]=a)}function Ab(a,b,c){Ab.cb||(Ab.cb=!0,zb(a,b,c))}function Bb(){void 0===Bb.start&&(Bb.start=Date.now());return 1E3*(Date.now()-Bb.start)|0}var Cb;
Cb=fa?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Db={};function Eb(){if(!Fb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Db)void 0===Db[b]?delete a[b]:a[b]=Db[b];var c=[];for(b in a)c.push(b+"="+a[b]);Fb=c}return Fb}var Fb;function Gb(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Hb(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}var Ib=[31,29,31,30,31,30,31,31,30,31,30,31],Jb=[31,28,31,30,31,30,31,31,30,31,30,31];function Kb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=(Gb(a.getFullYear())?Ib:Jb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Lb(a,b,c,e){a||(a=this);this.parent=a;this.s=a.s;this.aa=null;this.id=W.xb++;this.name=b;this.mode=c;this.h={};this.j={};this.rdev=e}Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},tb:{get:function(){return W.u(this.mode)}},xa:{get:function(){return W.Y(this.mode)}}});W.Ya=Lb;W.Eb();var vb;
tb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,
ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,
EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function nb(a,b){var c=Array(Ba(a)+1);a=Aa(a,c,0,c.length);b&&(c.length=a);return c}
var Nb={__syscall_faccessat:function(a,b,c,e){try{b=E(b);assert(0===e);b=wb(a,b);if(c&-8)var g=-28;else{var h=W.l(b,{C:!0}).node;h?(a="",c&4&&(a+="r"),c&2&&(a+="w"),c&1&&(a+="x"),g=a&&W.L(h,a)?-2:0):g=-44}return g}catch(l){if("undefined"==typeof W||!(l instanceof W.g))throw l;return-l.o}},__syscall_fcntl64:function(a,b,c){Y=c;try{var e=Z(a);switch(b){case 0:var g=yb();return 0>g?-28:W.open(e.path,e.flags,0,g).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return g=yb(),e.flags|=g,0;case 5:return g=
yb(),Fa[g+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return K[Mb()>>2]=28,-1;default:return-28}}catch(h){if("undefined"==typeof W||!(h instanceof W.g))throw h;return-h.o}},__syscall_fstat64:function(a,b){try{var c=Z(a);return xb(W.stat,c.path,b)}catch(e){if("undefined"==typeof W||!(e instanceof W.g))throw e;return-e.o}},__syscall_fstatat64:function(a,b,c,e){try{b=E(b);var g=e&256,h=e&4096;e&=-4353;assert(!e,e);b=wb(a,b,h);return xb(g?W.lstat:W.stat,b,c)}catch(l){if("undefined"==
typeof W||!(l instanceof W.g))throw l;return-l.o}},__syscall_getdents64:function(a,b,c){try{var e=Z(a);e.M||(e.M=W.readdir(e.path));a=0;for(var g=W.B(e,0,1),h=Math.floor(g/280);h<e.M.length&&a+280<=c;){var l=e.M[h];if("."===l){var q=e.node.id;var t=4}else if(".."===l)q=W.l(e.path,{parent:!0}).node.id,t=4;else{var p=W.F(e.node,l);q=p.id;t=W.Y(p.mode)?2:W.u(p.mode)?4:W.N(p.mode)?10:8}assert(q);S=[q>>>0,(R=q,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>
0))/4294967296)>>>0:0)];K[b+a>>2]=S[0];K[b+a+4>>2]=S[1];S=[280*(h+1)>>>0,(R=280*(h+1),1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];K[b+a+8>>2]=S[0];K[b+a+12>>2]=S[1];Fa[b+a+16>>1]=280;J[b+a+18>>0]=t;va(l,b+a+19,256);a+=280;h+=1}W.B(e,280*h,0);return a}catch(r){if("undefined"==typeof W||!(r instanceof W.g))throw r;return-r.o}},__syscall_ioctl:function(a,b,c){Y=c;try{var e=Z(a);switch(b){case 21509:case 21505:return e.tty?
0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var g=yb();return K[g>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return g=yb(),W.wa(e,b,g);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:f("bad ioctl syscall "+b)}}catch(h){if("undefined"==typeof W||!(h instanceof W.g))throw h;return-h.o}},__syscall_lstat64:function(a,b){try{return a=E(a),xb(W.lstat,a,b)}catch(c){if("undefined"==typeof W||!(c instanceof
W.g))throw c;return-c.o}},__syscall_open:function(a,b,c){Y=c;try{var e=E(a),g=c?yb():0;return W.open(e,b,g).fd}catch(h){if("undefined"==typeof W||!(h instanceof W.g))throw h;return-h.o}},__syscall_rename:function(a,b){try{return a=E(a),b=E(b),W.rename(a,b),0}catch(c){if("undefined"==typeof W||!(c instanceof W.g))throw c;return-c.o}},__syscall_rmdir:function(a){try{return a=E(a),W.rmdir(a),0}catch(b){if("undefined"==typeof W||!(b instanceof W.g))throw b;return-b.o}},__syscall_stat64:function(a,b){try{return a=
E(a),xb(W.stat,a,b)}catch(c){if("undefined"==typeof W||!(c instanceof W.g))throw c;return-c.o}},__syscall_unlink:function(a){try{return a=E(a),W.unlink(a),0}catch(b){if("undefined"==typeof W||!(b instanceof W.g))throw b;return-b.o}},_gmtime_js:function(a,b){a=new Date(1E3*K[a>>2]);K[b>>2]=a.getUTCSeconds();K[b+4>>2]=a.getUTCMinutes();K[b+8>>2]=a.getUTCHours();K[b+12>>2]=a.getUTCDate();K[b+16>>2]=a.getUTCMonth();K[b+20>>2]=a.getUTCFullYear()-1900;K[b+24>>2]=a.getUTCDay();K[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),
0,1,0,0,0,0))/864E5|0},_localtime_js:function(a,b){a=new Date(1E3*K[a>>2]);K[b>>2]=a.getSeconds();K[b+4>>2]=a.getMinutes();K[b+8>>2]=a.getHours();K[b+12>>2]=a.getDate();K[b+16>>2]=a.getMonth();K[b+20>>2]=a.getFullYear()-1900;K[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);K[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;K[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();K[b+32>>2]=(e!=c&&a.getTimezoneOffset()==Math.min(c,
e))|0},_mktime_js:function(a){var b=new Date(K[a+20>>2]+1900,K[a+16>>2],K[a+12>>2],K[a+8>>2],K[a+4>>2],K[a>>2],0),c=K[a+32>>2],e=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),h=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),l=g.getTimezoneOffset(),q=Math.min(l,h);0>c?K[a+32>>2]=Number(h!=l&&q==e):0<c!=(q==e)&&(h=Math.max(l,h),b.setTime(b.getTime()+6E4*((0<c?q:h)-e)));K[a+24>>2]=b.getDay();K[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;K[a>>2]=b.getSeconds();K[a+4>>2]=b.getMinutes();K[a+
8>>2]=b.getHours();K[a+12>>2]=b.getDate();K[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},_tzset_js:Ab,abort:function(){f("native code called abort()")},clock:Bb,clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Cb();else return K[Mb()>>2]=28,-1;K[b>>2]=a/1E3|0;K[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_get_now:Cb,emscripten_memcpy_big:function(a,b,c){I.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){var b=I.length;a>>>=0;assert(a>b);if(2147483648<a)return B("Cannot enlarge memory, asked to go up to "+
a+" bytes, but the limit is 2147483648 bytes!"),!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var g=Math;e=Math.max(a,e);g=g.min.call(g,2147483648,e+(65536-e%65536)%65536);e=Cb();a:{var h=g;try{qa.grow(h-Ea.byteLength+65535>>>16);Ha();var l=1;break a}catch(q){B("emscripten_realloc_buffer: Attempted to grow heap from "+Ea.byteLength+" bytes to "+h+" bytes, but got error: "+q)}l=void 0}h=Cb();ka("Heap resize call from "+b+" to "+g+" took "+(h-e)+" msecs. Success: "+!!l);if(l)return!0}B("Failed to grow the heap from "+
b+" bytes to "+g+" bytes, not enough memory!");return!1},environ_get:function(a,b){var c=0;Eb().forEach(function(e,g){var h=b+c;g=K[a+4*g>>2]=h;for(h=0;h<e.length;++h)assert(e.charCodeAt(h)===(e.charCodeAt(h)&255)),J[g++>>0]=e.charCodeAt(h);J[g>>0]=0;c+=e.length+1});return 0},environ_sizes_get:function(a,b){var c=Eb();K[a>>2]=c.length;var e=0;c.forEach(function(g){e+=g.length+1});K[b>>2]=e;return 0},fd_close:function(a){try{var b=Z(a);W.close(b);return 0}catch(c){if("undefined"==typeof W||!(c instanceof
W.g))throw c;return c.o}},fd_fdstat_get:function(a,b){try{var c=Z(a);J[b>>0]=c.tty?2:W.u(c.mode)?3:W.N(c.mode)?7:4;return 0}catch(e){if("undefined"==typeof W||!(e instanceof W.g))throw e;return e.o}},fd_read:function(a,b,c,e){try{a:{for(var g=Z(a),h=a=0;h<c;h++){var l=K[b+(8*h+4)>>2],q=W.read(g,J,K[b+8*h>>2],l,void 0);if(0>q){var t=-1;break a}a+=q;if(q<l)break}t=a}K[e>>2]=t;return 0}catch(p){if("undefined"==typeof W||!(p instanceof W.g))throw p;return p.o}},fd_seek:function(a,b,c,e,g){try{var h=Z(a);
a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;W.B(h,a,e);S=[h.position>>>0,(R=h.position,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];K[g>>2]=S[0];K[g+4>>2]=S[1];h.M&&0===a&&0===e&&(h.M=null);return 0}catch(l){if("undefined"==typeof W||!(l instanceof W.g))throw l;return l.o}},fd_write:function(a,b,c,e){try{a:{for(var g=Z(a),h=a=0;h<c;h++){var l=W.write(g,J,K[b+8*h>>2],K[b+(8*h+4)>>2],void 0);
if(0>l){var q=-1;break a}a+=l}q=a}K[e>>2]=q;return 0}catch(t){if("undefined"==typeof W||!(t instanceof W.g))throw t;return t.o}},gettimeofday:function(a){var b=Date.now();K[a>>2]=b/1E3|0;K[a+4>>2]=b%1E3*1E3|0;return 0},setTempRet0:function(){},strftime:function(a,b,c,e){function g(m,u,z){for(m="number"==typeof m?m.toString():m||"";m.length<u;)m=z[0]+m;return m}function h(m,u){return g(m,u,"0")}function l(m,u){function z(L){return 0>L?-1:0<L?1:0}var F;0===(F=z(m.getFullYear()-u.getFullYear()))&&0===
(F=z(m.getMonth()-u.getMonth()))&&(F=z(m.getDate()-u.getDate()));return F}function q(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function t(m){m=Kb(new Date(m.A+1900,0,1),m.na);var u=new Date(m.getFullYear()+1,0,4),z=q(new Date(m.getFullYear(),
0,4));u=q(u);return 0>=l(z,m)?0>=l(u,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var p=K[e+40>>2];e={Hb:K[e>>2],Gb:K[e+4>>2],la:K[e+8>>2],fa:K[e+12>>2],U:K[e+16>>2],A:K[e+20>>2],ma:K[e+24>>2],na:K[e+28>>2],hc:K[e+32>>2],Fb:K[e+36>>2],Ib:p?E(p):""};c=E(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d",
"%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in p)c=c.replace(new RegExp(r,"g"),p[r]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");p={"%a":function(m){return y[m.ma].substring(0,3)},"%A":function(m){return y[m.ma]},"%b":function(m){return A[m.U].substring(0,3)},"%B":function(m){return A[m.U]},
"%C":function(m){return h((m.A+1900)/100|0,2)},"%d":function(m){return h(m.fa,2)},"%e":function(m){return g(m.fa,2," ")},"%g":function(m){return t(m).toString().substring(2)},"%G":function(m){return t(m)},"%H":function(m){return h(m.la,2)},"%I":function(m){m=m.la;0==m?m=12:12<m&&(m-=12);return h(m,2)},"%j":function(m){return h(m.fa+Hb(Gb(m.A+1900)?Ib:Jb,m.U-1),3)},"%m":function(m){return h(m.U+1,2)},"%M":function(m){return h(m.Gb,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.la&&12>
m.la?"AM":"PM"},"%S":function(m){return h(m.Hb,2)},"%t":function(){return"\t"},"%u":function(m){return m.ma||7},"%U":function(m){var u=new Date(m.A+1900,0,1),z=0===u.getDay()?u:Kb(u,7-u.getDay());m=new Date(m.A+1900,m.U,m.fa);return 0>l(z,m)?h(Math.ceil((31-z.getDate()+(Hb(Gb(m.getFullYear())?Ib:Jb,m.getMonth()-1)-31)+m.getDate())/7),2):0===l(z,u)?"01":"00"},"%V":function(m){var u=new Date(m.A+1901,0,4),z=q(new Date(m.A+1900,0,4));u=q(u);var F=Kb(new Date(m.A+1900,0,1),m.na);return 0>l(F,z)?"53":
0>=l(u,F)?"01":h(Math.ceil((z.getFullYear()<m.A+1900?m.na+32-z.getDate():m.na+1-z.getDate())/7),2)},"%w":function(m){return m.ma},"%W":function(m){var u=new Date(m.A,0,1),z=1===u.getDay()?u:Kb(u,0===u.getDay()?1:7-u.getDay()+1);m=new Date(m.A+1900,m.U,m.fa);return 0>l(z,m)?h(Math.ceil((31-z.getDate()+(Hb(Gb(m.getFullYear())?Ib:Jb,m.getMonth()-1)-31)+m.getDate())/7),2):0===l(z,u)?"01":"00"},"%y":function(m){return(m.A+1900).toString().substring(2)},"%Y":function(m){return m.A+1900},"%z":function(m){m=
m.Fb;var u=0<=m;m=Math.abs(m)/60;return(u?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Ib},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(r in p)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),p[r](e)));c=c.replace(/\0\0/g,"%");r=nb(c,!1);if(r.length>b)return 0;wa(r,a);return r.length-1}};
(function(){function a(h){d.asm=h.exports;qa=d.asm.memory;assert(qa,"memory not found in wasm exports");Ha();Ja=d.asm.__indirect_function_table;assert(Ja,"table not found in wasm exports");Qa.unshift(d.asm.__wasm_call_ctors);Xa("wasm-instantiate")}function b(h){assert(d===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;a(h.instance)}function c(h){return ab().then(function(l){return WebAssembly.instantiate(l,e)}).then(function(l){return l}).then(h,
function(l){B("failed to asynchronously prepare wasm: "+l);P.startsWith("file://")&&B("warning: Loading from a file URI ("+P+") is not supported in most browsers. See https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing");f(l)})}var e={env:Nb,wasi_snapshot_preview1:Nb};Wa("wasm-instantiate");var g=d;if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(h){return B("Module.instantiateWasm callback failed with error: "+
h),!1}(function(){return pa||"function"!=typeof WebAssembly.instantiateStreaming||Ya()||P.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(P,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,e).then(b,function(l){B("wasm streaming compile failed: "+l);B("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();d.___wasm_call_ctors=Q("__wasm_call_ctors");var Da=d._malloc=Q("malloc");d._decode=Q("decode");
d._open_audio_decode=Q("open_audio_decode");d._audio_decode=Q("audio_decode");d._close_audio_decode=Q("close_audio_decode");var Mb=d.___errno_location=Q("__errno_location"),ub=d.___stdio_exit=Q("__stdio_exit"),qb=d._emscripten_builtin_memalign=Q("emscripten_builtin_memalign"),Ob=d._emscripten_stack_init=function(){return(Ob=d._emscripten_stack_init=d.asm.emscripten_stack_init).apply(null,arguments)};
d._emscripten_stack_get_free=function(){return(d._emscripten_stack_get_free=d.asm.emscripten_stack_get_free).apply(null,arguments)};d._emscripten_stack_get_base=function(){return(d._emscripten_stack_get_base=d.asm.emscripten_stack_get_base).apply(null,arguments)};var La=d._emscripten_stack_get_end=function(){return(La=d._emscripten_stack_get_end=d.asm.emscripten_stack_get_end).apply(null,arguments)},xa=d.stackSave=Q("stackSave"),ya=d.stackRestore=Q("stackRestore"),ua=d.stackAlloc=Q("stackAlloc");
d.dynCall_jiji=Q("dynCall_jiji");d.dynCall_iiiji=Q("dynCall_iiiji");d.dynCall_jiiij=Q("dynCall_jiiij");d.dynCall_jiiji=Q("dynCall_jiiji");d.dynCall_viiijj=Q("dynCall_viiijj");d.dynCall_jij=Q("dynCall_jij");d.dynCall_jii=Q("dynCall_jii");D("intArrayFromString",!1);D("intArrayToString",!1);D("ccall",!1);d.cwrap=function(a,b,c){return function(){return ta(a,b,c,arguments)}};D("setValue",!1);D("getValue",!1);D("allocate",!1);D("UTF8ArrayToString",!1);D("UTF8ToString",!1);D("stringToUTF8Array",!1);
D("stringToUTF8",!1);D("lengthBytesUTF8",!1);D("stackTrace",!1);D("addOnPreRun",!1);D("addOnInit",!1);D("addOnPreMain",!1);D("addOnExit",!1);D("addOnPostRun",!1);D("writeStringToMemory",!1);D("writeArrayToMemory",!1);D("writeAsciiToMemory",!1);D("addRunDependency",!0);D("removeRunDependency",!0);D("FS_createFolder",!1);D("FS_createPath",!0);D("FS_createDataFile",!0);D("FS_createPreloadedFile",!0);D("FS_createLazyFile",!0);D("FS_createLink",!1);D("FS_createDevice",!0);D("FS_unlink",!0);
D("getLEB",!1);D("getFunctionTables",!1);D("alignFunctionTables",!1);D("registerFunctions",!1);D("addFunction",!1);D("removeFunction",!1);D("getFuncWrapper",!1);D("prettyPrint",!1);D("dynCall",!1);D("getCompilerSetting",!1);D("print",!1);D("printErr",!1);D("getTempRet0",!1);D("setTempRet0",!1);D("callMain",!1);D("abort",!1);D("keepRuntimeAlive",!1);D("zeroMemory",!1);D("stringToNewUTF8",!1);D("emscripten_realloc_buffer",!1);D("ENV",!1);D("withStackSave",!1);D("ERRNO_CODES",!1);
D("ERRNO_MESSAGES",!1);D("setErrNo",!1);D("inetPton4",!1);D("inetNtop4",!1);D("inetPton6",!1);D("inetNtop6",!1);D("readSockaddr",!1);D("writeSockaddr",!1);D("DNS",!1);D("getHostByName",!1);D("Protocols",!1);D("Sockets",!1);D("getRandomDevice",!1);D("traverseStack",!1);D("convertFrameToPC",!1);D("UNWIND_CACHE",!1);D("saveInUnwindCache",!1);D("convertPCtoSourceLocation",!1);D("readAsmConstArgsArray",!1);D("readAsmConstArgs",!1);D("mainThreadEM_ASM",!1);D("jstoi_q",!1);D("jstoi_s",!1);
D("getExecutableName",!1);D("listenOnce",!1);D("autoResumeAudioContext",!1);D("dynCallLegacy",!1);D("getDynCaller",!1);D("dynCall",!1);D("callRuntimeCallbacks",!1);D("wasmTableMirror",!1);D("setWasmTableEntry",!1);D("getWasmTableEntry",!1);D("handleException",!1);D("runtimeKeepalivePush",!1);D("runtimeKeepalivePop",!1);D("callUserCallback",!1);D("maybeExit",!1);D("safeSetTimeout",!1);D("asmjsMangle",!1);D("asyncLoad",!1);D("alignMemory",!1);D("mmapAlloc",!1);D("reallyNegative",!1);D("unSign",!1);
D("reSign",!1);D("formatString",!1);D("PATH",!1);D("PATH_FS",!1);D("SYSCALLS",!1);D("getSocketFromFD",!1);D("getSocketAddress",!1);D("JSEvents",!1);D("registerKeyEventCallback",!1);D("specialHTMLTargets",!1);D("maybeCStringToJsString",!1);D("findEventTarget",!1);D("findCanvasEventTarget",!1);D("getBoundingClientRect",!1);D("fillMouseEventData",!1);D("registerMouseEventCallback",!1);D("registerWheelEventCallback",!1);D("registerUiEventCallback",!1);D("registerFocusEventCallback",!1);
D("fillDeviceOrientationEventData",!1);D("registerDeviceOrientationEventCallback",!1);D("fillDeviceMotionEventData",!1);D("registerDeviceMotionEventCallback",!1);D("screenOrientation",!1);D("fillOrientationChangeEventData",!1);D("registerOrientationChangeEventCallback",!1);D("fillFullscreenChangeEventData",!1);D("registerFullscreenChangeEventCallback",!1);D("registerRestoreOldStyle",!1);D("hideEverythingExceptGivenElement",!1);D("restoreHiddenElements",!1);D("setLetterbox",!1);
D("currentFullscreenStrategy",!1);D("restoreOldWindowedStyle",!1);D("softFullscreenResizeWebGLRenderTarget",!1);D("doRequestFullscreen",!1);D("fillPointerlockChangeEventData",!1);D("registerPointerlockChangeEventCallback",!1);D("registerPointerlockErrorEventCallback",!1);D("requestPointerLock",!1);D("fillVisibilityChangeEventData",!1);D("registerVisibilityChangeEventCallback",!1);D("registerTouchEventCallback",!1);D("fillGamepadEventData",!1);D("registerGamepadEventCallback",!1);
D("registerBeforeUnloadEventCallback",!1);D("fillBatteryEventData",!1);D("battery",!1);D("registerBatteryEventCallback",!1);D("setCanvasElementSize",!1);D("getCanvasElementSize",!1);D("demangle",!1);D("demangleAll",!1);D("jsStackTrace",!1);D("stackTrace",!1);D("getEnvStrings",!1);D("checkWasiClock",!1);D("writeI53ToI64",!1);D("writeI53ToI64Clamped",!1);D("writeI53ToI64Signaling",!1);D("writeI53ToU64Clamped",!1);D("writeI53ToU64Signaling",!1);D("readI53FromI64",!1);D("readI53FromU64",!1);
D("convertI32PairToI53",!1);D("convertU32PairToI53",!1);D("setImmediateWrapped",!1);D("clearImmediateWrapped",!1);D("polyfillSetImmediate",!1);D("uncaughtExceptionCount",!1);D("exceptionLast",!1);D("exceptionCaught",!1);D("ExceptionInfo",!1);D("CatchInfo",!1);D("exception_addRef",!1);D("exception_decRef",!1);D("Browser",!1);D("funcWrappers",!1);D("getFuncWrapper",!1);D("setMainLoop",!1);D("wget",!1);D("FS",!1);D("MEMFS",!1);D("TTY",!1);D("PIPEFS",!1);D("SOCKFS",!1);D("_setNetworkCallback",!1);
D("tempFixedLengthArray",!1);D("miniTempWebGLFloatBuffers",!1);D("heapObjectForWebGLType",!1);D("heapAccessShiftForWebGLHeap",!1);D("GL",!1);D("emscriptenWebGLGet",!1);D("computeUnpackAlignedImageSize",!1);D("emscriptenWebGLGetTexPixelData",!1);D("emscriptenWebGLGetUniform",!1);D("webglGetUniformLocation",!1);D("webglPrepareUniformLocationsBeforeFirstUse",!1);D("webglGetLeftBracePos",!1);D("emscriptenWebGLGetVertexAttrib",!1);D("writeGLArray",!1);D("AL",!1);D("SDL_unicode",!1);
D("SDL_ttfContext",!1);D("SDL_audio",!1);D("SDL",!1);D("SDL_gfx",!1);D("GLUT",!1);D("EGL",!1);D("GLFW_Window",!1);D("GLFW",!1);D("GLEW",!1);D("IDBStore",!1);D("runAndAbortIfError",!1);D("warnOnce",!1);D("stackSave",!1);D("stackRestore",!1);D("stackAlloc",!1);D("AsciiToString",!1);D("stringToAscii",!1);D("UTF16ToString",!1);D("stringToUTF16",!1);D("lengthBytesUTF16",!1);D("UTF32ToString",!1);D("stringToUTF32",!1);D("lengthBytesUTF32",!1);D("allocateUTF8",!1);D("allocateUTF8OnStack",!1);
d.writeStackCookie=Ka;d.checkStackCookie=Ma;oa("ALLOC_NORMAL");oa("ALLOC_STACK");var Qb;Ua=function Rb(){Qb||Sb();Qb||(Ua=Rb)};
function Sb(){function a(){if(!Qb&&(Qb=!0,d.calledRun=!0,!ra)){Ma();assert(!Sa);Sa=!0;d.noFSInit||W.X.ha||W.X();W.Va=!1;bb(Qa);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();assert(!d._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');Ma();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Ra.unshift(b)}bb(Ra)}}if(!(0<M)){Ob();Ka();if(d.preRun)for("function"==typeof d.preRun&&
(d.preRun=[d.preRun]);d.preRun.length;)Ta();bb(Pa);0<M||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a(),Ma())}}d.run=Sb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();Sb();self.FS=W;


  return createFFmepgModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmepgModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmepgModule; });
else if (typeof exports === 'object')
  exports["createFFmepgModule"] = createFFmepgModule;
