
var createFFmepgModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(createFFmepgModule) {
  createFFmepgModule = createFFmepgModule || {};


var d;d||(d=typeof createFFmepgModule !== 'undefined' ? createFFmepgModule : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});Object.getOwnPropertyDescriptor(d.ready,"_decode")||(Object.defineProperty(d.ready,"_decode",{configurable:!0,get:function(){f("You are getting _decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_decode",{configurable:!0,set:function(){f("You are setting _decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_encode")||(Object.defineProperty(d.ready,"_encode",{configurable:!0,get:function(){f("You are getting _encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_encode",{configurable:!0,set:function(){f("You are setting _encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_open_audio_decode")||(Object.defineProperty(d.ready,"_open_audio_decode",{configurable:!0,get:function(){f("You are getting _open_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_open_audio_decode",{configurable:!0,set:function(){f("You are setting _open_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_audio_decode")||(Object.defineProperty(d.ready,"_audio_decode",{configurable:!0,get:function(){f("You are getting _audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_audio_decode",{configurable:!0,set:function(){f("You are setting _audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_close_audio_decode")||(Object.defineProperty(d.ready,"_close_audio_decode",{configurable:!0,get:function(){f("You are getting _close_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_close_audio_decode",{configurable:!0,set:function(){f("You are setting _close_audio_decode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_open_audio_encode")||(Object.defineProperty(d.ready,"_open_audio_encode",{configurable:!0,get:function(){f("You are getting _open_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_open_audio_encode",{configurable:!0,set:function(){f("You are setting _open_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_audio_encode")||(Object.defineProperty(d.ready,"_audio_encode",{configurable:!0,get:function(){f("You are getting _audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_audio_encode",{configurable:!0,set:function(){f("You are setting _audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"_close_audio_encode")||(Object.defineProperty(d.ready,"_close_audio_encode",{configurable:!0,get:function(){f("You are getting _close_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"_close_audio_encode",{configurable:!0,set:function(){f("You are setting _close_audio_encode on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"___stdio_exit")||(Object.defineProperty(d.ready,"___stdio_exit",{configurable:!0,get:function(){f("You are getting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"___stdio_exit",{configurable:!0,set:function(){f("You are setting ___stdio_exit on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(d.ready,"onRuntimeInitialized")||(Object.defineProperty(d.ready,"onRuntimeInitialized",{configurable:!0,get:function(){f("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(d.ready,"onRuntimeInitialized",{configurable:!0,set:function(){f("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var ca=Object.assign({},d),da="./this.program",ea="object"==typeof window,k="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ia=!ea&&!ha&&!k;if(d.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var m="",t,u,v,fs,ja,ka;
if(ha){if("object"!=typeof process||"function"!=typeof require)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");m=k?require("path").dirname(m)+"/":__dirname+"/";ka=()=>{ja||(fs=require("fs"),ja=require("path"))};t=function(a,b){ka();a=ja.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};v=a=>{a=t(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);
return a};u=(a,b,c)=>{ka();a=ja.normalize(a);fs.readFile(a,function(e,g){e?c(e):b(g.buffer)})};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",function(a){throw a;});d.inspect=function(){return"[Emscripten Module object]"}}else if(ia){if("object"==typeof process&&"function"===typeof require||"object"==typeof window||"function"==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");
"undefined"!=typeof read&&(t=function(a){return read(a)});v=function(a){if("function"==typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"==typeof a);return a};u=function(a,b){setTimeout(()=>b(v(a)),0)};"undefined"!=typeof print&&("undefined"==typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!=typeof printErr?printErr:print)}else if(ea||k){k?m=self.location.href:"undefined"!=typeof document&&document.currentScript&&(m=document.currentScript.src);
_scriptDir&&(m=_scriptDir);0!==m.indexOf("blob:")?m=m.substr(0,m.replace(/[?#].*/,"").lastIndexOf("/")+1):m="";if("object"!=typeof window&&"function"!=typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};k&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",
a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});u=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)}}else throw Error("environment detection error");var la=d.print||console.log.bind(console),x=d.printErr||console.warn.bind(console);Object.assign(d,ca);ca=null;Object.getOwnPropertyDescriptor(d,"fetchSettings")&&f("`Module.fetchSettings` was supplied but `fetchSettings` not included in INCOMING_MODULE_JS_API");
y("arguments","arguments_");d.thisProgram&&(da=d.thisProgram);y("thisProgram","thisProgram");y("quit","quit_");assert("undefined"==typeof d.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof d.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof d.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");
assert("undefined"==typeof d.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");assert("undefined"==typeof d.read,"Module.read option was removed (modify read_ in JS)");assert("undefined"==typeof d.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");assert("undefined"==typeof d.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");assert("undefined"==typeof d.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");
assert("undefined"==typeof d.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");y("read","read_");y("readAsync","readAsync");y("readBinary","readBinary");y("setWindowTitle","setWindowTitle");assert(!ia,"shell environment detected but not enabled at build time.  Add 'shell' to `-s ENVIRONMENT` to enable.");function ma(a){na||(na={});na[a]||(na[a]=1,x(a))}var na;
function y(a,b){Object.getOwnPropertyDescriptor(d,a)||Object.defineProperty(d,a,{configurable:!0,get:function(){f("Module."+a+" has been replaced with plain "+b+" (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}})}
function oa(a,b){a="'"+a+"' was not exported. add it to EXPORTED_RUNTIME_METHODS (see the FAQ)";b&&(a+=". Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you");return a}function pa(a){Object.getOwnPropertyDescriptor(d,a)||Object.defineProperty(d,a,{configurable:!0,get:function(){f(oa(a,!1))}})}function C(a,b){Object.getOwnPropertyDescriptor(d,a)||(d[a]=()=>f(oa(a,b)))}var qa;d.wasmBinary&&(qa=d.wasmBinary);y("wasmBinary","wasmBinary");
var noExitRuntime=d.noExitRuntime||!0;y("noExitRuntime","noExitRuntime");"object"!=typeof WebAssembly&&f("no native wasm support detected");var ra,sa=!1;function assert(a,b){a||f("Assertion failed"+(b?": "+b:""))}function ta(a){var b=d["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function ua(a,b,c,e){var g={string:function(n){var r=0;if(null!==n&&void 0!==n&&0!==n){var w=(n.length<<2)+1;r=va(w);wa(n,r,w)}return r},array:function(n){var r=va(n.length);assert(0<=n.length,"writeArrayToMemory array must have a length (should be an array or typed array)");D.set(n,r);return r}};a=ta(a);var h=[],l=0;assert("array"!==b,'Return type should not be "array".');if(e)for(var p=0;p<e.length;p++){var q=g[c[p]];q?(0===l&&(l=xa()),h[p]=q(e[p])):h[p]=e[p]}c=a.apply(null,h);return c=function(n){0!==
l&&ya(l);return"string"===b?F(n):"boolean"===b?!!n:n}(c)}var za="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function G(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&za)return za.decode(a.subarray(b,c));for(e="";b<c;){var g=a[b++];if(g&128){var h=a[b++]&63;if(192==(g&224))e+=String.fromCharCode((g&31)<<6|h);else{var l=a[b++]&63;224==(g&240)?g=(g&15)<<12|h<<6|l:(240!=(g&248)&&ma("Invalid UTF-8 leading byte 0x"+g.toString(16)+" encountered when deserializing a UTF-8 string in wasm memory to a JS string!"),g=(g&7)<<18|h<<12|l<<6|a[b++]&63);65536>g?e+=String.fromCharCode(g):(g-=65536,e+=
String.fromCharCode(55296|g>>10,56320|g&1023))}}else e+=String.fromCharCode(g)}return e}function F(a){return a?G(H,a,void 0):""}
function Aa(a,b,c,e){if(!(0<e))return 0;var g=c;e=c+e-1;for(var h=0;h<a.length;++h){var l=a.charCodeAt(h);if(55296<=l&&57343>=l){var p=a.charCodeAt(++h);l=65536+((l&1023)<<10)|p&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;1114111<l&&ma("Invalid Unicode code point 0x"+l.toString(16)+" encountered when serializing a JS string to a UTF-8 string in wasm memory! (Valid unicode code points should be in range 0-0x10FFFF).");
b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-g}function wa(a,b,c){assert("number"==typeof c,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");Aa(a,H,b,c)}function Ba(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!=typeof TextDecoder&&new TextDecoder("utf-16le");
function Ca(a){var b=Ba(a)+1,c=Da(b);c&&Aa(a,D,c,b);return c}var Ea,D,H,Fa,I,Ga;function Ha(){var a=ra.buffer;Ea=a;d.HEAP8=D=new Int8Array(a);d.HEAP16=Fa=new Int16Array(a);d.HEAP32=I=new Int32Array(a);d.HEAPU8=H=new Uint8Array(a);d.HEAPU16=new Uint16Array(a);d.HEAPU32=Ga=new Uint32Array(a);d.HEAPF32=new Float32Array(a);d.HEAPF64=new Float64Array(a)}d.TOTAL_STACK&&assert(5242880===d.TOTAL_STACK,"the stack size can no longer be determined at runtime");var Ia=d.INITIAL_MEMORY||16777216;
y("INITIAL_MEMORY","INITIAL_MEMORY");assert(5242880<=Ia,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+Ia+"! (TOTAL_STACK=5242880)");assert("undefined"!=typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!=Int32Array.prototype.subarray&&void 0!=Int32Array.prototype.set,"JS engine does not provide full typed array support");assert(!d.wasmMemory,"Use of `wasmMemory` detected.  Use -s IMPORTED_MEMORY to define wasmMemory externally");assert(16777216==Ia,"Detected runtime INITIAL_MEMORY setting.  Use -s IMPORTED_MEMORY to define wasmMemory dynamically");
var Ja;function Ka(){var a=La();assert(0==(a&3));I[a+4>>2]=34821223;I[a+8>>2]=2310721022;I[0]=1668509029}function Ma(){if(!sa){var a=La(),b=Ga[a+4>>2];a=Ga[a+8>>2];34821223==b&&2310721022==a||f("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+a.toString(16)+" 0x"+b.toString(16));1668509029!==I[0]&&f("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var Na=new Int16Array(1),Oa=new Int8Array(Na.buffer);
Na[0]=25459;if(115!==Oa[0]||99!==Oa[1])throw"Runtime error: expected the system to be little-endian! (Run with -s SUPPORT_BIG_ENDIAN=1 to bypass)";var Pa=[],Qa=[],Ra=[],Sa=!1;function Ta(){var a=d.preRun.shift();Pa.unshift(a)}assert(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
assert(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");assert(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var J=0,K=null,Ua=null,M={};function Va(a){for(var b=a;;){if(!M[a])return a;a=b+Math.random()}}
function Wa(a){J++;d.monitorRunDependencies&&d.monitorRunDependencies(J);a?(assert(!M[a]),M[a]=1,null===K&&"undefined"!=typeof setInterval&&(K=setInterval(function(){if(sa)clearInterval(K),K=null;else{var b=!1,c;for(c in M)b||(b=!0,x("still waiting on run dependencies:")),x("dependency: "+c);b&&x("(end of list)")}},1E4))):x("warning: run dependency added without ID")}
function Xa(a){J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);a?(assert(M[a]),delete M[a]):x("warning: run dependency removed without ID");0==J&&(null!==K&&(clearInterval(K),K=null),Ua&&(a=Ua,Ua=null,a()))}d.preloadedImages={};d.preloadedAudios={};function f(a){if(d.onAbort)d.onAbort(a);a="Aborted("+a+")";x(a);sa=!0;a=new WebAssembly.RuntimeError(a);ba(a);throw a;}function Ya(){return N.startsWith("data:application/octet-stream;base64,")}
function O(a){return function(){var b=d.asm;assert(Sa,"native function `"+a+"` called before runtime initialization");assert(!0,"native function `"+a+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");b[a]||assert(b[a],"exported native function `"+a+"` not found");return b[a].apply(null,arguments)}}var N;N="opus.wasm";if(!Ya()){var Za=N;N=d.locateFile?d.locateFile(Za,m):m+Za}
function $a(){var a=N;try{if(a==N&&qa)return new Uint8Array(qa);if(v)return v(a);throw"both async and sync fetching of the wasm failed";}catch(b){f(b)}}
function ab(){if(!qa&&(ea||k)){if("function"==typeof fetch&&!N.startsWith("file://"))return fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return $a()});if(u)return new Promise(function(a,b){u(N,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return $a()})}var P,Q;
function bb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.Jb;"number"==typeof c?void 0===b.ka?cb(c)():cb(c)(b.ka):c(void 0===b.ka?null:b.ka)}}}function db(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){ma("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return b===b?b:b+" ["+b+"]"})}var eb=[];
function cb(a){var b=eb[a];b||(a>=eb.length&&(eb.length=a+1),eb[a]=b=Ja.get(a));assert(Ja.get(a)==b,"JavaScript-side Wasm function table mirror is out of date!");return b}function fb(a,b){for(var c=0,e=a.length-1;0<=e;e--){var g=a[e];"."===g?a.splice(e,1):".."===g?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function gb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(e){return!!e}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function R(a){if("/"===a)return"/";a=gb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function S(a,b){return gb(a+"/"+b)}
function ib(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ha)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){f("no cryptographic support found for randomDevice. consider polyfilling it if you want to use something insecure like Math.random(), e.g. put this in a --pre-js: var crypto = { getRandomValues: function(array) { for (var i = 0; i < array.length; i++) array[i] = (Math.random()*256)|0 } };")}}
function T(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:U.cwd();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(e){return!!e}),!b).join("/");return(b?"/":"")+a||"."}
function jb(a,b){function c(l){for(var p=0;p<l.length&&""===l[p];p++);for(var q=l.length-1;0<=q&&""===l[q];q--);return p>q?[]:l.slice(p,q-p+1)}a=T(a).substr(1);b=T(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),g=e,h=0;h<e;h++)if(a[h]!==b[h]){g=h;break}e=[];for(h=g;h<a.length;h++)e.push("..");e=e.concat(b.slice(g));return e.join("/")}var kb=[];function lb(a,b){kb[a]={input:[],output:[],S:b};U.ya(a,mb)}
var mb={open:function(a){var b=kb[a.node.rdev];if(!b)throw new U.g(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.S.flush(a.tty)},flush:function(a){a.tty.S.flush(a.tty)},read:function(a,b,c,e){if(!a.tty||!a.tty.S.La)throw new U.g(60);for(var g=0,h=0;h<e;h++){try{var l=a.tty.S.La(a.tty)}catch(p){throw new U.g(29);}if(void 0===l&&0===g)throw new U.g(6);if(null===l||void 0===l)break;g++;b[c+h]=l}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,e){if(!a.tty||!a.tty.S.va)throw new U.g(60);
try{for(var g=0;g<e;g++)a.tty.S.va(a.tty,b[c+g])}catch(h){throw new U.g(29);}e&&(a.node.timestamp=Date.now());return g}},ob={La:function(a){if(!a.input.length){var b=null;if(ha){var c=Buffer.alloc(256),e=0;try{e=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(g){if(g.toString().includes("EOF"))e=0;else throw g;}0<e?b=c.slice(0,e).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b)}return a.input.shift()},va:function(a,b){null===b||10===b?(la(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(G(a.output,0)),a.output=[])}},pb={va:function(a,b){null===b||10===b?(x(G(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(x(G(a.output,0)),a.output=[])}},V={G:null,s:function(){return V.createNode(null,"/",16895,0)},createNode:function(a,
b,c,e){if(U.mb(c)||U.isFIFO(c))throw new U.g(63);V.G||(V.G={dir:{node:{C:V.h.C,v:V.h.v,lookup:V.h.lookup,H:V.h.H,rename:V.h.rename,unlink:V.h.unlink,rmdir:V.h.rmdir,readdir:V.h.readdir,symlink:V.h.symlink},stream:{A:V.j.A}},file:{node:{C:V.h.C,v:V.h.v},stream:{A:V.j.A,read:V.j.read,write:V.j.write,U:V.j.U,Y:V.j.Y,aa:V.j.aa}},link:{node:{C:V.h.C,v:V.h.v,readlink:V.h.readlink},stream:{}},Ca:{node:{C:V.h.C,v:V.h.v},stream:U.Za}});c=U.createNode(a,b,c,e);U.u(c.mode)?(c.h=V.G.dir.node,c.j=V.G.dir.stream,
c.i={}):U.isFile(c.mode)?(c.h=V.G.file.node,c.j=V.G.file.stream,c.m=0,c.i=null):U.M(c.mode)?(c.h=V.G.link.node,c.j=V.G.link.stream):U.W(c.mode)&&(c.h=V.G.Ca.node,c.j=V.G.Ca.stream);c.timestamp=Date.now();a&&(a.i[b]=c,a.timestamp=c.timestamp);return c},Kb:function(a){return a.i?a.i.subarray?a.i.subarray(0,a.m):new Uint8Array(a.i):new Uint8Array(0)},Ha:function(a,b){var c=a.i?a.i.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.i,a.i=new Uint8Array(b),0<a.m&&a.i.set(c.subarray(0,
a.m),0))},wb:function(a,b){if(a.m!=b)if(0==b)a.i=null,a.m=0;else{var c=a.i;a.i=new Uint8Array(b);c&&a.i.set(c.subarray(0,Math.min(b,a.m)));a.m=b}},h:{C:function(a){var b={};b.dev=U.W(a.mode)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;U.u(a.mode)?b.size=4096:U.isFile(a.mode)?b.size=a.m:U.M(a.mode)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Wa=4096;b.blocks=Math.ceil(b.size/b.Wa);return b},v:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&V.wb(a,b.size)},lookup:function(){throw U.na[44];},H:function(a,b,c,e){return V.createNode(a,b,c,e)},rename:function(a,b,c){if(U.u(a.mode)){try{var e=U.D(b,c)}catch(h){}if(e)for(var g in e.i)throw new U.g(55);}delete a.parent.i[a.name];a.parent.timestamp=Date.now();a.name=c;b.i[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.i[b];a.timestamp=Date.now()},rmdir:function(a,
b){var c=U.D(a,b),e;for(e in c.i)throw new U.g(55);delete a.i[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.i)a.i.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=V.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(!U.M(a.mode))throw new U.g(28);return a.link}},j:{read:function(a,b,c,e,g){var h=a.node.i;if(g>=a.node.m)return 0;a=Math.min(a.node.m-g,e);assert(0<=a);if(8<a&&h.subarray)b.set(h.subarray(g,g+a),c);else for(e=0;e<a;e++)b[c+
e]=h[g+e];return a},write:function(a,b,c,e,g,h){assert(!(b instanceof ArrayBuffer));b.buffer===D.buffer&&(h=!1);if(!e)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.i||a.i.subarray)){if(h)return assert(0===g,"canOwn must imply no weird position inside the file"),a.i=b.subarray(c,c+e),a.m=e;if(0===a.m&&0===g)return a.i=b.slice(c,c+e),a.m=e;if(g+e<=a.m)return a.i.set(b.subarray(c,c+e),g),e}V.Ha(a,g+e);if(a.i.subarray&&b.subarray)a.i.set(b.subarray(c,c+e),g);else for(h=0;h<e;h++)a.i[g+h]=
b[c+h];a.m=Math.max(a.m,g+e);return e},A:function(a,b,c){1===c?b+=a.position:2===c&&U.isFile(a.node.mode)&&(b+=a.node.m);if(0>b)throw new U.g(28);return b},U:function(a,b,c){V.Ha(a.node,b+c);a.node.m=Math.max(a.node.m,b+c)},Y:function(a,b,c,e,g,h){if(0!==b)throw new U.g(28);if(!U.isFile(a.node.mode))throw new U.g(43);a=a.node.i;if(h&2||a.buffer!==Ea){if(0<e||e+c<a.length)a.subarray?a=a.subarray(e,e+c):a=Array.prototype.slice.call(a,e,e+c);e=!0;assert(65536,"alignment argument is required");c=65536*
Math.ceil(c/65536);(h=qb(65536,c))?(H.fill(0,h,h+c),c=h):c=0;if(!c)throw new U.g(48);D.set(a,c)}else e=!1,c=a.byteOffset;return{Tb:c,Bb:e}},aa:function(a,b,c,e,g){if(!U.isFile(a.node.mode))throw new U.g(43);if(g&2)return 0;V.j.write(a,b,0,e,c,!1);return 0}}};function rb(a,b,c){var e=Va("al "+a);u(a,function(g){assert(g,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(g));e&&Xa(e)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});e&&Wa(e)}
var sb={0:"Success",1:"Arg list too long",2:"Permission denied",3:"Address already in use",4:"Address not available",5:"Address family not supported by protocol family",6:"No more processes",7:"Socket already connected",8:"Bad file number",9:"Trying to read unreadable message",10:"Mount device busy",11:"Operation canceled",12:"No children",13:"Connection aborted",14:"Connection refused",15:"Connection reset by peer",16:"File locking deadlock error",17:"Destination address required",18:"Math arg out of domain of func",
19:"Quota exceeded",20:"File exists",21:"Bad address",22:"File too large",23:"Host is unreachable",24:"Identifier removed",25:"Illegal byte sequence",26:"Connection already in progress",27:"Interrupted system call",28:"Invalid argument",29:"I/O error",30:"Socket is already connected",31:"Is a directory",32:"Too many symbolic links",33:"Too many open files",34:"Too many links",35:"Message too long",36:"Multihop attempted",37:"File or path name too long",38:"Network interface is not configured",39:"Connection reset by network",
40:"Network is unreachable",41:"Too many open files in system",42:"No buffer space available",43:"No such device",44:"No such file or directory",45:"Exec format error",46:"No record locks available",47:"The link has been severed",48:"Not enough core",49:"No message of desired type",50:"Protocol not available",51:"No space left on device",52:"Function not implemented",53:"Socket is not connected",54:"Not a directory",55:"Directory not empty",56:"State not recoverable",57:"Socket operation on non-socket",
59:"Not a typewriter",60:"No such device or address",61:"Value too large for defined data type",62:"Previous owner died",63:"Not super-user",64:"Broken pipe",65:"Protocol error",66:"Unknown protocol",67:"Protocol wrong type for socket",68:"Math result not representable",69:"Read only file system",70:"Illegal seek",71:"No such process",72:"Stale file handle",73:"Connection timed out",74:"Text file busy",75:"Cross-device link",100:"Device not a stream",101:"Bad font file fmt",102:"Invalid slot",103:"Invalid request code",
104:"No anode",105:"Block device required",106:"Channel number out of range",107:"Level 3 halted",108:"Level 3 reset",109:"Link number out of range",110:"Protocol driver not attached",111:"No CSI structure available",112:"Level 2 halted",113:"Invalid exchange",114:"Invalid request descriptor",115:"Exchange full",116:"No data (for no delay io)",117:"Timer expired",118:"Out of streams resources",119:"Machine is not on the network",120:"Package not installed",121:"The object is remote",122:"Advertise error",
123:"Srmount error",124:"Communication error on send",125:"Cross mount point (not really error)",126:"Given log. name not unique",127:"f.d. invalid for this operation",128:"Remote address changed",129:"Can   access a needed shared lib",130:"Accessing a corrupted shared lib",131:".lib section in a.out corrupted",132:"Attempting to link in too many libs",133:"Attempting to exec a shared library",135:"Streams pipe error",136:"Too many users",137:"Socket type not supported",138:"Not supported",139:"Protocol family not supported",
140:"Can't send after socket shutdown",141:"Too many references",142:"Host is down",148:"No medium (in tape drive)",156:"Level 2 not synchronized"},tb={},U={root:null,$:[],Fa:{},streams:[],rb:1,F:null,Ea:"/",ea:!1,Pa:!0,g:null,na:{},ib:null,ba:0,l:(a,b={})=>{a=T(U.cwd(),a);if(!a)return{path:"",node:null};var c={ma:!0,xa:0},e;for(e in c)void 0===b[e]&&(b[e]=c[e]);if(8<b.xa)throw new U.g(32);a=fb(a.split("/").filter(l=>!!l),!1);var g=U.root;c="/";for(e=0;e<a.length;e++){var h=e===a.length-1;if(h&&b.parent)break;
g=U.D(g,a[e]);c=S(c,a[e]);U.N(g)&&(!h||h&&b.ma)&&(g=g.Z.root);if(!h||b.B)for(h=0;U.M(g.mode);)if(g=U.readlink(c),c=T(hb(c),g),g=U.l(c,{xa:b.xa}).node,40<h++)throw new U.g(32);}return{path:c,node:g}},J:a=>{for(var b;;){if(U.fa(a))return a=a.s.Qa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},pa:(a,b)=>{for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%U.F.length},Na:a=>{var b=U.pa(a.parent.id,a.name);a.P=U.F[b];U.F[b]=a},Oa:a=>{var b=U.pa(a.parent.id,
a.name);if(U.F[b]===a)U.F[b]=a.P;else for(b=U.F[b];b;){if(b.P===a){b.P=a.P;break}b=b.P}},D:(a,b)=>{var c=U.ob(a);if(c)throw new U.g(c,a);for(c=U.F[U.pa(a.id,b)];c;c=c.P){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return U.lookup(a,b)},createNode:(a,b,c,e)=>{assert("object"==typeof a);a=new U.Sa(a,b,c,e);U.Na(a);return a},la:a=>{U.Oa(a)},fa:a=>a===a.parent,N:a=>!!a.Z,isFile:a=>32768===(a&61440),u:a=>16384===(a&61440),M:a=>40960===(a&61440),W:a=>8192===(a&61440),mb:a=>24576===(a&61440),isFIFO:a=>
4096===(a&61440),isSocket:a=>49152===(a&49152),jb:{r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},qb:a=>{var b=U.jb[a];if("undefined"==typeof b)throw Error("Unknown file open mode: "+a);return b},Ia:a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},K:(a,b)=>{if(U.Pa)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},ob:a=>{var b=U.K(a,"x");return b?b:a.h.lookup?0:2},ua:(a,b)=>{try{return U.D(a,b),20}catch(c){}return U.K(a,
"wx")},ga:(a,b,c)=>{try{var e=U.D(a,b)}catch(g){return g.o}if(a=U.K(a,"wx"))return a;if(c){if(!U.u(e.mode))return 54;if(U.fa(e)||U.J(e)===U.cwd())return 10}else if(U.u(e.mode))return 31;return 0},pb:(a,b)=>a?U.M(a.mode)?32:U.u(a.mode)&&("r"!==U.Ia(b)||b&512)?31:U.K(a,U.Ia(b)):44,Ta:4096,sb:(a=0,b=U.Ta)=>{for(;a<=b;a++)if(!U.streams[a])return a;throw new U.g(33);},R:a=>U.streams[a],gb:(a,b,c)=>{U.ia||(U.ia=function(){},U.ia.prototype={object:{get:function(){return this.node},set:function(e){this.node=
e}}});a=Object.assign(new U.ia,a);b=U.sb(b,c);a.fd=b;return U.streams[b]=a},$a:a=>{U.streams[a]=null},Za:{open:a=>{a.j=U.kb(a.node.rdev).j;a.j.open&&a.j.open(a)},A:()=>{throw new U.g(70);}},ta:a=>a>>8,Ob:a=>a&255,O:(a,b)=>a<<8|b,ya:(a,b)=>{U.Fa[a]={j:b}},kb:a=>U.Fa[a],Ka:a=>{var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.$)}return b},Ra:(a,b)=>{function c(l){assert(0<U.ba);U.ba--;return b(l)}function e(l){if(l){if(!e.hb)return e.hb=!0,c(l)}else++h>=g.length&&c(null)}"function"==
typeof a&&(b=a,a=!1);U.ba++;1<U.ba&&x("warning: "+U.ba+" FS.syncfs operations in flight at once, probably just doing extra work");var g=U.Ka(U.root.s),h=0;g.forEach(l=>{if(!l.type.Ra)return e(null);l.type.Ra(l,a,e)})},s:(a,b,c)=>{if("string"==typeof a)throw a;var e="/"===c,g=!c;if(e&&U.root)throw new U.g(10);if(!e&&!g){var h=U.l(c,{ma:!1});c=h.path;h=h.node;if(U.N(h))throw new U.g(10);if(!U.u(h.mode))throw new U.g(54);}b={type:a,Sb:b,Qa:c,$:[]};a=a.s(b);a.s=b;b.root=a;e?U.root=a:h&&(h.Z=b,h.s&&h.s.$.push(b));
return a},Xb:a=>{a=U.l(a,{ma:!1});if(!U.N(a.node))throw new U.g(28);a=a.node;var b=a.Z,c=U.Ka(b);Object.keys(U.F).forEach(e=>{for(e=U.F[e];e;){var g=e.P;c.includes(e.s)&&U.la(e);e=g}});a.Z=null;b=a.s.$.indexOf(b);assert(-1!==b);a.s.$.splice(b,1)},lookup:(a,b)=>a.h.lookup(a,b),H:(a,b,c)=>{var e=U.l(a,{parent:!0}).node;a=R(a);if(!a||"."===a||".."===a)throw new U.g(28);var g=U.ua(e,a);if(g)throw new U.g(g);if(!e.h.H)throw new U.g(63);return e.h.H(e,a,b,c)},create:(a,b)=>U.H(a,(void 0!==b?b:438)&4095|
32768,0),mkdir:(a,b)=>U.H(a,(void 0!==b?b:511)&1023|16384,0),Pb:(a,b)=>{a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{U.mkdir(c,b)}catch(g){if(20!=g.o)throw g;}}},ha:(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return U.H(a,b|8192,c)},symlink:(a,b)=>{if(!T(a))throw new U.g(44);var c=U.l(b,{parent:!0}).node;if(!c)throw new U.g(44);b=R(b);var e=U.ua(c,b);if(e)throw new U.g(e);if(!c.h.symlink)throw new U.g(63);return c.h.symlink(c,b,a)},rename:(a,b)=>{var c=hb(a),e=hb(b),g=
R(a),h=R(b);var l=U.l(a,{parent:!0});var p=l.node;l=U.l(b,{parent:!0});l=l.node;if(!p||!l)throw new U.g(44);if(p.s!==l.s)throw new U.g(75);var q=U.D(p,g);a=jb(a,e);if("."!==a.charAt(0))throw new U.g(28);a=jb(b,c);if("."!==a.charAt(0))throw new U.g(55);try{var n=U.D(l,h)}catch(r){}if(q!==n){b=U.u(q.mode);if(g=U.ga(p,g,b))throw new U.g(g);if(g=n?U.ga(l,h,b):U.ua(l,h))throw new U.g(g);if(!p.h.rename)throw new U.g(63);if(U.N(q)||n&&U.N(n))throw new U.g(10);if(l!==p&&(g=U.K(p,"w")))throw new U.g(g);U.Oa(q);
try{p.h.rename(q,l,h)}catch(r){throw r;}finally{U.Na(q)}}},rmdir:a=>{var b=U.l(a,{parent:!0}).node;a=R(a);var c=U.D(b,a),e=U.ga(b,a,!0);if(e)throw new U.g(e);if(!b.h.rmdir)throw new U.g(63);if(U.N(c))throw new U.g(10);b.h.rmdir(b,a);U.la(c)},readdir:a=>{a=U.l(a,{B:!0}).node;if(!a.h.readdir)throw new U.g(54);return a.h.readdir(a)},unlink:a=>{var b=U.l(a,{parent:!0}).node;if(!b)throw new U.g(44);a=R(a);var c=U.D(b,a),e=U.ga(b,a,!1);if(e)throw new U.g(e);if(!b.h.unlink)throw new U.g(63);if(U.N(c))throw new U.g(10);
b.h.unlink(b,a);U.la(c)},readlink:a=>{a=U.l(a).node;if(!a)throw new U.g(44);if(!a.h.readlink)throw new U.g(28);return T(U.J(a.parent),a.h.readlink(a))},stat:(a,b)=>{a=U.l(a,{B:!b}).node;if(!a)throw new U.g(44);if(!a.h.C)throw new U.g(63);return a.h.C(a)},lstat:a=>U.stat(a,!0),chmod:(a,b,c)=>{a="string"==typeof a?U.l(a,{B:!c}).node:a;if(!a.h.v)throw new U.g(63);a.h.v(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},lchmod:(a,b)=>{U.chmod(a,b,!0)},fchmod:(a,b)=>{a=U.R(a);if(!a)throw new U.g(8);U.chmod(a.node,
b)},chown:(a,b,c,e)=>{a="string"==typeof a?U.l(a,{B:!e}).node:a;if(!a.h.v)throw new U.g(63);a.h.v(a,{timestamp:Date.now()})},lchown:(a,b,c)=>{U.chown(a,b,c,!0)},fchown:(a,b,c)=>{a=U.R(a);if(!a)throw new U.g(8);U.chown(a.node,b,c)},truncate:(a,b)=>{if(0>b)throw new U.g(28);a="string"==typeof a?U.l(a,{B:!0}).node:a;if(!a.h.v)throw new U.g(63);if(U.u(a.mode))throw new U.g(31);if(!U.isFile(a.mode))throw new U.g(28);var c=U.K(a,"w");if(c)throw new U.g(c);a.h.v(a,{size:b,timestamp:Date.now()})},Ib:(a,b)=>
{a=U.R(a);if(!a)throw new U.g(8);if(0===(a.flags&2097155))throw new U.g(28);U.truncate(a.node,b)},Yb:(a,b,c)=>{a=U.l(a,{B:!0}).node;a.h.v(a,{timestamp:Math.max(b,c)})},open:(a,b,c,e,g)=>{if(""===a)throw new U.g(44);b="string"==typeof b?U.qb(b):b;c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var h=a;else{a=gb(a);try{h=U.l(a,{B:!(b&131072)}).node}catch(p){}}var l=!1;if(b&64)if(h){if(b&128)throw new U.g(20);}else h=U.H(a,c,0),l=!0;if(!h)throw new U.g(44);U.W(h.mode)&&(b&=-513);
if(b&65536&&!U.u(h.mode))throw new U.g(54);if(!l&&(c=U.pb(h,b)))throw new U.g(c);b&512&&U.truncate(h,0);b&=-131713;e=U.gb({node:h,path:U.J(h),flags:b,seekable:!0,position:0,j:h.j,zb:[],error:!1},e,g);e.j.open&&e.j.open(e);!d.logReadFiles||b&1||(U.wa||(U.wa={}),a in U.wa||(U.wa[a]=1));return e},close:a=>{if(U.X(a))throw new U.g(8);a.L&&(a.L=null);try{a.j.close&&a.j.close(a)}catch(b){throw b;}finally{U.$a(a.fd)}a.fd=null},X:a=>null===a.fd,A:(a,b,c)=>{if(U.X(a))throw new U.g(8);if(!a.seekable||!a.j.A)throw new U.g(70);
if(0!=c&&1!=c&&2!=c)throw new U.g(28);a.position=a.j.A(a,b,c);a.zb=[];return a.position},read:(a,b,c,e,g)=>{if(0>e||0>g)throw new U.g(28);if(U.X(a))throw new U.g(8);if(1===(a.flags&2097155))throw new U.g(8);if(U.u(a.node.mode))throw new U.g(31);if(!a.j.read)throw new U.g(28);var h="undefined"!=typeof g;if(!h)g=a.position;else if(!a.seekable)throw new U.g(70);b=a.j.read(a,b,c,e,g);h||(a.position+=b);return b},write:(a,b,c,e,g,h)=>{if(0>e||0>g)throw new U.g(28);if(U.X(a))throw new U.g(8);if(0===(a.flags&
2097155))throw new U.g(8);if(U.u(a.node.mode))throw new U.g(31);if(!a.j.write)throw new U.g(28);a.seekable&&a.flags&1024&&U.A(a,0,2);var l="undefined"!=typeof g;if(!l)g=a.position;else if(!a.seekable)throw new U.g(70);b=a.j.write(a,b,c,e,g,h);l||(a.position+=b);return b},U:(a,b,c)=>{if(U.X(a))throw new U.g(8);if(0>b||0>=c)throw new U.g(28);if(0===(a.flags&2097155))throw new U.g(8);if(!U.isFile(a.node.mode)&&!U.u(a.node.mode))throw new U.g(43);if(!a.j.U)throw new U.g(138);a.j.U(a,b,c)},Y:(a,b,c,e,
g,h)=>{if(0!==(g&2)&&0===(h&2)&&2!==(a.flags&2097155))throw new U.g(2);if(1===(a.flags&2097155))throw new U.g(2);if(!a.j.Y)throw new U.g(43);return a.j.Y(a,b,c,e,g,h)},aa:(a,b,c,e,g)=>a&&a.j.aa?a.j.aa(a,b,c,e,g):0,Rb:()=>0,qa:(a,b,c)=>{if(!a.j.qa)throw new U.g(59);return a.j.qa(a,b,c)},readFile:(a,b={})=>{b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,e=U.open(a,b.flags);a=U.stat(a).size;
var g=new Uint8Array(a);U.read(e,g,0,a,0);"utf8"===b.encoding?c=G(g,0):"binary"===b.encoding&&(c=g);U.close(e);return c},writeFile:(a,b,c={})=>{c.flags=c.flags||577;a=U.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(Ba(b)+1);b=Aa(b,e,0,e.length);U.write(a,e,0,b,void 0,c.Ya)}else if(ArrayBuffer.isView(b))U.write(a,b,0,b.byteLength,void 0,c.Ya);else throw Error("Unsupported data type");U.close(a)},cwd:()=>U.Ea,chdir:a=>{a=U.l(a,{B:!0});if(null===a.node)throw new U.g(44);if(!U.u(a.node.mode))throw new U.g(54);
var b=U.K(a.node,"x");if(b)throw new U.g(b);U.Ea=a.path},bb:()=>{U.mkdir("/tmp");U.mkdir("/home");U.mkdir("/home/web_user")},ab:()=>{U.mkdir("/dev");U.ya(U.O(1,3),{read:()=>0,write:(b,c,e,g)=>g});U.ha("/dev/null",U.O(1,3));lb(U.O(5,0),ob);lb(U.O(6,0),pb);U.ha("/dev/tty",U.O(5,0));U.ha("/dev/tty1",U.O(6,0));var a=ib();U.I("/dev","random",a);U.I("/dev","urandom",a);U.mkdir("/dev/shm");U.mkdir("/dev/shm/tmp")},eb:()=>{U.mkdir("/proc");var a=U.mkdir("/proc/self");U.mkdir("/proc/self/fd");U.s({s:()=>{var b=
U.createNode(a,"fd",16895,73);b.h={lookup:(c,e)=>{var g=U.R(+e);if(!g)throw new U.g(8);c={parent:null,s:{Qa:"fake"},h:{readlink:()=>g.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},fb:()=>{d.stdin?U.I("/dev","stdin",d.stdin):U.symlink("/dev/tty","/dev/stdin");d.stdout?U.I("/dev","stdout",null,d.stdout):U.symlink("/dev/tty","/dev/stdout");d.stderr?U.I("/dev","stderr",null,d.stderr):U.symlink("/dev/tty1","/dev/stderr");var a=U.open("/dev/stdin",0),b=U.open("/dev/stdout",1),c=U.open("/dev/stderr",
1);assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");assert(1===b.fd,"invalid handle for stdout ("+b.fd+")");assert(2===c.fd,"invalid handle for stderr ("+c.fd+")")},Ga:()=>{U.g||(U.g=function(a,b){this.node=b;this.xb=function(c){this.o=c;for(var e in tb)if(tb[e]===c){this.code=e;break}};this.xb(a);this.message=sb[a];this.stack&&(Object.defineProperty(this,"stack",{value:Error().stack,writable:!0}),this.stack=db(this.stack))},U.g.prototype=Error(),U.g.prototype.constructor=U.g,[44].forEach(a=>
{U.na[a]=new U.g(a);U.na[a].stack="<generic error, no stack>"}))},yb:()=>{U.Ga();U.F=Array(4096);U.s(V,{},"/");U.bb();U.ab();U.eb();U.ib={MEMFS:V}},V:(a,b,c)=>{assert(!U.V.ea,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");U.V.ea=!0;U.Ga();d.stdin=a||d.stdin;d.stdout=b||d.stdout;d.stderr=c||d.stderr;U.fb()},Ub:()=>{U.V.ea=!1;ub();for(var a=0;a<U.streams.length;a++){var b=
U.streams[a];b&&U.close(b)}},oa:(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Hb:(a,b)=>{a=U.ja(a,b);return a.exists?a.object:null},ja:(a,b)=>{try{var c=U.l(a,{B:!b});a=c.path}catch(g){}var e={fa:!1,exists:!1,error:0,name:null,path:null,object:null,tb:!1,vb:null,ub:null};try{c=U.l(a,{parent:!0}),e.tb=!0,e.vb=c.path,e.ub=c.node,e.name=R(a),c=U.l(a,{B:!b}),e.exists=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.fa="/"===c.path}catch(g){e.error=g.o}return e},Fb:(a,b)=>{a="string"==typeof a?
a:U.J(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=S(a,c);try{U.mkdir(e)}catch(g){}a=e}}return e},cb:(a,b,c,e,g)=>{a=S("string"==typeof a?a:U.J(a),b);return U.create(a,U.oa(e,g))},Da:(a,b,c,e,g,h)=>{var l=b;a&&(a="string"==typeof a?a:U.J(a),l=b?S(a,b):a);a=U.oa(e,g);l=U.create(l,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(g=c.length;e<g;++e)b[e]=c.charCodeAt(e);c=b}U.chmod(l,a|146);b=U.open(l,577);U.write(b,c,0,c.length,0,h);U.close(b);U.chmod(l,a)}return l},
I:(a,b,c,e)=>{a=S("string"==typeof a?a:U.J(a),b);b=U.oa(!!c,!!e);U.I.ta||(U.I.ta=64);var g=U.O(U.I.ta++,0);U.ya(g,{open:h=>{h.seekable=!1},close:()=>{e&&e.buffer&&e.buffer.length&&e(10)},read:(h,l,p,q)=>{for(var n=0,r=0;r<q;r++){try{var w=c()}catch(A){throw new U.g(29);}if(void 0===w&&0===n)throw new U.g(6);if(null===w||void 0===w)break;n++;l[p+r]=w}n&&(h.node.timestamp=Date.now());return n},write:(h,l,p,q)=>{for(var n=0;n<q;n++)try{e(l[p+n])}catch(r){throw new U.g(29);}q&&(h.node.timestamp=Date.now());
return n}});return U.ha(a,b,g)},Ja:a=>{if(a.ra||a.nb||a.link||a.i)return!0;if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(t)try{a.i=nb(t(a.url)),a.m=a.i.length}catch(b){throw new U.g(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Db:(a,b,c,e,g)=>{function h(){this.sa=!1;this.da=
[]}h.prototype.get=function(n){if(!(n>this.length-1||0>n)){var r=n%this.chunkSize;return this.Ma(n/this.chunkSize|0)[r]}};h.prototype.lb=function(n){this.Ma=n};h.prototype.Ba=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),w,A=(w=n.getResponseHeader("Accept-Ranges"))&&"bytes"===w;n=(w=n.getResponseHeader("Content-Encoding"))&&
"gzip"===w;var B=1048576;A||(B=r);var z=this;z.lb(L=>{var fa=L*B,X=(L+1)*B-1;X=Math.min(X,r-1);if("undefined"==typeof z.da[L]){var Jb=z.da;if(fa>X)throw Error("invalid range ("+fa+", "+X+") or no bytes requested!");if(X>r-1)throw Error("only "+r+" bytes available! programmer error!");var E=new XMLHttpRequest;E.open("GET",c,!1);r!==B&&E.setRequestHeader("Range","bytes="+fa+"-"+X);E.responseType="arraybuffer";E.overrideMimeType&&E.overrideMimeType("text/plain; charset=x-user-defined");E.send(null);
if(!(200<=E.status&&300>E.status||304===E.status))throw Error("Couldn't load "+c+". Status: "+E.status);fa=void 0!==E.response?new Uint8Array(E.response||[]):nb(E.responseText||"");Jb[L]=fa}if("undefined"==typeof z.da[L])throw Error("doXHR failed!");return z.da[L]});if(n||!r)B=r=1,B=r=this.Ma(0).length,la("LazyFiles on gzip forces download of the whole file when length is accessed");this.Va=r;this.Ua=B;this.sa=!0};if("undefined"!=typeof XMLHttpRequest){if(!k)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var l=new h;Object.defineProperties(l,{length:{get:function(){this.sa||this.Ba();return this.Va}},chunkSize:{get:function(){this.sa||this.Ba();return this.Ua}}});l={ra:!1,i:l}}else l={ra:!1,url:c};var p=U.cb(a,b,l,e,g);l.i?p.i=l.i:l.url&&(p.i=null,p.url=l.url);Object.defineProperties(p,{m:{get:function(){return this.i.length}}});var q={};Object.keys(p.j).forEach(n=>{var r=p.j[n];q[n]=function(){U.Ja(p);return r.apply(null,arguments)}});q.read=(n,r,w,A,B)=>{U.Ja(p);n=n.node.i;if(B>=n.length)return 0;
A=Math.min(n.length-B,A);assert(0<=A);if(n.slice)for(var z=0;z<A;z++)r[w+z]=n[B+z];else for(z=0;z<A;z++)r[w+z]=n.get(B+z);return A};p.j=q;return p},Gb:(a,b,c,e,g,h,l,p,q,n)=>{function r(B){function z(L){n&&n();p||U.Da(a,b,L,e,g,q);h&&h();Xa(A)}vb.Lb(B,w,z,()=>{l&&l();Xa(A)})||z(B)}var w=b?T(S(a,b)):a,A=Va("cp "+w);Wa(A);"string"==typeof c?rb(c,B=>r(B),l):r(c)},indexedDB:()=>window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB,za:()=>"EM_FS_"+window.location.pathname,Aa:20,
T:"FILE_DATA",Vb:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});var e=U.indexedDB();try{var g=e.open(U.za(),U.Aa)}catch(h){return c(h)}g.onupgradeneeded=()=>{la("creating db");g.result.createObjectStore(U.T)};g.onsuccess=()=>{var h=g.result.transaction([U.T],"readwrite"),l=h.objectStore(U.T),p=0,q=0,n=a.length;a.forEach(r=>{r=l.put(U.ja(r).object.i,r);r.onsuccess=()=>{p++;p+q==n&&(0==q?b():c())};r.onerror=()=>{q++;p+q==n&&(0==q?b():c())}});h.onerror=c};g.onerror=c},Nb:(a,b,c)=>{b=b||(()=>{});c=c||(()=>{});
var e=U.indexedDB();try{var g=e.open(U.za(),U.Aa)}catch(h){return c(h)}g.onupgradeneeded=c;g.onsuccess=()=>{var h=g.result;try{var l=h.transaction([U.T],"readonly")}catch(w){c(w);return}var p=l.objectStore(U.T),q=0,n=0,r=a.length;a.forEach(w=>{var A=p.get(w);A.onsuccess=()=>{U.ja(w).exists&&U.unlink(w);U.Da(hb(w),R(w),A.result,!0,!0,!0);q++;q+n==r&&(0==n?b():c())};A.onerror=()=>{n++;q+n==r&&(0==n?b():c())}});l.onerror=c};g.onerror=c},Ab:()=>{f("FS.absolutePath has been removed; use PATH_FS.resolve instead")},
Cb:()=>{f("FS.createFolder has been removed; use FS.mkdir instead")},Eb:()=>{f("FS.createLink has been removed; use FS.symlink instead")},Mb:()=>{f("FS.joinPath has been removed; use PATH.join instead")},Qb:()=>{f("FS.mmapAlloc has been replaced by the top level function mmapAlloc")},Wb:()=>{f("FS.standardizePath has been removed; use PATH.normalize instead")}};
function wb(a,b,c){if("/"===b[0])return b;if(-100===a)a=U.cwd();else{a=U.R(a);if(!a)throw new U.g(8);a=a.path}if(0==b.length){if(!c)throw new U.g(44);return a}return S(a,b)}
function xb(a,b,c){try{var e=a(b)}catch(g){if(g&&g.node&&gb(b)!==gb(U.J(g.node)))return-54;throw g;}I[c>>2]=e.dev;I[c+4>>2]=0;I[c+8>>2]=e.ino;I[c+12>>2]=e.mode;I[c+16>>2]=e.nlink;I[c+20>>2]=e.uid;I[c+24>>2]=e.gid;I[c+28>>2]=e.rdev;I[c+32>>2]=0;Q=[e.size>>>0,(P=e.size,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[c+40>>2]=Q[0];I[c+44>>2]=Q[1];I[c+48>>2]=4096;I[c+52>>2]=e.blocks;I[c+56>>2]=e.atime.getTime()/1E3|0;I[c+60>>
2]=0;I[c+64>>2]=e.mtime.getTime()/1E3|0;I[c+68>>2]=0;I[c+72>>2]=e.ctime.getTime()/1E3|0;I[c+76>>2]=0;Q=[e.ino>>>0,(P=e.ino,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[c+80>>2]=Q[0];I[c+84>>2]=Q[1];return 0}var W=void 0;function Y(){assert(void 0!=W);W+=4;return I[W-4>>2]}function Z(a){a=U.R(a);if(!a)throw new U.g(8);return a}
function yb(a,b,c){function e(q){return(q=q.toTimeString().match(/\(([A-Za-z ]+)\)$/))?q[1]:"GMT"}var g=(new Date).getFullYear(),h=new Date(g,0,1),l=new Date(g,6,1);g=h.getTimezoneOffset();var p=l.getTimezoneOffset();I[a>>2]=60*Math.max(g,p);I[b>>2]=Number(g!=p);a=e(h);b=e(l);a=Ca(a);b=Ca(b);p<g?(I[c>>2]=a,I[c+4>>2]=b):(I[c>>2]=b,I[c+4>>2]=a)}function zb(a,b,c){zb.Xa||(zb.Xa=!0,yb(a,b,c))}function Ab(){void 0===Ab.start&&(Ab.start=Date.now());return 1E3*(Date.now()-Ab.start)|0}var Bb;
Bb=ha?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Cb={};function Db(){if(!Eb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Cb)void 0===Cb[b]?delete a[b]:a[b]=Cb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Eb=c}return Eb}var Eb;
function Fb(a,b,c,e){a||(a=this);this.parent=a;this.s=a.s;this.Z=null;this.id=U.rb++;this.name=b;this.mode=c;this.h={};this.j={};this.rdev=e}Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},nb:{get:function(){return U.u(this.mode)}},ra:{get:function(){return U.W(this.mode)}}});U.Sa=Fb;U.yb();var vb;
tb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,
ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,
EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function nb(a){var b=Array(Ba(a)+1);a=Aa(a,b,0,b.length);b.length=a;return b}
var Hb={__syscall_faccessat:function(a,b,c,e){try{b=F(b);assert(0===e);b=wb(a,b);if(c&-8)var g=-28;else{var h=U.l(b,{B:!0}).node;h?(a="",c&4&&(a+="r"),c&2&&(a+="w"),c&1&&(a+="x"),g=a&&U.K(h,a)?-2:0):g=-44}return g}catch(l){if("undefined"==typeof U||!(l instanceof U.g))throw l;return-l.o}},__syscall_fcntl64:function(a,b,c){W=c;try{var e=Z(a);switch(b){case 0:var g=Y();return 0>g?-28:U.open(e.path,e.flags,0,g).fd;case 1:case 2:return 0;case 3:return e.flags;case 4:return g=Y(),e.flags|=g,0;case 5:return g=
Y(),Fa[g+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return I[Gb()>>2]=28,-1;default:return-28}}catch(h){if("undefined"==typeof U||!(h instanceof U.g))throw h;return-h.o}},__syscall_fstat64:function(a,b){try{var c=Z(a);return xb(U.stat,c.path,b)}catch(e){if("undefined"==typeof U||!(e instanceof U.g))throw e;return-e.o}},__syscall_fstatat64:function(a,b,c,e){try{b=F(b);var g=e&256,h=e&4096;e&=-4353;assert(!e,e);b=wb(a,b,h);return xb(g?U.lstat:U.stat,b,c)}catch(l){if("undefined"==
typeof U||!(l instanceof U.g))throw l;return-l.o}},__syscall_getdents64:function(a,b,c){try{var e=Z(a);e.L||(e.L=U.readdir(e.path));a=0;for(var g=U.A(e,0,1),h=Math.floor(g/280);h<e.L.length&&a+280<=c;){var l=e.L[h];if("."===l){var p=e.node.id;var q=4}else if(".."===l)p=U.l(e.path,{parent:!0}).node.id,q=4;else{var n=U.D(e.node,l);p=n.id;q=U.W(n.mode)?2:U.u(n.mode)?4:U.M(n.mode)?10:8}assert(p);Q=[p>>>0,(P=p,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>
0))/4294967296)>>>0:0)];I[b+a>>2]=Q[0];I[b+a+4>>2]=Q[1];Q=[280*(h+1)>>>0,(P=280*(h+1),1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[b+a+8>>2]=Q[0];I[b+a+12>>2]=Q[1];Fa[b+a+16>>1]=280;D[b+a+18>>0]=q;wa(l,b+a+19,256);a+=280;h+=1}U.A(e,280*h,0);return a}catch(r){if("undefined"==typeof U||!(r instanceof U.g))throw r;return-r.o}},__syscall_ioctl:function(a,b,c){W=c;try{var e=Z(a);switch(b){case 21509:case 21505:return e.tty?
0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return e.tty?0:-59;case 21519:if(!e.tty)return-59;var g=Y();return I[g>>2]=0;case 21520:return e.tty?-28:-59;case 21531:return g=Y(),U.qa(e,b,g);case 21523:return e.tty?0:-59;case 21524:return e.tty?0:-59;default:f("bad ioctl syscall "+b)}}catch(h){if("undefined"==typeof U||!(h instanceof U.g))throw h;return-h.o}},__syscall_lstat64:function(a,b){try{return a=F(a),xb(U.lstat,a,b)}catch(c){if("undefined"==typeof U||!(c instanceof
U.g))throw c;return-c.o}},__syscall_open:function(a,b,c){W=c;try{var e=F(a),g=c?Y():0;return U.open(e,b,g).fd}catch(h){if("undefined"==typeof U||!(h instanceof U.g))throw h;return-h.o}},__syscall_rename:function(a,b){try{return a=F(a),b=F(b),U.rename(a,b),0}catch(c){if("undefined"==typeof U||!(c instanceof U.g))throw c;return-c.o}},__syscall_rmdir:function(a){try{return a=F(a),U.rmdir(a),0}catch(b){if("undefined"==typeof U||!(b instanceof U.g))throw b;return-b.o}},__syscall_stat64:function(a,b){try{return a=
F(a),xb(U.stat,a,b)}catch(c){if("undefined"==typeof U||!(c instanceof U.g))throw c;return-c.o}},__syscall_unlink:function(a){try{return a=F(a),U.unlink(a),0}catch(b){if("undefined"==typeof U||!(b instanceof U.g))throw b;return-b.o}},_gmtime_js:function(a,b){a=new Date(1E3*I[a>>2]);I[b>>2]=a.getUTCSeconds();I[b+4>>2]=a.getUTCMinutes();I[b+8>>2]=a.getUTCHours();I[b+12>>2]=a.getUTCDate();I[b+16>>2]=a.getUTCMonth();I[b+20>>2]=a.getUTCFullYear()-1900;I[b+24>>2]=a.getUTCDay();I[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),
0,1,0,0,0,0))/864E5|0},_localtime_js:function(a,b){a=new Date(1E3*I[a>>2]);I[b>>2]=a.getSeconds();I[b+4>>2]=a.getMinutes();I[b+8>>2]=a.getHours();I[b+12>>2]=a.getDate();I[b+16>>2]=a.getMonth();I[b+20>>2]=a.getFullYear()-1900;I[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);I[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;I[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();I[b+32>>2]=(e!=c&&a.getTimezoneOffset()==Math.min(c,
e))|0},_mktime_js:function(a){var b=new Date(I[a+20>>2]+1900,I[a+16>>2],I[a+12>>2],I[a+8>>2],I[a+4>>2],I[a>>2],0),c=I[a+32>>2],e=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),h=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),l=g.getTimezoneOffset(),p=Math.min(l,h);0>c?I[a+32>>2]=Number(h!=l&&p==e):0<c!=(p==e)&&(h=Math.max(l,h),b.setTime(b.getTime()+6E4*((0<c?p:h)-e)));I[a+24>>2]=b.getDay();I[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;I[a>>2]=b.getSeconds();I[a+4>>2]=b.getMinutes();I[a+
8>>2]=b.getHours();I[a+12>>2]=b.getDate();I[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},_tzset_js:zb,abort:function(){f("native code called abort()")},clock:Ab,clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Bb();else return I[Gb()>>2]=28,-1;I[b>>2]=a/1E3|0;I[b+4>>2]=a%1E3*1E6|0;return 0},emscripten_get_now:Bb,emscripten_memcpy_big:function(a,b,c){H.copyWithin(a,b,b+c)},emscripten_resize_heap:function(a){var b=H.length;a>>>=0;assert(a>b);if(2147483648<a)return x("Cannot enlarge memory, asked to go up to "+
a+" bytes, but the limit is 2147483648 bytes!"),!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var g=Math;e=Math.max(a,e);g=g.min.call(g,2147483648,e+(65536-e%65536)%65536);e=Bb();a:{var h=g;try{ra.grow(h-Ea.byteLength+65535>>>16);Ha();var l=1;break a}catch(p){x("emscripten_realloc_buffer: Attempted to grow heap from "+Ea.byteLength+" bytes to "+h+" bytes, but got error: "+p)}l=void 0}h=Bb();la("Heap resize call from "+b+" to "+g+" took "+(h-e)+" msecs. Success: "+!!l);if(l)return!0}x("Failed to grow the heap from "+
b+" bytes to "+g+" bytes, not enough memory!");return!1},environ_get:function(a,b){var c=0;Db().forEach(function(e,g){var h=b+c;g=I[a+4*g>>2]=h;for(h=0;h<e.length;++h)assert(e.charCodeAt(h)===(e.charCodeAt(h)&255)),D[g++>>0]=e.charCodeAt(h);D[g>>0]=0;c+=e.length+1});return 0},environ_sizes_get:function(a,b){var c=Db();I[a>>2]=c.length;var e=0;c.forEach(function(g){e+=g.length+1});I[b>>2]=e;return 0},fd_close:function(a){try{var b=Z(a);U.close(b);return 0}catch(c){if("undefined"==typeof U||!(c instanceof
U.g))throw c;return c.o}},fd_fdstat_get:function(a,b){try{var c=Z(a);D[b>>0]=c.tty?2:U.u(c.mode)?3:U.M(c.mode)?7:4;return 0}catch(e){if("undefined"==typeof U||!(e instanceof U.g))throw e;return e.o}},fd_read:function(a,b,c,e){try{a:{for(var g=Z(a),h=a=0;h<c;h++){var l=I[b+(8*h+4)>>2],p=U.read(g,D,I[b+8*h>>2],l,void 0);if(0>p){var q=-1;break a}a+=p;if(p<l)break}q=a}I[e>>2]=q;return 0}catch(n){if("undefined"==typeof U||!(n instanceof U.g))throw n;return n.o}},fd_seek:function(a,b,c,e,g){try{var h=Z(a);
a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;U.A(h,a,e);Q=[h.position>>>0,(P=h.position,1<=+Math.abs(P)?0<P?(Math.min(+Math.floor(P/4294967296),4294967295)|0)>>>0:~~+Math.ceil((P-+(~~P>>>0))/4294967296)>>>0:0)];I[g>>2]=Q[0];I[g+4>>2]=Q[1];h.L&&0===a&&0===e&&(h.L=null);return 0}catch(l){if("undefined"==typeof U||!(l instanceof U.g))throw l;return l.o}},fd_write:function(a,b,c,e){try{a:{for(var g=Z(a),h=a=0;h<c;h++){var l=U.write(g,D,I[b+8*h>>2],I[b+(8*h+4)>>2],void 0);
if(0>l){var p=-1;break a}a+=l}p=a}I[e>>2]=p;return 0}catch(q){if("undefined"==typeof U||!(q instanceof U.g))throw q;return q.o}},gettimeofday:function(a){var b=Date.now();I[a>>2]=b/1E3|0;I[a+4>>2]=b%1E3*1E3|0;return 0},setTempRet0:function(){}};
(function(){function a(h){d.asm=h.exports;ra=d.asm.memory;assert(ra,"memory not found in wasm exports");Ha();Ja=d.asm.__indirect_function_table;assert(Ja,"table not found in wasm exports");Qa.unshift(d.asm.__wasm_call_ctors);Xa("wasm-instantiate")}function b(h){assert(d===g,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");g=null;a(h.instance)}function c(h){return ab().then(function(l){return WebAssembly.instantiate(l,e)}).then(function(l){return l}).then(h,
function(l){x("failed to asynchronously prepare wasm: "+l);N.startsWith("file://")&&x("warning: Loading from a file URI ("+N+") is not supported in most browsers. See https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-run-a-local-webserver-for-testing-why-does-my-program-stall-in-downloading-or-preparing");f(l)})}var e={env:Hb,wasi_snapshot_preview1:Hb};Wa("wasm-instantiate");var g=d;if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(h){return x("Module.instantiateWasm callback failed with error: "+
h),!1}(function(){return qa||"function"!=typeof WebAssembly.instantiateStreaming||Ya()||N.startsWith("file://")||"function"!=typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,e).then(b,function(l){x("wasm streaming compile failed: "+l);x("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();d.___wasm_call_ctors=O("__wasm_call_ctors");var Da=d._malloc=O("malloc");d._decode=O("decode");
d._open_audio_decode=O("open_audio_decode");d._audio_decode=O("audio_decode");d._close_audio_decode=O("close_audio_decode");d._encode=O("encode");d._open_audio_encode=O("open_audio_encode");d._audio_encode=O("audio_encode");d._close_audio_encode=O("close_audio_encode");
var Gb=d.___errno_location=O("__errno_location"),ub=d.___stdio_exit=O("__stdio_exit"),qb=d._emscripten_builtin_memalign=O("emscripten_builtin_memalign"),Ib=d._emscripten_stack_init=function(){return(Ib=d._emscripten_stack_init=d.asm.emscripten_stack_init).apply(null,arguments)};d._emscripten_stack_get_free=function(){return(d._emscripten_stack_get_free=d.asm.emscripten_stack_get_free).apply(null,arguments)};
d._emscripten_stack_get_base=function(){return(d._emscripten_stack_get_base=d.asm.emscripten_stack_get_base).apply(null,arguments)};var La=d._emscripten_stack_get_end=function(){return(La=d._emscripten_stack_get_end=d.asm.emscripten_stack_get_end).apply(null,arguments)},xa=d.stackSave=O("stackSave"),ya=d.stackRestore=O("stackRestore"),va=d.stackAlloc=O("stackAlloc");d.dynCall_jiji=O("dynCall_jiji");d.dynCall_iiiji=O("dynCall_iiiji");d.dynCall_jiiij=O("dynCall_jiiij");d.dynCall_jiiji=O("dynCall_jiiji");
d.dynCall_viiijj=O("dynCall_viiijj");d.dynCall_jij=O("dynCall_jij");d.dynCall_jii=O("dynCall_jii");C("intArrayFromString",!1);C("intArrayToString",!1);C("ccall",!1);d.cwrap=function(a,b,c){return function(){return ua(a,b,c,arguments)}};C("setValue",!1);C("getValue",!1);C("allocate",!1);C("UTF8ArrayToString",!1);C("UTF8ToString",!1);C("stringToUTF8Array",!1);C("stringToUTF8",!1);C("lengthBytesUTF8",!1);C("stackTrace",!1);C("addOnPreRun",!1);C("addOnInit",!1);C("addOnPreMain",!1);C("addOnExit",!1);
C("addOnPostRun",!1);C("writeStringToMemory",!1);C("writeArrayToMemory",!1);C("writeAsciiToMemory",!1);C("addRunDependency",!0);C("removeRunDependency",!0);C("FS_createFolder",!1);C("FS_createPath",!0);C("FS_createDataFile",!0);C("FS_createPreloadedFile",!0);C("FS_createLazyFile",!0);C("FS_createLink",!1);C("FS_createDevice",!0);C("FS_unlink",!0);C("getLEB",!1);C("getFunctionTables",!1);C("alignFunctionTables",!1);C("registerFunctions",!1);C("addFunction",!1);C("removeFunction",!1);
C("getFuncWrapper",!1);C("prettyPrint",!1);C("dynCall",!1);C("getCompilerSetting",!1);C("print",!1);C("printErr",!1);C("getTempRet0",!1);C("setTempRet0",!1);C("callMain",!1);C("abort",!1);C("keepRuntimeAlive",!1);C("zeroMemory",!1);C("stringToNewUTF8",!1);C("emscripten_realloc_buffer",!1);C("ENV",!1);C("withStackSave",!1);C("ERRNO_CODES",!1);C("ERRNO_MESSAGES",!1);C("setErrNo",!1);C("inetPton4",!1);C("inetNtop4",!1);C("inetPton6",!1);C("inetNtop6",!1);C("readSockaddr",!1);C("writeSockaddr",!1);
C("DNS",!1);C("getHostByName",!1);C("Protocols",!1);C("Sockets",!1);C("getRandomDevice",!1);C("traverseStack",!1);C("convertFrameToPC",!1);C("UNWIND_CACHE",!1);C("saveInUnwindCache",!1);C("convertPCtoSourceLocation",!1);C("readAsmConstArgsArray",!1);C("readAsmConstArgs",!1);C("mainThreadEM_ASM",!1);C("jstoi_q",!1);C("jstoi_s",!1);C("getExecutableName",!1);C("listenOnce",!1);C("autoResumeAudioContext",!1);C("dynCallLegacy",!1);C("getDynCaller",!1);C("dynCall",!1);C("callRuntimeCallbacks",!1);
C("wasmTableMirror",!1);C("setWasmTableEntry",!1);C("getWasmTableEntry",!1);C("handleException",!1);C("runtimeKeepalivePush",!1);C("runtimeKeepalivePop",!1);C("callUserCallback",!1);C("maybeExit",!1);C("safeSetTimeout",!1);C("asmjsMangle",!1);C("asyncLoad",!1);C("alignMemory",!1);C("mmapAlloc",!1);C("reallyNegative",!1);C("unSign",!1);C("reSign",!1);C("formatString",!1);C("PATH",!1);C("PATH_FS",!1);C("SYSCALLS",!1);C("getSocketFromFD",!1);C("getSocketAddress",!1);C("JSEvents",!1);
C("registerKeyEventCallback",!1);C("specialHTMLTargets",!1);C("maybeCStringToJsString",!1);C("findEventTarget",!1);C("findCanvasEventTarget",!1);C("getBoundingClientRect",!1);C("fillMouseEventData",!1);C("registerMouseEventCallback",!1);C("registerWheelEventCallback",!1);C("registerUiEventCallback",!1);C("registerFocusEventCallback",!1);C("fillDeviceOrientationEventData",!1);C("registerDeviceOrientationEventCallback",!1);C("fillDeviceMotionEventData",!1);C("registerDeviceMotionEventCallback",!1);
C("screenOrientation",!1);C("fillOrientationChangeEventData",!1);C("registerOrientationChangeEventCallback",!1);C("fillFullscreenChangeEventData",!1);C("registerFullscreenChangeEventCallback",!1);C("registerRestoreOldStyle",!1);C("hideEverythingExceptGivenElement",!1);C("restoreHiddenElements",!1);C("setLetterbox",!1);C("currentFullscreenStrategy",!1);C("restoreOldWindowedStyle",!1);C("softFullscreenResizeWebGLRenderTarget",!1);C("doRequestFullscreen",!1);C("fillPointerlockChangeEventData",!1);
C("registerPointerlockChangeEventCallback",!1);C("registerPointerlockErrorEventCallback",!1);C("requestPointerLock",!1);C("fillVisibilityChangeEventData",!1);C("registerVisibilityChangeEventCallback",!1);C("registerTouchEventCallback",!1);C("fillGamepadEventData",!1);C("registerGamepadEventCallback",!1);C("registerBeforeUnloadEventCallback",!1);C("fillBatteryEventData",!1);C("battery",!1);C("registerBatteryEventCallback",!1);C("setCanvasElementSize",!1);C("getCanvasElementSize",!1);C("demangle",!1);
C("demangleAll",!1);C("jsStackTrace",!1);C("stackTrace",!1);C("getEnvStrings",!1);C("checkWasiClock",!1);C("writeI53ToI64",!1);C("writeI53ToI64Clamped",!1);C("writeI53ToI64Signaling",!1);C("writeI53ToU64Clamped",!1);C("writeI53ToU64Signaling",!1);C("readI53FromI64",!1);C("readI53FromU64",!1);C("convertI32PairToI53",!1);C("convertU32PairToI53",!1);C("setImmediateWrapped",!1);C("clearImmediateWrapped",!1);C("polyfillSetImmediate",!1);C("uncaughtExceptionCount",!1);C("exceptionLast",!1);
C("exceptionCaught",!1);C("ExceptionInfo",!1);C("CatchInfo",!1);C("exception_addRef",!1);C("exception_decRef",!1);C("Browser",!1);C("funcWrappers",!1);C("getFuncWrapper",!1);C("setMainLoop",!1);C("wget",!1);C("FS",!1);C("MEMFS",!1);C("TTY",!1);C("PIPEFS",!1);C("SOCKFS",!1);C("_setNetworkCallback",!1);C("tempFixedLengthArray",!1);C("miniTempWebGLFloatBuffers",!1);C("heapObjectForWebGLType",!1);C("heapAccessShiftForWebGLHeap",!1);C("GL",!1);C("emscriptenWebGLGet",!1);
C("computeUnpackAlignedImageSize",!1);C("emscriptenWebGLGetTexPixelData",!1);C("emscriptenWebGLGetUniform",!1);C("webglGetUniformLocation",!1);C("webglPrepareUniformLocationsBeforeFirstUse",!1);C("webglGetLeftBracePos",!1);C("emscriptenWebGLGetVertexAttrib",!1);C("writeGLArray",!1);C("AL",!1);C("SDL_unicode",!1);C("SDL_ttfContext",!1);C("SDL_audio",!1);C("SDL",!1);C("SDL_gfx",!1);C("GLUT",!1);C("EGL",!1);C("GLFW_Window",!1);C("GLFW",!1);C("GLEW",!1);C("IDBStore",!1);C("runAndAbortIfError",!1);
C("warnOnce",!1);C("stackSave",!1);C("stackRestore",!1);C("stackAlloc",!1);C("AsciiToString",!1);C("stringToAscii",!1);C("UTF16ToString",!1);C("stringToUTF16",!1);C("lengthBytesUTF16",!1);C("UTF32ToString",!1);C("stringToUTF32",!1);C("lengthBytesUTF32",!1);C("allocateUTF8",!1);C("allocateUTF8OnStack",!1);d.writeStackCookie=Ka;d.checkStackCookie=Ma;pa("ALLOC_NORMAL");pa("ALLOC_STACK");var Kb;Ua=function Lb(){Kb||Mb();Kb||(Ua=Lb)};
function Mb(){function a(){if(!Kb&&(Kb=!0,d.calledRun=!0,!sa)){Ma();assert(!Sa);Sa=!0;d.noFSInit||U.V.ea||U.V();U.Pa=!1;bb(Qa);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();assert(!d._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');Ma();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Ra.unshift(b)}bb(Ra)}}if(!(0<J)){Ib();Ka();if(d.preRun)for("function"==typeof d.preRun&&
(d.preRun=[d.preRun]);d.preRun.length;)Ta();bb(Pa);0<J||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a(),Ma())}}d.run=Mb;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();Mb();self.FS=U;


  return createFFmepgModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = createFFmepgModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return createFFmepgModule; });
else if (typeof exports === 'object')
  exports["createFFmepgModule"] = createFFmepgModule;
